### ISSUE TITLE
Error when changing the birth date

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#1015]
![Capture d’écran 2024-05-21 à 16 49 38](https://github.com/geokrety/geokrety-website/assets/77342426/897cb728-ed2a-4c41-b4bb-c575b519acbb)
![Capture d’écran 2024-05-21 à 16 49 52](https://github.com/geokrety/geokrety-website/assets/77342426/fa32bb53-950a-4530-a9d6-d7bd996053ab)

**Comment by kumy** [comment]
doh! @GGGuerin Do you have the same issue if you switch the side in English?

**Comment by kumy** [comment]
I'm not able to reproduce :/

**Comment by kumy** [comment]
Do you see something special in the Firefox developper console?

**Comment by kumy** [comment]
I was able to reproduce with your GK, my guess is it's related to the archiving state, let's see :eye:

**Comment by GGGuerin** [comment]
OK .... when I work in english, I can change the birthdate. 
But when i create a move younger than the new birthdate, it does not work ....
![Capture d’écran 2024-05-21 à 18 55 14](https://github.com/geokrety/geokrety-website/assets/77342426/f4d39b98-860b-4d08-903b-edb90a594dc8)
![Capture d’écran 2024-05-21 à 18 55 24](https://github.com/geokrety/geokrety-website/assets/77342426/3d7d09e9-dee0-4b4e-bea7-e8e5efec945a)

**Comment by kumy** [comment]
I think I've fixed both issues, I just pushed the commits it should be live on staging https://staging.geokrety.org/ in a a few minutes. @GGGuerin Please test there and keep me posted :)

**Comment by kumy** [comment]
(FTR Another user reported the second issue via support)

**Comment by GGGuerin** [comment]
New issue ... Birth date is older than the date of the move
![Capture d’écran 2024-05-23 à 08 16 53](https://github.com/geokrety/geokrety-website/assets/77342426/a5251985-0e19-4ea5-bedb-408e23ececa8)

**Comment by kumy** [comment]
@GGGuerin I was able to post the same log as in your screenshot
https://geokrety.org/en/geokrety/GK180EF/page/1#log5385466

**Comment by GGGuerin** [comment]
> @GGGuerin I was able to post the same log as in your screenshot https://geokrety.org/en/geokrety/GK180EF/page/1#log5385466
Let me do a trial ;-)

**Comment by GGGuerin** [comment]
This GK was "initially" created one or two days ago. So if you try to log before this initial birthdate, it does not work ....
![Capture d’écran 2024-05-23 à 17 29 36](https://github.com/geokrety/geokrety-website/assets/77342426/f9d33b0e-ea54-46f9-b212-686b14f3047a)

**Comment by kumy** [comment]
Ha French... let me try in French. Could you try the English version on your side :pray:

**Comment by GGGuerin** [comment]
Trial in english.... 
![Capture d’écran 2024-05-23 à 17 34 40](https://github.com/geokrety/geokrety-website/assets/77342426/021d0c85-b3d9-4ade-97c4-32b70f5b12b7)

**Comment by kumy** [comment]
Yep, I saw you in the logs ;)
Still trying to understand what could be the issue

**Comment by GGGuerin** [comment]
> Yep, I saw you in the logs ;) Still trying to understand what could be the issue

It seems that it does take into account the "initial" birth date, doesn't it ?

**Comment by kumy** [comment]
> It seems that it does take into account the "initial" birth date, doesn't it ?

yes :(

I was finally able to reproduce :partying_face:

**Comment by GGGuerin** [comment]
![Capture d’écran 2024-05-23 à 17 41 19](https://github.com/geokrety/geokrety-website/assets/77342426/9f9dd36a-41c9-4da9-9dd9-601b2fbdcb8a)

**Comment by kumy** [comment]
I think I have the root cause and the fix in this PR https://github.com/geokrety/geokrety-website/pull/1017/files. Now I want to have the unit tests fixed. That should have been detected :smiling_imp:

**Comment by kumy** [comment]
2.50.1 is deployed
![image](https://github.com/geokrety/geokrety-website/assets/176794/e86184aa-692e-4546-8395-589c007b8fb7)

**Comment by GGGuerin** [comment]
It works ! Great !
Thanks
