### ISSUE TITLE
Automatic deploy en rec and prod

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#104]
As discussed [here](https://github.com/geokrety/geokrety-website/pull/77#issuecomment-397586848)

> would be really useful to move "prod" and "rec" tags (or branches) for deployed things (like you do for "boly38" one)
    * in fact 'master' is not PROD deployed version (and maybe not always 'rec' deployed version too..)
    * footer commit SHA1 is not sufficient while a given commit could disappear on force push action

**Comment by kumy** [comment]
I propose to have:
* `master` to be the integration branch, commits pushed there will trigger update of https://rec.geokrety.org
* `prod` to be the production branch, commits pushed there will trigger update of https://geokrety.org.

Additionally, we'll have core developer branches called `boly38`, `filips` and `kumy`. Deployed automatically using the same branches names.

To rephrase:
Our pull requests have to be merged first in `master`, then tested at https://rec.geokrety.org. When validated, a merge (commit or fast forward) from `master` to prod will trigger update of https://geokrety.org.

@boly38 is this ok for you?

**Comment by boly38** [comment]
sorry to miss that issue, sure, ok! :)

**Comment by kumy** [comment]
Note: don't forget to deploy the same feature for cdn

**Comment by kumy** [comment]
This is ready, but it will only work if the merge to `prod` include commit afe987ad8c0514ac8d351094688d847910f8bc3a
