### ISSUE TITLE
Feature: Short URL to Krety log

### ISSUE THREAD

**Issue by sdennler** [geokrety/geokrety-website#1040]
For GeoKreties with limited space to write the note (example: NFC-Tags), it would be great to have a short URL to the tracking site.

Instead of

https://geokrety.org/de/moves?tracking_code=XXXXX

Some thing like

https://geokrety.org/XXXXX
https://geokrety.org/m/XXXXX

Yes, there are URL shortener available, but they are usually bad and not reliable. And a plain URL is more trustworty.

**Comment by kumy** [comment]
`https://geokrety.org/m/XXXXX` will be supported in v2.54.1

**Comment by sdennler** [comment]
Thank you for the fast implementation. Works well!
