### ISSUE TITLE
watchlist mailing - images are broken

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#1054]
hi 👋 GK team, hope you're well ! thanks for this amazing service :) 👍 

In my watchlist mailing I noticed two things
- since a while (cant say the starting date) the GC image is broken
 
![image](https://github.com/user-attachments/assets/921061d7-0002-42fb-a5cf-f52c5f5ebca7)

- since between July 18..July22 the in/out first col image is broken

![image](https://github.com/user-attachments/assets/d5ef3e42-4764-4cb3-a650-fea58a9ef29b)

It's so not critical :)
have a good day
see you

**Comment by kumy** [comment]
Hi! 👏
Nice to hear from you, it's been a long time!

Thanks. I will have a look after my vacations (unless you want to fix it by yourself 🤗)

**Comment by boly38** [comment]
> (unless you want to fix it by yourself 🤗)
héhé by curiosity only I put an eye on analysis to help (2 cents) you to switch in when you will be back

buggy mail example of movicon that is not showed
`<img src="https://ci3.googleusercontent.com/meips/ADKq_NbvkRvzfXxubUk66bWTVl-H6cKEbJlvhAiE7cciTsucEKAwgzx6ixLNqC7e-VFYRoU3tZiZdwAxcaIGjdwnw4DrRK5coxsF=s0-d-e1-ft#https://cdn.geokrety.org/images/log-icons/0/5.svg" title="5662001: transité" width="37px" height="37px" `

NB: strange prefix before https://cdn.geokrety.org/images/log-icons/0/5.svg (which show image) : maybe some cache logic

## daily generation path

- [cli dailymail](https://github.com/geokrety/geokrety-website/blob/4e4882a01e71b37bdf27f9538488ac39b07fc1df/website/app/GeoKrety/Controller/Cli/DailyMail.php#L169)
- => [send daily](https://github.com/geokrety/geokrety-website/blob/main/website/app/GeoKrety/Email/DailyMail.php#L27)
- => rely on template [daily-mail.tpl](https://github.com/geokrety/geokrety-website/blob/4e4882a01e71b37bdf27f9538488ac39b07fc1df/website/app-templates/smarty/emails/daily-mail.tpl#L90) with
- move icon  > `logicon`
- cache icon > `cachelink` ?

those icons definition are in [smarty extension](https://github.com/geokrety/geokrety-website/blob/4e4882a01e71b37bdf27f9538488ac39b07fc1df/website/app-templates/smarty/extension/SmartyGeokretyExtension.php#L435-L460)

where img src link prefix is drived by  `GK_CDN_IMAGES_URL`
-> unable to find definition (maybe env var) ?

**Comment by kumy** [comment]
I have a copy of the emails, and they render well in Thunderbird

I can confirm they are not rendering well on gmail portal

Thunderbird
![image](https://github.com/user-attachments/assets/36448813-a277-4df7-b952-db265410f5a6)

`GK_CDN_IMAGES_URL` is effectively an env var, it's defined [there](https://github.com/geokrety/geokrety-website/blob/4e4882a01e71b37bdf27f9538488ac39b07fc1df/website/app/GeoKrety/Service/Config.php#L422) for its default value

**Comment by kumy** [comment]
This is probably the issue here
https://stackoverflow.com/a/53964335/944936

shame on Google!

**Comment by kumy** [comment]
> since a while (cant say the starting date) the GC image is broken
It should be since the GKv2 migration. Flags were always been svg files

**Comment by kumy** [comment]
- I don't want to duplicate the images in multiple formats
- I don't want to step back to jpg/png

We could:
- implement a new internal microservice
  - that use `rsvg-convert` to transform svg to png
- configure a special endpoint, restricted to svg, in nginx that will proxy_pass the request to the rsvg-convert service (with some caching?)
- update the [smarty extensions](https://github.com/geokrety/geokrety-website/blob/main/website/app-templates/smarty/extension/SmartyGeokretyExtension.php#L296) that render images to support a new output type (which will just change the path to the 'svg' image - using the new nginx special url)
- update the email templates to use the new output type
  - eventually doing such based on user destination email (if gmail.com then do it else keep the actual behavior - we could add other exceptions later if we have other complaints)

**Comment by kumy** [comment]
Here is a demo of an on-the-fly svg to png converter
https://github.com/geokrety/GeoKrety-Static/commit/ed4c50ff06fd3e17a4355354dc2cca95a6e7e572

Can be used by simply adding `.png` at the end of file name
`curl https://cdn...../flags/4x3/fr.svg` -> `curl https://cdn...../flags/4x3/fr.svg.png`

![image](https://github.com/user-attachments/assets/278cb20c-c589-4587-adad-be49fbc3a178)


- still need to properly detect 404

**Comment by kumy** [comment]
Ok, first part for the OTF image conversion deployed on staging only :heavy_check_mark: 

samples:
- https://cdn.staging.geokrety.org/images/the-mole-with-name.svg
- https://cdn.staging.geokrety.org/images/the-mole-with-name.svg.png

@boly38 If you wish to handle the next steps it's up to you, I'll see if I find time before our leave. But in any case I will not publish the fix to prod before our leave.

**Comment by kumy** [comment]
I'll deploy the fix on staging and will manually hack the system to force it send a test mail from there

**Comment by kumy** [comment]
oh yeah! :man_dancing: 

Done (but will be deployed on prod later).

### Working in gmail
Sample image link: `https://ci3.googleusercontent.com/meips/ADKq_NYdz-OxvF6S3H5w3fxrE-YnZ-hESv_0IzfQGSLIfNEXjOkUR9B-J7S7ghHYqicCnWbpbL1TGtvMSDL_hZejDQlqjQQMoW0J7x3WAA=s0-d-e1-ft#https://cdn.staging.geokrety.org/flags/4x3/fr.svg.png`
![image](https://github.com/user-attachments/assets/4fe2428d-d5a2-4f04-9639-df024a391a70)

### working in Thunderbird
![image](https://github.com/user-attachments/assets/b10a9161-8c59-492e-84a9-e974b76c7eb0)


### picture on website are still svg
![image](https://github.com/user-attachments/assets/45523338-7b04-4cd0-93ba-105eb5e62c58)

**Comment by kumy** [comment]
I finally deployed the change, I'm pretty confident with it.

Thanks for reporting!

**Comment by boly38** [comment]
Hey what support ! it was not critical of course but you're amazing 🚀 
many thanks 🙏

**Comment by boly38** [comment]
QA note Date:	1 sept. 2024 08:08 > watchlist mailing is now OK ! thanks :)
