### ISSUE TITLE
race map not working

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#109]
Context:
- I just miss end date to add my geokrety on previous one (id=13)
- race id=13 could be deleted (if possible)
- I'm now able to add GK with 5 digit onto just recreated race (id=14) (there is no way to add geokret once a given race is started)

This issue is the following:
- on [race (14) page](https://geokrety.org/race.php?raceid=14), google maps doesn't show the map:

![image](https://user-images.githubusercontent.com/3100576/41717846-5691473e-755b-11e8-8eb6-e7a4c73f7342.png)

race is not fully supported but seems see in advance what related to #87 
- maybe there is a way to migrate/use maps like onto konkret.php page, or we will get same result soon ? move onto openstreetmap ?

**Comment by kumy** [comment]
For the map not loading, issue is `Google Maps JavaScript API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error`
