### ISSUE TITLE
Feature Request - Rate limit `export*.php`

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#12]
We started to talk about that in #10 and #11.

The `export*.php` are quite time consuming. We should deploy some kind of `rate limiting` on those endpoints.

It seems possible to achieve this using [NGinx](https://www.nginx.com/blog/rate-limiting-nginx/)

Some partners should be able to do lot of queries to synchronize their database. This include at least opencaching* sites, geokretymap.org.

**Comment by kumy** [comment]
Link to https://github.com/geokrety/geokrety-api/issues/27 for the Api-NG issue.

**Comment by kumy** [comment]
The production instance use [Apache2](https://github.com/geokrety/geokrety-website/blob/757f3000093b214da149f309adaa5188a592710a/Dockerfile#L1) at the moment…

**Comment by kumy** [comment]
An example of rate limit on [GKM](https://github.com/GeoKretyMap/gkm-api-nginx/blob/master/conf.d/api.geokretymap.org.conf#L114)

**Comment by romain-dartigues** [comment]
Or HAProxy [ref](https://blog.serverfault.com/2010/08/26/1016491873/),
or [Redis](https://redis.io/commands/incr#pattern-rate-limiter).

A full protection should probably:
* limit per IP when no API was given
* limit per API (avoid DDoS)
* global limit per endpoint (disable only part of the website to protect the others services)

**Comment by kumy** [comment]
Next Traefik version will support basic ratelimiting with labels

https://docs.traefik.io/v1.6/configuration/commons/#rate-limiting
