### ISSUE TITLE
Missing text when waypoint is unknown

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#133]
From mail:

Since some time, on the `ruchy` page, the validation message when a waypoint coordinates are missing from the database asking user to provide coordinates is missing.

### step to reproduce

1. open https://rec.geokrety.org/ruchy.php
1. Fill logtype (drop/seen/dipped), tracking code
1. Fill waypoint field to any value not in our database (e.g. OC999999)

### expected result

The message on the right should indicate the user that he have to fill coordinates

### actual result

Only the `No cache found` message is displayed.

### Note

If the rest of the fields are filled (except the coordinates), the form is not validated and the message `Missing or invalid coordinates.` is shown.

**Comment by boly38** [comment]
another usecase:
- fille the form
- search "voyages"
- on (1) result "voyages" string must be removed by javascript (this is not the case)
- on submit, the log is stored without coordinates! :(  (ex. last 2 logs on  https://rec.geokrety.org/konkret.php?id=67904 )

**Comment by boly38** [comment]
As requirement for this issue, I started a QA project in order to avoid loss of ruchy feature following new release: cf [geokrety-website-qa](https://github.com/geokrety/geokrety-website-qa) project.

WIP on ruchy page dedicated scenario.

**Comment by boly38** [comment]
How do we plan to moderate this case ? any idea @kumy ?

(that was done on "rec")
- go to ruchy page, fill as waypoint ("GC_DELIRAN") , fill coordinates, submit the form,
- after the steps above, database includes a wrong waypoint code with valid coordinates.

Suggestion:
- create a dedicated issue
- add "signal an error" button : I'm absolutely not a fan of this solution.
- add automated check of (Waypoint code => coordinates): feasible ? seems hard as we don't have only "GC" as prefix.. need to handle all cases

**Comment by kumy** [comment]
>How do we plan to moderate this case ?

@boly38 As I understand it, shouldn't it be a dedicated issue?

**Comment by boly38** [comment]
I dont keep latest character `.` to match other error case => `No cache found`
