### ISSUE TITLE
New abreviation at geocaching.su

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#138]
Received from @okainov by support mail.

> Just wanted to notify you that we introduced two new abbreviations "LT" and "LV" for "mystery" caches on our website geocaching.su. I'm not sure does it require any actions from your side to make it possible to put geokrets into those caches, but if yes, could you please add mapping for those codes to geocaching.su website?
> 
> See example of the new cache http://www.geocaching.su/?pn=101&cid=10987 (and actually it already has some geokret inside, but it was added before type change https://geokrety.org/konkret.php?id=56189)
> 
> Thanks in advance!

**Comment by kumy** [comment]
@okainov, in the database I can count 48 caches with waypoint name starting with 'LT' and 17 starting with 'LV'.

Do you think we are complete? Should we think about a full re-import?

**Comment by okainov** [comment]
@kumy we have around 430 caches with new type in total (mostly it was type change for some of old caches). If it's easy\doesn't require much resources from your side, it would be nice to re-parse everything (we have 21900 caches in total).  In other case I can just make  temporary output of all those caches to geokrety rss so it will be synced once and then revert it back

**Comment by okainov** [comment]
>18129

It could be fine, because we have some "deleted", "archived" caches which probably don't go into public views. Just checked - 18426 are "active", which looks good enough in comparison with your number. 

>Do you have a documentation about the /rss/geokrety/api.php endpoint?

I have access to the sources and can provide you some info. Do you need something specific or just general kind of "documentation"?

**Comment by kumy** [comment]
Let's close. feel free to reopen if needed.

**Comment by okainov** [comment]
Apparently this was not fully done, API part was missing :(

**Comment by kumy** [comment]
Note: we also need to manually patch new classes for GKv2. I'll do...

**Comment by kumy** [comment]
Also fixed in new them branch. closing
