### ISSUE TITLE
Improve and clarify the GCxxxx waypoint support

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#148]
Following discussion on social network and on Geokrety [International support  forum](https://groups.google.com/forum/#!topic/geokrety/YyjbIeBVOmQ)

When you log a geokrety (on geokrety website), in "New location", you can search waypoint.

**what's wrong**
- open  https://rec.geokrety.org/ruchy.php
- click on **'I have dipped a GeoKret'**
- about **New location section** to fill:

A GCxxxx waypoint is found if and only if there is an historic entry in the geokrety ruchy database (to confirm) : this point is really confusing for geokrety users.
In addition there is a label **"work only with opencaching network"** 
For an user that search an (unknown from ruchy) GC code, he get "no cache found" as result and he think that GC code is not supported by geokrety.

**Suggested improvment**
- [ ] update label when GC code is not found from "No cache found" >to> "no GC cache found in geokrety database, you will have to fill coordinates" : this point could be #133 duplicate
- [ ] update https://geokrety.org/help.php#fullysupportedwaypoints help page to improve that point.

   only some GC code coordinates are known from geokrety database
   geokrety service is keeping an history of all geokrety logs and is able to learn GC coordinates over the time
   if your GC cache is not found, please feel the cache coordinates, and you (or other player) will be able to retrieve this GC code next time

**Comment by kumy** [comment]
The field now clearly state it.

![Screenshot from 2019-08-31 22-15-14](https://user-images.githubusercontent.com/176794/64068761-e4308580-cc3c-11e9-8e89-e7316d80ecc5.png)

Closing. Reopen if disagree.
