### ISSUE TITLE
(autodeploy rec) register a geokrety doesn't work well

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#149]
Hi, just found maybe a missing check in autodeploy of a given branch.

**Steps**
- connected on rec.geokrety.org (as BSLLM)
- create a new geokret wth name and description

**Expect**
- geokret created, no error and redirected to just created geokret page

**Result**
- got this as result (cf. screenshot under)
- but geokret is created (because geokret is listed in 'my geokret' view)

![image](https://user-images.githubusercontent.com/3100576/45816130-0c98cb80-bcdb-11e8-9c17-06f729b8b6c6.png)

**Note about fix**
- [ ] try to find/add an automated way to check/verify file permissions

**Comment by kumy** [comment]
I have fixed directories and files ownership for the rec copy, write is now possible. However, all images are served from the cdn, which is not the same share between rec and prod :/ so no "new" pictures will be displayed on rec

**Comment by boly38** [comment]
yep now do not reproduce
thanks :)
