### ISSUE TITLE
Letter "S" doesn't resize properly in help headers

### ISSUE THREAD

**Issue by mvolfik** [geokrety/geokrety-website#159]
Just look at the pictures... Firefox 62 @ Ubuntu 18.04.
https://geokrety.org/help.php#https
![screenshot from 2018-09-24 20-27-21](https://user-images.githubusercontent.com/31281386/45971833-561a4b00-c03a-11e8-8da5-4d15854a72b9.png)
![screenshot from 2018-09-24 20-40-31](https://user-images.githubusercontent.com/31281386/45971836-587ca500-c03a-11e8-9423-de4f10d0597b.png)
My experiments say that:
- ~~It only happens with the regular version of the font (bold and light seem OK)~~ *not really*
- Only happens (is visible) for some font-sizes e.g. 13pt, 14pt (15pt looks OK)

**Comment by kumy** [comment]
Confirmed here, same OS and FF version.

We historically use `font-family: 'Oxygen', Verdana, Geneva, Arial, Helvetica, sans-serif;`, In the meantime, bootstrap was installed, I think we can go to the default bootstrap font and size.

**Comment by kumy** [comment]
Updated css deployed. It's now better. @mvolfik How do you feel the change?
[It would be nice to have a complete design of the  UI :)]

**Comment by kumy** [comment]
Looks good to me. Closing.
