### ISSUE TITLE
Keyless access to Google Maps Platform is deprecated.

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#162]
# Steps to reproduce
* Go to page: https://geokrety.org/user_stat.php?userid=26422
* Open browser developer console (ctrl+shift+K on FF)

# Actual result
An error is displayed many times

`Geocoding Service: Keyless access to Google Maps Platform is deprecated. Please use an API key with all your API calls to avoid service interruption. For further details please refer to http://g.co/dev/maps-no-account  For more information on authentication and Google Maps JavaScript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key`

# Expected result
No error should be displayed

**Comment by boly38** [comment]
related to #87

**Comment by kumy** [comment]
Migrated on `new-them` branch
