### ISSUE TITLE
html entities in users' statpic

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#181]
From support mail:
For users having special characters in their username, the generated statpics include the htmlentities representation of the character. Those html entitites should be converted to the original character on image generation.

Original message:
> Bonjour, j'ai trouvé vos coordonnées dans les contacts de geokrety.org.
Je me demandais s'il est possible de voir les caractères accentués dans
les bannières de statistiques comme par exemple pour "Lomobéré":
https://cdn.geokrety.org/images/statpics/34645.png
merci beaucoup

**Comment by boly38** [comment]
Do we need a script to enforce image re-creation?

https://rec.geokrety.org/mypage.php?userid=34645
(seems not fixed or same image?)

**Comment by kumy** [comment]
AFAIK, there is no script to regenerate all statpics. They'll be updated on next user statistics update. :disappointed:

**Comment by kumy** [comment]
> Do we need a script to enforce image re-creation?

It would be nice to have one ;)

**Comment by boly38** [comment]
I've no time to do that right now, but if you think it's important, let's create an issue for that point :)

>They'll be updated on next user statistics update.
seems to reduce the criticity of the feature: just need to check that it's working :)

**Comment by kumy** [comment]
We could probably postpone this point to the time where we have the new API up.

**Comment by boly38** [comment]
Oo ;)
https://geokrety.org/mypage.php?userid=34645
