### ISSUE TITLE
ruchy > howto manage wrong waypoint submission

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#186]
**step to reproduce**

Let's do the following steps **2 times** (that was done on "rec" for [iiii](https://rec.geokrety.org/konkret.php?id=68558)):
- go to ruchy page, 
- fill "I've dipped a geokret" + tracking code
- fill as waypoint ("GC_DELIRAN") , 
- fill coordinates, 
    - first time fill with `45 15.8892 5 53.661`, 
    - second time `45 15.8892 5 53.699`
- submit the form,

**current result**
- after the first time steps GC_DELIRAN is written in database with  `45 15.8892 5 53.661` as coordinates. First ruchy log uses this cordinates
- after the second time steps GC_DELIRAN keep the following coordinates `45 15.8892 5 53.661` in DB. Both ruchy logs have same coordinates

**expected result**
- to define

**question to solve**
- determine if the current result is acceptable, or must change to "override" coordinates (second time submission) ?
- in current state: how to revert/update a wrong coordinate input for a given waypoint code ? (seems we have to contact support)
- should we accept that a ruchy log override exising waypoint coordinate ? (for waypoint that are not in waypoint table)
- how a end-user can report/fix an error in waypoint ? must we add a feature for that ?
   - (if any) how to moderate error report ?

**Comment by kumy** [comment]
Really good question. I had to deal with such case in the past and it bothered me. The coordinates of the cache were several km South and were in the sea.

There can be some reasons to not fill the same coordinates:
* the coordinates are completely wrong many km away - bad typo
* the original coordinates were updated by the cache owner
* Some "spam"

In an ideal world there should be a way to report wrong coordinates with just a few click to the admin. On the admin side, we could have a dashboard with some quick links to the caches, and decision actions buttons. This seems -to me- a lot of time to invest in the current version of the code. It's a must have feature for the next website. We should record it clearly to not forget. maybe in such format as https://github.com/geokrety/geokrety-api/wiki/%22Parked%22-feature ?

A simple way to have an intermediate solution could be:

**expected result**
The first coordinates won't be touched, the second record should contains the new coordinates. On next moves, we can propose the most newer version of the coordinates.

**Comment by kumy** [comment]
In `new-theme` branch, coordinates may be overridden.

If this is a `GC` cache, then the database is updated (OC, and other are imported via scripts)
The next move on that waypoint, form will load what's in database.

![Screenshot from 2019-08-31 22-08-55](https://user-images.githubusercontent.com/176794/64068720-31602780-cc3c-11e9-9753-c37134c5e61c.png)
