### ISSUE TITLE
ErrorException - templates/konfig.php in handleError

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#212]
https://sentry.kumy.org/geokrety/geokrety-legacy/issues/656

ErrorException
mysqli_connect(): (HY000/2002): Nie mo?na przypisa? ??danego adresu
templates/konfig.php in handleError at line 235

**Comment by boly38** [comment]
little question for @kumy : could you point me the script/endpoint used for mailing list (daily digest) ?

- Is that `poprawki.php` ?
- Does exist some related file in `geokrety-scripts` side ? `geokrety-scripts/mailoza.php` ?

**Comment by kumy** [comment]
Sorry I don't know exactly which script is responsible for this, but for sure it listed in this file ;) https://github.com/geokrety/geokrety-scripts/blob/master/geokrety-crontab

**Comment by kumy** [comment]
Based on cron date time it must be this one ;)
https://github.com/geokrety/geokrety-scripts/blob/master/obserwacje2.php

**Comment by boly38** [comment]
thanks 😀 so additional files based onto website ones 😅
