### ISSUE TITLE
ruchy.php waypoint by gc code

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#217]
Step to reproduce (not easy):

- play lots of time with "Waypoint" field and fill correct GCCode
- remove last letter and readd it quickly

Issue:
- in some case, we got "missing" result

IMHO some javascript race condition makes QA failure for this usecase (and blur event doesn't fix that)

**Comment by kumy** [comment]
LInk to #344

**Comment by kumy** [comment]
Let's close, `new-theme` is a bit different
