### ISSUE TITLE
2 red error icons shown

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#23]
From #18

On the ruchy.php page:

"2. Objet voyageur" issue : 2 red error icons (1 expected?)

**Comment by kumy** [comment]
@boly38 I'm not able to reproduce, do you have a step by step procedure, a screenshot?

**Comment by kumy** [comment]
Ok, I can reproduce. The second icon comes from the username validation.

**Comment by boly38** [comment]
Ok well seems that fix already pushed on rec.geokrety.org because I'm unable to reproduce. Well done.
