### ISSUE TITLE
Broken javascript on one GK page

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#254]
The GeoKret GK6690 has it's page broken, from what I saw it is caused by the map Javascript.
The move located in Japan at coordinates `35.70210 139.77835` breaks all when used with other waypoints. The highest value I could have get for the longitude was `91`.

@boly38 Should we try to migrate to other library like leafletJS (#87) or upgrade to Google Map API v3 ? Would you like to work on this bug?

See: https://staging.geokrety.org/konkret.php?id=26256#

The loaded map file:
https://gist.github.com/kumy/2da4fb6c8b0e619e355d4e752a9b1c72

**Comment by boly38** [comment]
I saw your comment, can't right now, but keep this issue in mind :)

**Comment by boly38** [comment]
reproduced with @kumy input on **bugfix/map** (cf. `___bugMap.php`). next step is to try leafletjs as google map replacement (I think we could try to move away from google).

**Comment by kumy** [comment]
+1 for leaflet + osm

**Comment by boly38** [comment]
I found leaflet really easy to use, cf similar path with leaflet + OSM : [___leafletjs.php](https://boly38.staging.geokrety.org/___leafletjs.php)

**Comment by boly38** [comment]
do we have a cron that clean `mapki/*` directories? I were unable to find it in gkscripts

**Comment by boly38** [comment]
WIP Notes:
- jquery-3.3.1.min.js isadded in `krety.html` // move it to head

**Comment by kumy** [comment]
@boly38  I don't think this directory `mapki` is ever cleaned

**Comment by kumy** [comment]
@boly38 `master` branch deployed on staging, and database synchronized with prod.

**Comment by boly38** [comment]
Japan is in the place 🇯🇵⛩️🍜🍢🍣🍱
👏
