### ISSUE TITLE
GreaseMonkey not compatible with GKT?

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#263]
From one user in GeoKrety group, it seems that GreaseMonkey doesn't play well with GKT. When the user moved to TamperMokey, all went well.

As our page suggest to use GM, with not change suggestion to TM?

Also, we should test and fix error if we can.

Ref page: https://geokrety.org/toolbox.php

**Comment by boly38** [comment]
I had also poke simor (author nickname in source) by sending him a private message with a link to the discussion. No answer for now. And seems last toolbox version is so old..

 Would be great to move this source as geokrety github repository :)

**Comment by kumy** [comment]
There is already an ongoing conversation with @sirsimor there https://github.com/geokrety/GeoKrety-Toolbox/issues/1 about merging code. No luck yet :(

**Comment by kumy** [comment]
GKT v0.3.5 in greaseMonkey has this error in developer console:
```
Script error:  TypeError: "Document.evaluate requires at least 2 arguments, but only 1 were passed"
    init user-script:http://simor.net/greasemonkey//GeoKrety Toolbox:742
    userScript user-script:http://simor.net/greasemonkey//GeoKrety Toolbox:792
    scopeWrapper user-script:http://simor.net/greasemonkey//GeoKrety Toolbox:813
    <anonymous> user-script:http://simor.net/greasemonkey//GeoKrety Toolbox:494
```
