### ISSUE TITLE
GK not seen in OC cache

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#267]
From mail:

I dropped a GK to my NC "Galgenhumor":
https://www.geokrety.org/konkret.php?id=62504

But it´s not listed in the inventory of the cache:
https://www.opencaching.de/viewcache.php?wp=OC8EEA

Is this a problem of opencaching.de or of geoKrety.org?

PS.
I only see a GK called "Maria (Pik-D)" (which is not really there).

**Comment by kumy** [comment]
@teiling88 may you please explain us how is oc.de synchronized with geokrety.org? Is is actually broken?

**Comment by kumy** [comment]
ping @teiling88

**Comment by teiling88** [comment]
Oh sorry I missed the first mentioned. Sorry for that. I will have a look in the evening.

**Comment by kumy** [comment]
@teiling88 just a friendly reminder

**Comment by teiling88** [comment]
Hey @kumy,
at the moment I have no idea what the issue is. I will have a deeper look into this issue after my wedding in the end of mai.

**Comment by kumy** [comment]
Closing right now, feel free to reopen if problem occurs again.

**Comment by kumy** [comment]
Issue still seems to occur https://github.com/cgeo/cgeo/issues/11660
