### ISSUE TITLE
Legend missing on new map

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#271]
We used to have the legend of the pins color such as

![Screenshot from 2019-04-03 20-52-08](https://user-images.githubusercontent.com/176794/55505044-7dd61580-5652-11e9-8ad7-6d1e23310fc1.png)

I don't see them on new map implementation.

**Comment by boly38** [comment]
seems on the same page there is a theme issue with altitude container too

![IMG_20190403_215457](https://user-images.githubusercontent.com/3100576/55509071-91d24500-565b-11e9-974b-f4b9c8a62b32.png)

**Comment by kumy** [comment]
Hum works fine here:
Firefox Quantum 66.0.2

![Screenshot from 2019-04-03 22-01-42](https://user-images.githubusercontent.com/176794/55509400-3a80a480-565c-11e9-8403-427ac273ad70.png)
https://github.com/geokrety/geokrety-website/issues/271

**Comment by boly38** [comment]
Dev notice: 
- altitude jpgraph image is generated by (geokrety-scripts / wysokosc )

**Comment by boly38** [comment]
out of altitude

https://boly38.staging.geokrety.org/konkret.php?id=65876 is up to date with fresh version
- map legend 
- map download csv and gpx on the same line, right align
![image](https://user-images.githubusercontent.com/3100576/55552935-1ade9000-56df-11e9-8e64-b9a718bdf465.png)

- added section label (not sure it's better thant previously?)

![image](https://user-images.githubusercontent.com/3100576/55552949-2762e880-56df-11e9-8872-108765c80aa1.png)

what do you think kumy ? :astonished:

**Comment by kumy** [comment]
Looks really well! Will update cdn right now

**Comment by kumy** [comment]
cdn updated https://cdn.geokrety.org/libraries/leaflet/
