### ISSUE TITLE
Move leafletjs library to our cdn

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#272]
Would be nice if we import leaflet to [our cdn](https://github.com/geokrety/GeoKrety-Static), to prevent loading js from multiple sources. This will help users having blockers like uMatrix to display our website without trouble.

Note: There is not automatic deploy for this repo.

**Comment by kumy** [comment]
There is also this import https://cdnjs.cloudflare.com/ajax/libs/jquery.colorbox/1.6.4/jquery.colorbox-min.js?ver=1.1 from at least `konkret.php` page

**Comment by boly38** [comment]
- [ ] remove css section from `konkret.php`by using `wsnowrap` instead of `konkretlabel`

**Comment by boly38** [comment]
If I understood well, our Geokrety CDN doesn't provide the following header:

````
access-control-allow-origin: *
````
so as result, while trying to test locally, my browser is rejecting me to query this cdn resource :+1: 

![image](https://user-images.githubusercontent.com/3100576/55624227-91de5c00-57a5-11e9-9e0a-4fd4d1f63c63.png)

do you have the hand @kumy to add this header for geokety CDN ?

**Comment by kumy** [comment]
@boly38 I think it's already present

https://github.com/geokrety/GeoKrety-Static/blob/8993a7e92277be4ae13573a7fca8f77e83ad51aa/default.conf#L47

**Comment by boly38** [comment]
seems that rule doesn't apply well (because of "subdirectory" dont match ?)

test using curl:
```` 
curl -svo. https://unpkg.com/leaflet@1.4.0/dist/leaflet.js 2>&1 | grep -i origin
< access-control-allow-origin: *
curl -svo. https://cdn.geokrety.org/libraries/jquery/jquery-3.3.1.min.js 2>&1 | grep -i origin
(nothing!)
````

**Comment by kumy** [comment]
My bad, I didn't saw `js` files where not in this list ;)

**Comment by kumy** [comment]
Here we are :0
```
$ curl -svo. https://cdn.geokrety.org/libraries/jquery/jquery-3.3.1.min.js 2>&1 | grep -i origin
< Access-Control-Allow-Origin: *
```
