### ISSUE TITLE
no trip on map for some geokrety

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#278]
Following geokrety have a map issue : no icon on the map, why ?

- https://geokrety.org/konkret.php?id=60972&nocache
-- trip rest query result is 200 but with no body

TODO
- [x] talk about map (potential bad behavior / onto website, twitter, fb)
- [x] check csv and gpx results - seems ok
- [x] try to reproduce locally using 60972 as example - based on chars - failed to reproduce
- [x] try to reproduce locally using 60972 as example - based on ruchy data - *ok reproduced* (special thanks to @kumy for tools)

--

*reproduced with real data*
- trip rest `json_encode` where resulting `FALSE` with `JSON_ERROR_UTF8` as last json error.
- fix : add safe_json_encoder

**Comment by kumy** [comment]
I have searched a bit, the json encoding is failing with an error 5 (JSON_ERROR_UTF8)
The `AbstractResponse.php` `write_json()` method should check is the json_encode() return value is false (`=== FALSE`), and use `json_last_error()` to obtain the error code.

**Comment by boly38** [comment]
need to wait commit `09..` onto https://boly38.staging.geokrety.org/konkret.php?id=60972&nocache
