### ISSUE TITLE
ws.geonames.org doesn't work anymore

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#284]
https://sentry.kumy.org/geokrety/geokrety-legacy/issues/441/

```
ErrorException: fopen(http://ws.geonames.org/countryCode?lat=56.94063&lng=3.19452&radius=30): failed to open stream: php_network_getaddresses: getaddrinfo failed: No address associated with hostname
  File "geonames-waypointy.php", line 74, in handleError
    $handle = fopen("http://ws.geonames.org/countryCode?lat=$lat&lng=$lon&radius=30", "rb");
  File "/var/www/html/templates/sentry-php-master/lib/Raven/ErrorHandler.php", line 0, in fopen
    Raven_ErrorHandler->handleError
  File "geonames-waypointy.php", line 74
    $handle = fopen("http://ws.geonames.org/countryCode?lat=$lat&lng=$lon&radius=30", "rb");
```

**Comment by boly38** [comment]
According to [webservice documentation](http://www.geonames.org/export/web-services.html) :
- new enpoint address is in the form of `http://api.geonames.org/countryCode?lat=56.94063&lng=3.19452&radius=30`
- and *new requirement*, we need a `username` as query parameter, else we got the following error:
````
ERR:10:Please add a username to each call in order for geonames to be able to identify the calling application and count the credits usage.
````

@kumy do you already have a geokrety account? else we need to create one ([register](http://www.geonames.org/login))

**Comment by kumy** [comment]
I don't have one, please go to the registration process and share password securely :)

**Comment by boly38** [comment]
I've created an account, will share it soon. Need to pay attention to [daily limit](http://www.geonames.org/export/):
````
20'000 credits daily limit per application (identified by the parameter 'username'), 
the hourly limit is 1000 credits. 
A credit is a web service request hit for most services.
 An exception is thrown when the limit is exceeded.
````
