### ISSUE TITLE
Improve picture upload

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#292]
* Raise the image size (W / H) limits
* Raise the image weight

**Comment by boly38** [comment]
I think this is an excellent point for many of our users.
If possible, add the way to resize the image (new page/feature) in case of limit reached.

**Comment by kumy** [comment]
Would be nice if pictures could be added using drag and drop… Could be sum up as "A better UI" ;)

**Comment by kumy** [comment]
link to #4

**Comment by kumy** [comment]
I'm starting working on this page on the `new-theme` branch, and seen that an easy first step would be to increase values here:
https://github.com/geokrety/geokrety-website/blob/064175a13e981f25a699a874810628fe5737c370/website/imgup.php#L11-L13

**Comment by kumy** [comment]
Here we are, a first step in picture management has been provided in `new-theme`. File size is limited by php `max_uploaded_filesize` (8M in my environment), width/height set to high value: 6000px.

* Once uploaded, the picture is downscaled to max 1280 px width or Height.
* Picture preview before upload.

No drag and drop to add picture.

![Screenshot from 2019-05-18 00-16-55](https://user-images.githubusercontent.com/176794/57959053-4b326480-7902-11e9-9b58-68877ba0083a.png)

**Comment by kumy** [comment]
It's in `new-theme` branch. Let's close to clean our backlog

**Comment by kumy** [comment]
reopen for reworking.

**Comment by kumy** [comment]
Done in `new-theme` branch. (Not yet deployed)
