### ISSUE TITLE
New "logging form" - bugs

### ISSUE THREAD

**Issue by brasiaPL** [geokrety/geokrety-website#30]
In Google English ;)
Big buttons are probably a nod to phones, it does not look very nice on the computer.
1. Unfortunately, the login of moles by the cache name does not work on the new site. Ie. searches the box but the OP number is not completed :(
2. if I am not logged in appears (less visible than before, it should remain red) message in English "Although it is possible ...."
3. in general many messages (previously in Polish) are now in English
4. "Date of operation": on the right there is a kind of button that seems to open the calendar, it does not happen.
5. "GeoKreta Identification" - there used to be a name, now only TC
Probably it was supposed to be good and functionally worse than it was :(

In Polish:
Duże przyciski chyba są ukłonem w stronę telefonów, na komputerze nie wygląda to zbyt ładnie.
1. Niestety na nowej stronie nie działa logowanie kretów według nazwy kesza. Tzn. wyszukuje skrzynkę ale nie uzupełnia się numer OP :(
2. jeśli jestem niezalogowany pojawia się (mniej widoczny niż poprzednio, powinien pozostać czerwony) komunikat w j.angielskim "Although it is possible...."
3. w ogóle wiele komunikatów (wcześniej po polsku) teraz jest w angielskim
4. "Data operacji": po prawej jest taki jakby przycisk, który wydaje się powinien otwierać kalendarz, tak się nie dzieje.
5. "Identyfikacja GeoKreta" - kiedyś była nazwa, teraz tylko TC
Pewnie miało być dobrze a wyszło funkcjonalnie gorzej niż było :(

**Comment by brasiaPL** [comment]
And alert: 
Although it is possible to perform GeoKrety operations without logging in, we encourage you to create an account and log in. It will take you about 15 seconds :). -> Chociaż możliwe jest wykonywanie operacji na GeoKretach bez logowania, zachęcamy do utworzenia konta i zalogowania się. Zajmie to około 15 sekund :).

**Comment by kumy** [comment]
1. Fixed
2. Changed
3. Translations added
4. Fixed
5. Fixed

**Comment by kumy** [comment]
> crowdin it's too complicated for me ;)

@brasiaPL I've enabled crowdin inline translation. You need to use the new link on the left menu called "Fix translation". To exit the translation mode, just switch to another language using the selector. I hope it'll be easier :)

**Comment by brasiaPL** [comment]
@kumy Good job! :)
I have improved a bit... but how to get back to normal operation in GeoKrety.org?

**Comment by kumy** [comment]
I said it

> To exit the translation mode, just switch to another language using the selector

**Comment by harrieklomp** [comment]
Clicking on your own Country flag does also exit the translations.

**Comment by kumy** [comment]
There is now a button to exit the translation mode (and return to english) in the upper-right corner

**Comment by kumy** [comment]
I think we got them all. Let's close.
