### ISSUE TITLE
GeoKret comment length limited without warning

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#31]
![image](https://user-images.githubusercontent.com/3100576/38427814-8855c29a-39ba-11e8-8d71-c06b81bfa047.png)

https://geokrety.org/konkret.php?id=65085#log1330856

Hi,
I was trying to add a looooong comment on a given GeoKret. see example  above.
I finish my input and push submit button.
As result I got a cutted message.

Would be very nice to prevent this kind of data loss: prevent submit action and inform the end-user that he should review his input.

(I could try to fix that asap )

**Comment by kumy** [comment]
@boly38 I hope you'll like it :)

![screenshot from 2018-04-07 01-39-59](https://user-images.githubusercontent.com/176794/38448532-108a6e32-3a05-11e8-9ca4-6d18d9ebc78e.png)

**Comment by boly38** [comment]
oO You're right, over 500, the next input just move pointer on the next character without adding new one. My fault.
good job!
