### ISSUE TITLE
no "geokrety in my hand" while trying create a new log with c:geo

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#323]
[On FB](https://www.facebook.com/groups/1624761011150615/permalink/2083672151926163/), Claire told me that there is no more GeoKrety entries while trying to add a new log with android c:geo application.

I'm able to reproduce.

Need to know if c:geo is responsible or geokrety api ?

**Comment by kumy** [comment]
hum, let me reproduce here to define where the problem is.

**Comment by kumy** [comment]
Problem is from us, and that's certainly my fault #318

**Comment by kumy** [comment]
Fix should be deployed in a few seconds ;)

@boly38 may you ask the user to test again please

**Comment by kumy** [comment]
Notify @Lineflyer: FYI yesterday, we introduced a regression in our API preventing users form retrieving their GK inventory. Problem should now be fixed, but at least you have the info in case of support mail on your -c:geo- side. Sorry for that.

**Comment by boly38** [comment]
Hey, seems fixed for geokrety in new log UI
But Claire told me about an issue with cache inventory (I did'nt reproduce)
> je trouve bien dans l'inventaire des caches concernées les Geokrety déposés il y a 34 jours mais pas les suivants (25 jours et plus recemment)

**Comment by Lineflyer** [comment]
I have indeed noticed that as I wanted to log an OC.de cache yesterday and my inventory was missing. Thanks for information and I can confirm its working normal right now.

**Comment by kumy** [comment]
> But Claire told me about an other issue with geocache inventory (I didn't reproduce)

I don't understand the problem, sorry. A dedicated issue will be nice, but I'm sure you'll done it anyway ;)

**Comment by boly38** [comment]
I created#325
