### ISSUE TITLE
Ping GKM on new Geokrety event

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#324]
As noticed by @bekuno in cgeo [issue](https://github.com/cgeo/cgeo/issues/7610), new GeoKrety - more generally a GeoKret that has never traveled yet - are not present in GKM database.

It would be nice if GK could`ping` GKM on new GeoKrety event using url `https://api.geokretymap.org/gk<id>/dirty`. This endpoint should trigger a force update for the concerned gkid.

Regarding implementation, in an ideal world, this call should be a non blocking IO.

We could consider this as webhook, so many websites could request to be notified on -general- events (new GK, new move, etc…). in such case, it would be nice to have a dedicated microservice for that (written in any language - go? python?). I've introduced a redis server in the branche new-theme, could we use this server as a queue system (what about rabbit - I used it in [geokrety-api](https://github.com/geokrety/geokrety-api/blob/c39d28c53a6e2b79394683f6393bc04d02180998/docker-compose.yml#L70))?

However, as I'm currently splitting html from php in all the website #4, it would be nice to wait a bit to avoid infinite time fixing merging conflicts.

**Comment by kumy** [comment]
We should add a quick workaround (sync IO :unamused:) on [Register GeoKret](https://geokrety.org/register.php) page so it'll fix https://github.com/cgeo/cgeo/issues/7610 and consider another implementation later (new microservice :wink:).

**Comment by kumy** [comment]
We have a workaround..

**Comment by kumy** [comment]
Deployed to prod, and full resync started

**Comment by boly38** [comment]
@kumy did your workaround works when we log using c:geo api?

**Comment by kumy** [comment]
I hope!

**Comment by kumy** [comment]
Ho, this fix is for gk just created that never moved. It can t be achieved using c:geo. General logs (api or not) enter the normal flow of synchronizing (ie: poll export2.php regularly)

**Comment by boly38** [comment]
I leave a geokrety in a cache today and don't see it in the inventory https://coord.info/GC72NJ3
https://geokrety.org/konkret.php?id=69504
I even try gkm dirty api with no effect

**Comment by boly38** [comment]
ok it's in inventory right now 👍 thanks

**Comment by kumy** [comment]
Strange, there should be around 1min delay max :(

BTW, user's inventory in c:geo use our standard GK endpoint https://geokrety.org/export2.php?secid=....&inventory=1 not GKM, but cache listing in c;geo may use GKM (in next release, it'll only use GKM https://github.com/cgeo/cgeo/pull/7641)

**Comment by kumy** [comment]
Events could now be easily added on `new-theme`, it's there https://github.com/geokrety/geokrety-website/blob/feature/new-theme/website/app/events.php

**Comment by kumy** [comment]
Can be easily implemented in new theme thanks to the raised events.

**Comment by kumy** [comment]
Implemented in new-theme with rabbitmq
