### ISSUE TITLE
miss some geokrety in c:geo geocache inventory

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#325]
miss some geokrety in geocache inventory

![57586505-0fa92c00-74f7-11e9-932e-dfbbed288a16](https://user-images.githubusercontent.com/3100576/57587794-6587cf00-750b-11e9-9efd-869825d53e06.png)

for example in GC18KRB geocache c: geo inventory tab, we expect to have GK11E18 but there is only one TB

**Comment by kumy** [comment]
Ok, I see, GKM has a problem since ~January https://api.geokretymap.org/graphs/

I have to migrate GK on new server, I'll check at the same time

**Comment by kumy** [comment]
* Server timezone changed, so downloading the same GK on every loop
* gpx file were now compressed, but not supported by `basex`
* Full resync is running

**Comment by kumy** [comment]
GKM service didn't supported the massive update. Service is down until this evening

**Comment by kumy** [comment]
Service crashed while synchronizing, I've restarted the service, sync is ongoing.

**Comment by boly38** [comment]
what about last sync ?
I just checked GC18KRB: no geokrety :(

**Comment by kumy** [comment]
I've launched another throttled full sync this morning, it's now ended. I hope it'll be fine now.

BTW I was wondering if @boly38 would implement a cron script for checking sync. It seems to be a huge process and how to check if data are synced?

**Comment by boly38** [comment]
GC18KRB embeed a geokrety 👍 

I could maybe help : need some input about the context (create another dedicated issue?)

**Comment by boly38** [comment]
Hi @kumy , on FB an user told me a c:geo missing geokrety GK12BAD, could you please check?

**Comment by kumy** [comment]
I don't see what the problem is. Looking in c:geo for this GK show the same logs as on the GK website. I suspect he posted the wrong coordinates. In which cache code it is supposed to be?

**Comment by boly38** [comment]
Sorry my bad, I were too quick, seems he had only posted coordinates. I replied to him, so nothing related to sync.close.
