### ISSUE TITLE
Check concistency between GK and GKM

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#328]
It would be nice to have a script that could be launched one a week that will check if all GeoKrety in the GKM database are in sync.

**1. how to access the data on both side**
We can read our local db and retrieve GKM using public [REST API](https://github.com/GeoKretyMap/gkm/wiki/Api-endpoints)

**2. what is our definition of "sync"**
Difficult to define, but at least basic information, name, owner, cache count, current position, distance. But what about moves?

**3. how and when to check**
Via cron script, probably every week

**4. how to report**
prometheus ;) ?

** benefits **
* it help c:geo users to read update values
* we may use fast geoson responses in our GK minimaps
* ?

**Comment by kumy** [comment]
link #325.

@boly38 are you in?

**Comment by boly38** [comment]
someone told that there's no stupid question 😋 so: I would like to know why geokrety backend should be 'responsible' of third party synchronization?

 I don't know about GKM implementation but maybe it's more easy to provide additional geokrety api that provide to a given consumer a set of x geokrety informations to update. (GKM should support cpu to check consistency and not geokrety)

on geokrety side we could store new 'consumer' concept : a new table with following column : geokrety id, consumer id, last sync timestamp

on geokrety change, all rows with related geokrety id must be deleted.

this to avoid queue or consistency job on geokrety side: but consumers like gkm should have to create/improve a sync job:

as 'gkm' consumer, give me x geokrety informations that I don't sync.

what do you think?

**Comment by kumy** [comment]
What i didn't explicitly said, is that in a long term I would like to unify GK and GKM. We - on GK side - can benefit of the xml backend database which is really fast to select and return data based on GeoKrety position. ie we could use the GKM api in pages where we display maps. So we need to ensure integrity in the _slave_ database.

Regarding implementation, why in this way (GK actively checks GKM)? Because for example GKM has no way to find a GK that has never moved (data not present in `export*.php`).

We could also get ride of GKM completely but I'm not confident with the mysql performance in such requests.

Note: isn;t your idea about consumer concept  related to https://github.com/geokrety/geokrety-website/issues/324 ?

I thought about another argument yesterday, but unfortunately I forget it :-1: 

And regarding _cpu sonsuption_ GK and GKM are hosted on the same server :p

**Comment by boly38** [comment]
Ok Thanks

>Note: isn;t your idea about consumer concept related to #324 ?

Yep, basic feeling is that if we (geokrety.org "actor") need to be responsible of  GKM _slave_ database, then we need to store in a way sync informations. 

I doubt about the fact : "sync all in one job, once a week". 

I will continue on wip branch trying to implement such concept. 

For example/ If we store the "(per a given consumer) last sync timestamp", then the sync job could batch N (oldest and/or youngest) entries to sync at regular interval.  It should spread the workload by design..

**Comment by kumy** [comment]
> "(per a given consumer) last sync timestamp", then the sync job could batch N (oldest and/or youngest) entries to sync at regular interval.

This is quite the behavior all of `clients` do (OC platforms, GKM). ie poll the `export*.php` endpoints asking what changed since `date`. Each `client` is responsible for retaining the last success date. (for example GKM store this date in an XML attribute from the `pending` queue)

What is #324 about is the other way to synchronize. GKM will not pull regularly GK to check if something changed, but GK notify GKM saying "hey, this GK changed, you should start synchronizing it".

This issue #328 is about checking if data in GKM is the expected one. Taking in input the whole database or chunks then retrieving GKM content and compare to GK database. Tricky part would be how to notify admin about a continuous error on a GK that won't synchronize?

**Comment by boly38** [comment]
I tried to define the way to go on a wiki page:
https://github.com/geokrety/geokrety-website/wiki/Study-GKMConsistencyDesign

Feel free to comment.

**Comment by kumy** [comment]
:clap: I'll read in a moment…

**Comment by kumy** [comment]
Looks promising. At first I thought, "ouch, that's complicated!" but as reading continue, things goes clearer. Here are my thoughts:

**overview of what's going on**
It's nice to have an admin page (while reading I thought having a dashboard to monitor all those values and how the sync process goes would be a must have, and you already thought about it :+1:). 

**dedicated repo**
All this machinery could represent an entity as itself, a brick of service, a microservice, it has it's own life ;) Would be nice to avoid mixing this with the website code. It's like a subproject in GK world having it's own repository and life cycle. Sure it will need access to the GeoKrety database, but it's just a consumer of the geokrety actual database, it's not responsible for updating it. We could deploy it as a service in our geokrety docker stack. It can be written in any language, not necessarily php as the website.

**stateless**
On another end, the data storage. I'm not fan of storing data on a `temporary cache file on disk.`, it break the stateless paradigm of a microservice. The `syncstate` seems useful to not process the same data continuously, not restarting from the beginning as the batch time frame seems really short (`gkm_consistency_max_duration_sec`). This data is not production sensitive, if we loose it, that's not a problem, we start over from the beginning. Also, those seems to be really tiny data (not speaking of `rollId directory log`), those values could easily be stored in the redis database. It's fast and we already have an instance in the stack.

**directory log**
As for the other points, storing data on the file system does not fit well in microservice environment. If there is one instance of the service, it's easy, but what if we launch x instance of this project? data will spread over the servers and it'll be hard to have a global view. [For the GK website, it would be nice to migrate our pictures and generated files out of local filesystem, and migrate them to some object store (S3 compliant storage). We'll not use Amazon S3, but as we're self hosted, we'll deploy a minio instance for such feature.] So this new service could easily be shared with our problem here of log storage. So please don't write anything on local filesystem and push logs to minio.

**Comment by boly38** [comment]
Hi @kumy ,
following very first test on api 
- 10 call of API `/gk/{$gkid}` with different ids seems ok
- 30 calls of API `/gk/{$gkid}` with different ids sometime ok, sometime result in 503
- 50 call of API `/gk/{$gkid}` with different ids pretty often in 503 result

-  you an reproduce using `wip/gkmSync` branch and `___.php` page and change GkmConsistencyCheck::collectNextGeokretyToSync arg default value
- do we have rate limit on GKM API ? or bug (check service logs?) ?
- can we have a new GKM api : kind of **bulk get**, accepting an array of geokrety ids to get ?

**Comment by kumy** [comment]
You were certainly rate limited See conf here https://github.com/GeoKretyMap/gkm-api-nginx/blob/master/conf.d/api.geokretymap.org.conf#L107

We should add your ip(s) to https://github.com/GeoKretyMap/gkm-api-nginx/blob/master/no_req_limit.conf and also to `no cache file` https://github.com/GeoKretyMap/gkm-api-nginx/blob/master/no_cache.conf

> can we have a new GKM api : kind of bulk get, accepting an array of geokrety ids to get ?

Yes, everything is possible :) Would you try to implement it yourself? May you create an issue [here](https://github.com/GeoKretyMap/gkm-api-php)?

**Comment by kumy** [comment]
Hint, it happens here https://github.com/GeoKretyMap/gkm-api-php/blob/master/gkm/xquery/select-by-gkid.xq and https://github.com/GeoKretyMap/gkm-api-php/blob/master/gkm/export.php

**Comment by kumy** [comment]
@boly38 Multiple gk should now be supported thanks to https://github.com/GeoKretyMap/gkm-api-php/commit/1e9cac790601c22ccdbda47a4ec12231610100f1

**Comment by kumy** [comment]
Wiki updated https://github.com/GeoKretyMap/gkm/wiki/Api-endpoints (see at the bottom.)

**Comment by boly38** [comment]
with your fresh new `export2` GKM API a very first test of getting 50x10 geokrety from db then from gkm api tooks 4.56sec / if we consider 5 sec, then overall 70k geokrety would take less than 12min to be done. That not as hard as I was thinking.
(there is no "compare" step, not result push mecanism for this test context)

**Comment by kumy** [comment]
Should we increase -the arbitrary- limit to 50 GK at the same time?

**Comment by boly38** [comment]
Network exchanges consume lots of time. So if de increase the limit the we will have better performances I think too.

--
(not related)
--

the consistency job would result in detection of unsync items. we could put this unsync ids in a [Redis set](https://github.com/phpredis/phpredis/blob/develop/README.markdown#sets)
so we will create another job that will pop items from this set to send dirty calls to GKM. (Ideally would be great that GKM consumes directly Redis..)
And admin PointOfView could be a metric gauge of Redis set size. This gauge goes up due to consistency and down due to GKMdirtySender job. What do you think?

**Comment by kumy** [comment]
Nice idea to try to force a resync, but be careful, some errors are not (yet) recoverable. I remember something like ~50GK having parsing problem or some other weird thing the the current GKM-fetch script doesn't support. So, probably storing somewhere GKids having permanent error/unsync (but it will be hard to differentiate GK moving fast than errors)

Regarding the metrics, I think it would be preferable if `the sync tool` provides a `/metrics` endpoint listing all related statistics. It has to be responsible from computing the queue size and export them with to others values. It could in the background store all the `time-frame metrics` (time between two polls from prometheus) in the same redis instance.

**Comment by kumy** [comment]
I'll push the limit cursor to 200 after [the GKM migration](https://github.com/GeoKretyMap/gkm-api-php/issues/13) which will be done this weekend

**Comment by kumy** [comment]
As said in https://github.com/GeoKretyMap/gkm-api-php/issues/13

> @boly38 […] what about using full exports from https://api.geokrety.org/basex/export/ they are refreshed every 5 minutes ;)

**Comment by boly38** [comment]
To get it more fast, is it possible to have a gz version of `geokrety.xml`  (16Mo => 3Mo ) ?
BTW I will do some test about querying this xml file

**Comment by kumy** [comment]
Unfortunately it will be a bit harder :/

**Comment by boly38** [comment]
test1) seems loading huge file never end (not a good way at all)

test2) and using a reader to find a gk by id : very first test tooks 15sec to report a gk closeto the end of xml file :/

I thinl I will stay with bulk get api :)

**Comment by kumy** [comment]
ok, you should be able to get up to 200 `gk` per request. Should we whitelist your ip?

**Comment by kumy** [comment]
Just thinking about this for the spec of "a GK microservice":

**configuration**
A microservice must be configurable preferably using environment variables. This helps a lot for stateless deployment.

**Comment by boly38** [comment]
Hey @kumy , in order to deliver something not so far, I rewrite a little bit [Study-GKMConsistencyDesign ](https://github.com/geokrety/geokrety-website/wiki/Study-GKMConsistencyDesign) in a more simple way 
- based on geokretymap export
- integrate your remark on evn
- postpone of "centralized" solution for data/and/or/logs

**Comment by kumy** [comment]
> a cache of GKM data is produced and stored on redis

Really? I thought about using redis as only as a temporary storage for the metrics.

**Comment by boly38** [comment]
we will read gkm export in one shot (less than 20 sec) and use redis as a cache for each gkm entry (with time to live == ~1 hour for example)

this will improve perf for compare step: instead os searching gkm entry by id from api or from a file, we will use redis

**Comment by okainov** [comment]
>what about using full exports from https://api.geokrety.org/basex/export/ they are refreshed every 5 minutes ;)

Do you need a checkmark ? =)

[ ] update documentation to include new endpoints

Probably it can be used by one-time synchronizations (i.e. monthly/quaterly or so) just to make sure that nothing was missed, but for sure reading full data of 70k GKs is not the way to go for regular quick sync.

Also I quickly looked thru it it seems that `last_pos_id` and `last_log_id` are always the same - no need to repeat. Actually, I think both of them are not needed in this XML if it's intended for external services, since external services don't know what to do with GK internal IDs. And, of course `image` is completely useless is this XML =)

**Comment by kumy** [comment]
No, `last_pos_id` `last_log_id` are not useless, at least not useless for all partners, it's here to allow c:geo to mark GeoKrety as missing using the current code base. (But his feature is not yet implemented yet https://github.com/cgeo/cgeo/issues/4867), they are in most case equal each other, but not necessarily.

The same goes for the picture, it's used by c:geo and GK/GKM maps.

Sure sync all GK is not the way to go, `modifiedsince` parameter would be necessary in this case.

**Comment by okainov** [comment]
I just checked more deeper and found out that in ` https://api.geokrety.org/basex/export/` there is no `distancetravelled` now. It's not like super important, however we used to read and show it on gc.su, can it be returned?

**Comment by boly38** [comment]
With low availability, I'm progressing slowly on this subject but I'm progressing (https://github.com/geokrety/geokrety-service/tree/wip/gkmSync).
I'm not sure to understand okainov's remark about the doc: is it fair to indicate to update the doc on the export geokrety.xml (it seems not done) ?

**Comment by okainov** [comment]
@boly38 my point was just about updating API docs. Current docs (https://geokrety.org/api.php) include neither `basex` endpoint, nor any reference to the "new" API (api.geokrety.org?)

**Comment by boly38** [comment]
![image](https://user-images.githubusercontent.com/3100576/60967697-91f97500-a31b-11e9-83d3-f9a1065c57e6.png)
:)

**Comment by boly38** [comment]
#300 is a requirement, so the next step to go ahead on this issue

**Comment by kumy** [comment]
redis/prometheus/grafana deployed on `metrics` branch.

**Comment by boly38** [comment]
should be ok for 300, thanks a lots!
sorry ro say that but for sync we need push gateway too
like in 
https://github.com/geokrety/geokrety-website/blob/71e50315a3bee991e458c03cdc58adbd0f5fe9c7/gkShell/docker-compose.yml

💪

**Comment by kumy** [comment]
> sorry to say that but for 328 we need push gateway too

Better now that I'm hot :)

`pushgateway` added

**Comment by kumy** [comment]
This will not be needed anymore with GKv2. Closing
