### ISSUE TITLE
Edit username

### ISSUE THREAD

**Issue by harrieklomp** [geokrety/geokrety-website#34]
Sometimes people do ask how to change their username. On most sites you can change your username. Perhaps it can be made that users can change their username on the GK site also.

**Comment by kumy** [comment]
We have the functionality to change username properly in the admin pages. I also think this could be postponed to the full site rewrite.

**Comment by kumy** [comment]
We may add a link on the user page to contact us via e-mail.

**Comment by boly38** [comment]
- [ ] need to test with boly38 branch
