### ISSUE TITLE
Two fingers moves for maps on mobile

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#347]
We should activate the "two finger" moves for all maps whrn in mobile mode.

**Comment by okainov** [comment]
noooooo... whyyy???? One finger should move and two finger should zoom... why do you want to enable this ugly "two finger move" mode?

**Comment by kumy** [comment]
I personally like the two finger scroll because when the map is quite as large as the screen, passing through the map scroll the map, not the page. But community don t want it, lets forget!

What other think?

**Comment by kumy** [comment]
> One finger should move and two finger should zoom...

Just checked again and it's what is implemented in GKv2

> I personally like the two finger scroll because when the map is quite as large as the screen, passing through the map scroll the map, not the page. 

There is enough margin on the page to continue scrolling the page (and go over the map)

Closing then :)
