### ISSUE TITLE
Waypoint number result on logpage

### ISSUE THREAD

**Issue by harrieklomp** [geokrety/geokrety-website#35]
When search by cache name sometimes there are more caches with same or partly same search names in it. Loggers cannot select the correct waypoint to addl in left field without first go (via link) to the cachepage.

Perhaps add waypoint to result, so user can copy/past to waypoint field. Or by klick on suggested cache the correct waypoint goes to waypoint field.

![selectie_159](https://user-images.githubusercontent.com/1060518/38449371-7f1dac84-3a0e-11e8-9c31-e3bf3b9aa024.png)

**Comment by kumy** [comment]
It's the second part of #20
