### ISSUE TITLE
Some untranslated lines

### ISSUE THREAD

**Issue by harrieklomp** [geokrety/geokrety-website#36]
There are some more untranslated lines on https://geokrety.org/country_stat.php

![selectie_160](https://user-images.githubusercontent.com/1060518/38452696-7a8d388e-3a49-11e8-8c48-df55e80151de.png)

**Comment by kumy** [comment]
The only string I could add to the translation system is "Where are GeoKrety now?". The rest of the page is autogenerated by cron. It'll be to much effort to implement a multilingual page generation for GKv1.
