### ISSUE TITLE
Formating in users input

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#370]
Some fields in the site (GK mission, moves text, news comments) would need to accept a limited subset of html tags. Some pre-parser like ~~BBCode~~ Markdown would fit well in such situation. But don't forget, the database already contains html.

- [x] implement a WYSIWYG ~~BBCode~~ Markdown editor
- [ ] ~~update database content~~
- [x] add transformers on website template to render ~~BBCode~~ Markdown as html
- [x] update export scripts to have versions: noformat(legacy) / html / raw

Be careful on html escaping/unescaping and XSS :/

```
ALTER TABLE `gk-ruchy`
CHANGE `koment` `koment` text(5120) COLLATE 'utf8mb4_unicode_ci' NULL AFTER `user`;
```

**Comment by okainov** [comment]
I'm not sure, but probably you can use existing text editor (i.e. TinyMCE) plus use HtmlPurifier to process the code against whitelist of tags. No need to invent your own editors or parsers

**Comment by kumy** [comment]
The database should not contains html at all, this is so specific and has so many way to be written that it allows clients to make hard work to have it rendered properly in the way they wish. Markdown is nice for interoperability, and prevents all kind of (security) issues.

Anyway, we already strip *all* html tags from all GET/POST values unconditionally.

This is quite the same debate as `should the database contains html entities escaped string` -> no, it should have raw text. it's the responsibility of the rendering client to properly escape string based on the running context. Rules may not be the same in a browser, in an heavy client, system console, logs files… Also string should not be altered to pass "_securly_" any SQL request, those leading to use prepared statements ;)

**Comment by okainov** [comment]
>Markdown is nice for interoperability, and prevents all kind of (security) issues.

Hhhhm... So you force your clients to have an MD parser? Doesn't sound like a good idea IMO. MD it too specific, also users probably are not really familiar with it. I still do not understand what is your concern about HTML (except being security-paranoic :))

**Comment by kumy** [comment]
Just search on your favorite search engine for the keywords `html vs markdown`.

I'll not quote all arguments there but:
* Markdown uses a very simple formatting syntax
* it's simpler than HTML and you don't have to worry about opening and closing tags
* is human readable
* less error prone
* Its design allows it to be converted to many output formats
* we don't need advanced formating in our GK comments
* It gets used by GC.com, so easier for c:geo to post logs on both sites

Note: Markdown is also prone to XSS ;)
`[some text](javascript:alert('xss'))`
```
> hello <a name="n"
> href="javascript:alert('xss')">*you*</a>
```
> So you force your clients to have an MD parser

yes :) what's the problem?

> users probably are not really familiar with it

I know many users not familiar with html too

Just look at all our GH issues, we use it with great facility, imagine the time spent just to write the same comment with html?
Do you really think it's harder to type:
```
* one
* Two
* Three
```
than:
```
<ul>
  <li>one</li>
  <li>Two</li>
  <li>Three</li>
</ul>
```

what about:
```
<h1>Title</h1>
vs
# Title
```

```
some <b>text</b> with <i>emphasis</i> words?
some **text with** _emphasis_ words?
```

```
<hr>
---
```

And just for fun this comment as html:
```
<div class="comment-body markdown-body js-preview-body" style="min-height: 386px;"><p>Just search on your favorite search engine for the keywords <code>html vs markdown</code>.</p>
<p>I'll not quote all arguments there but:</p>
<ul>
<li>Markdown uses a very simple formatting syntax</li>
<li>it's simpler than HTML and you don't have to worry about opening and closing tags</li>
<li>is human readable</li>
<li>less error prone</li>
<li>Its design allows it to be converted to many output formats</li>
<li>we don't need advanced formating in our GK comments</li>
<li>It gets used by GC.com, so easier for c:geo to post logs on both sites</li>
</ul>
<p>Note: Markdown is also prone to XSS ;)<br>
<code>[some text](javascript:alert('xss'))</code></p>
<pre><code>&gt; hello &lt;a name="n"
&gt; href="javascript:alert('xss')"&gt;*you*&lt;/a&gt;
</code></pre>
<blockquote>
<p>So you force your clients to have an MD parser</p>
</blockquote>
<p>yes :) what's the problem?</p>
<blockquote>
<p>users probably are not really familiar with it</p>
</blockquote>
<p>I know many users not familiar with html too</p>
<p>Just look at all our GH issues, we use it with great facility, imagine the time spent just to write the same comment with html?<br>
Do you really think it's harder to type:</p>
<pre><code>* one
* Two
* Three
</code></pre>
<p>than:</p>
<pre><code>&lt;ul&gt;
  &lt;li&gt;one&lt;/li&gt;
  &lt;li&gt;Two&lt;/li&gt;
  &lt;li&gt;Three&lt;/li&gt;
&lt;/ul&gt;
</code></pre>
<p>what about:</p>
<pre><code>&lt;h1&gt;Title&lt;/h1&gt;
vs
# Title
</code></pre>
<pre><code>some &lt;b&gt;text&lt;/b&gt; with &lt;i&gt;emphasis&lt;/i&gt; words?
some **text with** _emphasis_ words?
</code></pre></div>
```

**Comment by okainov** [comment]
>Do you really think it's harder to type:

I think it doesn't matter since users use proper editor (usually WYSIWYG). Users do not type HTML manually. And neither they type MD. How do you store it in the backend - different story. I just don't see any points in spending efforts for converting database to MD values and then forcing clients to have MD parser (i.e. c:geo which parses HTML already and ALL other apps which some people may have eventually created)

> Markdown is also prone to XSS ;)

Doesn't matter if you use proper HTML parser (read "HTMLPurifier")

**Comment by kumy** [comment]
So we agree, users will use a WYSIWYG editor, having the possibility for advanced users to quickly format their logs, and being compatible with the formatting used on GC.com (c:geo for example post the same log on both platform at a time) is a plus.

Let's concentrate on the real problems, formatting has never been implemented in GeoKrety for any user input. So html or markdown, partners using the API may have to parse and render the data. Those not using the API are already parsing raw html… I think, we should consider removing all formatting in API endpoints to keep it retro-compatible. If we wish, as we use xml, we may later  easily extend xml responses to include, the 3 versions:
- raw/no formatting (description)
- html (description_html)
- markdown (description_markdown)

```
<geokret id="46684">
    <name><![CDATA[c:geo **tests**]]</name>
    <description><![CDATA[virtual, just for testing c:geo app. quote list sub]]></description>
    <description_html><![CDATA[
<p><strong>virtual</strong>, <em>just</em> for testing</p>
<ul><li>c:geo</li>
<li>app.</li>
</ul><blockquote>
<p>quote</p>
</blockquote>
<ul><li>list
<ul><li>sub</li>
</ul></li>
</ul><p><img src="https://new-theme.cdn.geokrety.house.kumy.net/images/obrazki-male/1502318298bg7ge.png" alt=""></p>]]>
</description_html>
    <description_markdown><![CDATA[**virtual**, *just* for testing
- c:geo
- app.

&gt; quote

* list
  * sub

![](https://new-theme.cdn.geokrety.house.kumy.net/images/obrazki-male/1502318298bg7ge.png)]]></description_markdown>
    <owner id="26422">kumy</owner>
    <datecreated>2014-09-12 17:23:41</datecreated>
    <distancetravelled>108896</distancetravelled>
    <state>1</state>
    <missing>0</missing>
    <position latitude="" longitude="" />
    <waypoints>
        <waypoint><![CDATA[]]</waypoint>
    </waypoints>
    <type id="0"><![CDATA[Traditional]]</type>
</geokret>
```
