### ISSUE TITLE
Get label templates name dynamically from template itself

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#375]
ATM name of the template and the template itself are somehow disconnected, so to add new template one needs to add logic AND modify list of templates manually. Would be much nicer to have some functionality like "read all templates and put them to the list" to avoid manual list updates.

**Comment by kumy** [comment]
@okainov are you interested in working on this issue?

**Comment by okainov** [comment]
@kumy I can see what I can do, depends how much logic around is involved, but for sure I can try ;)
