### ISSUE TITLE
cdn certificate expired

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#377]
https://cdn.geokrety.org/images/log-icons/0/0.png -> 
![image](https://user-images.githubusercontent.com/918446/58916687-afd42880-8724-11e9-9a33-26438d98705d.png)

Does LE update it only at the last day? Maybe it's better to configure it to update several days before actual expiration date...

**Comment by kumy** [comment]
Hum good catch, this is an old certificate from the old server. Will fix it now!

**Comment by kumy** [comment]
This one should be fixed.

**Comment by kumy** [comment]
https://geokrety.org also fixed.

**Comment by kumy** [comment]
@okainov thanks for the report :+1:
