### ISSUE TITLE
Warning message on www

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#378]
Accessing the site via https://www.geokrety.org/ display our warning panel, but in this case it should not be there :(

![Screenshot from 2019-06-05 00-25-41](https://user-images.githubusercontent.com/176794/58917911-7ac9d500-8728-11e9-88a2-6a30913f4c27.png)

**Comment by okainov** [comment]
Don't you want to set up redirects to canonical https://geokrety.org for all alternative domains?

I.e. 
- http://geokrety.org -> 301 -> https://geokrety.org
- http://www.geokrety.org -> 301 -> https://geokrety.org
- https://www.geokrety.org -> 301 -> https://geokrety.org
same for .pl or any other domains that you have for GK

**Comment by kumy** [comment]
Yup, good idea. This need to be configured in traefik.

**Comment by kumy** [comment]
Fixed
