### ISSUE TITLE
Missing translations on main page

### ISSUE THREAD

**Issue by harrieklomp** [geokrety/geokrety-website#38]
Some translations are not visible on main page and show English language. I believe this happened last weekend.

![selectie_163](https://user-images.githubusercontent.com/1060518/38683372-958bbeb2-3e6d-11e8-942a-a77fe7fe09b3.png)

**Comment by kumy** [comment]
You're right, strings were changed some days ago. It seems the automatic import/export process for translation is broken. i'll look at it. @harrieklomp Thanks for the report.

**Comment by kumy** [comment]
Ha!!! Site is actually is running on the `homestyle` branch. Translations are only uploaded for the master branch. @harrieklomp  So be prepared to translate new strings ;)

**Comment by kumy** [comment]
Here we are, translation import fixed. @harrieklomp Your translations are online. @boly38 sorry for the noise on master branch :(

**Comment by boly38** [comment]
@kumy no pb I'm 'git rebase' level expert 😂
