### ISSUE TITLE
Database structure sql is not working with MySQL 5.7

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#380]
Trying to set up the environment locally, I noticed that DB structure described in `\docker\mariadb\*.sql` is not properly working with MySQL 5.7, mostly due to incorrect default zeroed values for timestamps.

I don't know, it could be either out-of-date .sql files or old MySQL version being used for development...

Fixing queries (just use current time as default)

```
ALTER TABLE `gk-users`
	CHANGE COLUMN `ostatni_login` `ostatni_login` DATETIME NULL DEFAULT CURRENT_TIMESTAMP AFTER `ostatni_mail`;

ALTER TABLE `gk-geokrety`
	CHANGE COLUMN `timestamp_oc` `timestamp_oc` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `avatarid`;
```

**Comment by kumy** [comment]
I ll publish in a few hours a structure dump of the current database. Please stay tuned :)

**Comment by kumy** [comment]
Here we are. You'll find in PR #381 a fresh database structure dump.

**Comment by kumy** [comment]
BTW we use [mariadb:10.1](https://github.com/geokrety/geokrety-ansible/blob/master/templates/geokrety_legacy.yml#L159)
