### ISSUE TITLE
Coordinates are not rounded on logs page

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#382]
1. Go to logs page
2. Hover on some logs with coordinates
3. Coordinates are not rounded. Please round to max 5 digits after dot, the rest is useless.

![image](https://user-images.githubusercontent.com/918446/59150450-0d69bd00-8a24-11e9-8967-4ef93d1182c3.png)

**Comment by kumy** [comment]
I think the `new-theme` branch already has a fix for that, please check https://new-theme.staging.geokrety.org/konkret.php?id=73871

![Screenshot from 2019-06-08 20-42-22](https://user-images.githubusercontent.com/176794/59151128-12336e80-8a2e-11e9-898a-56c472ca9ec4.png)

so closing :)
