### ISSUE TITLE
[GKMap] No moles displayed when move the map around the Earth

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#387]
1. Open GKMap https://geokretymap.org/geokrety-world-map/#4/24.886/-271.406/0/1/0/0/90/
2. Move the map to the side to make the full "circle", so coordinates go more than normal limit (i.e. -271)
3. Make sure no moles are displayed

Probably `worldCopyJump` in Leaflet is not enabled or so (https://leafletjs.com/reference-1.5.0.html#map-option)

**Comment by kumy** [comment]
Thanks for the report, and thanks for the hint too.
Btw, GKM will fusion with GK starting from branch `new-map`, and bug also present there https://new-theme.geokrety.house.kumy.net/gkmap.php#2/37.996/-326.953/1/1/0/0/90/
