### ISSUE TITLE
Remove/reduce captcha for logged in users

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#389]
(new theme-related probably)

For me as a user I hate to see any types of captcha, because of the website being paranoic. Yes, if it's anonymous access and some actions are available, there probably for sure you want to make illusion of protection a bit.

But can we get rid of captcha for logged in users? Or at least make website less paranoic - if users wants to sent 2-5-10 messages to other users per day - it's okay, no need to be suspicious. Show captcha only if user tries to sent 100 messages per day - completely understandable and makes sense.

**Comment by kumy** [comment]
This is discussable, we had in the past a user sending spam from there this was the first counter measure, the second was to rate limit messages to one per 15 min. No one asked to raise the limits yet.

Anonymous users are not able to send messages to users. We should find a balance between protection and liberty.

Ping @boly38 what's your thought here?

**Comment by kumy** [comment]
Let's keep it on `send message to user` page to prevent spam - `new-theme`
