### ISSUE TITLE
Add an info box on top of GK page when waiting for adoption

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#39]
Our GK mass generator offer the possibility to adopt GK. The current link to the adopt page is not very visible.

I propose to add an alert message on top of the GK page including explanation and link to the adoption page.

**Comment by boly38** [comment]
maybe teach us about 'Our GK mass generator' because I were not able to find it on website ?
(add help section with this issue)

**Comment by kumy** [comment]
The mass GK generator is an admin feature the related code is https://github.com/geokrety/geokrety-website/blob/master/generatorek.php
