### ISSUE TITLE
[New UI] Replace small kret icon

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#390]
Currently there is nice general GK icon which is used for avatar, probably we should use the same for small icon (see screenshot)

![image](https://user-images.githubusercontent.com/918446/59156787-3ed49e00-8aa1-11e9-9c71-687b68e34562.png)

**Comment by kumy** [comment]
Why not. Should we keep the originals icons for other types of GK? As it is currently built, changing this icon only will translate as some if case condition in the code to not break actual website. Changing all at once, will allow us to have clean code, and to not break prod website.

Anyone willing to propose new svg icons for types coin, kretypost, human and books?

**Comment by Lineflyer** [comment]
On the new staging platform there is still the small icon used (leonardo da vinci representing a human).
Using a small version of the users avatar would be more meaningful.
