### ISSUE TITLE
[New UI] Add Drag-n-Drop images upload

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#391]
Please add drag-n-drop support for adding new images (in this case, for GK avatar)

![image](https://user-images.githubusercontent.com/918446/59156804-9c68ea80-8aa1-11e9-878e-69fb26b09542.png)

**Comment by kumy** [comment]
I agree this is a must have feature.

**Comment by kumy** [comment]
Done in `new-theme` branch. (Not yet deployed)
