### ISSUE TITLE
Align on "Geokret"/"GeoKret"/"GeoKrety" usage

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#392]
As I was going thru strings for Russian translations, I found out that ATM the name is not really aligned across the site, in some places it's `GeoKrety`, in some it's `Geokrety`, somewhere not capitalized at all `geokrety`. Probably it would be nice to align on usage and define the way to spell the name around.

Probable it should be something like this (just a random suggestion)

- Name of the website and service itself `GeoKrety`
- Name of the trackable items `Geokrety` (plural) / `Geokret` (singular). Or maybe "Geomole"? But this looks confusing, everyone got used to polish naming I think...

**Comment by kumy** [comment]
I personally tend to always use GeoKrety and GeoKret form. I change them when I find them. Did you encounter errors on new-theme?

**Comment by okainov** [comment]
I'm not sure about actual usage, but since the strings are on CrowdIn, I assume, they're being used somehow

![image](https://user-images.githubusercontent.com/918446/59157167-40549500-8aa6-11e9-9a44-52d9d817d325.png)

**Comment by kumy** [comment]
Crowdin don't include strings from new-theme yet :/

**Comment by kumy** [comment]
Should be better in `new-theme`. Errors on `new-theme` will new new issue and/or PR
