### ISSUE TITLE
Add a menu link directing to the adoption page

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#40]
Following #39, what about adding a link to the adoption page directly in the left menu.

What should be it's place?

It should be displayed only for authenticated users.

**Comment by kumy** [comment]
@boly38 good idea this new label :+1:

**Comment by kumy** [comment]
@filipsPL @boly38 Is this ok for you?

![screenshot from 2018-04-13 19-59-01](https://user-images.githubusercontent.com/176794/38750419-25bdb44e-3f55-11e8-8f7f-ea80cdc948cf.png)

**Comment by boly38** [comment]
just to say a minor feedback I suggest to permut 'claim' and 'my account'. but that's not major. I'm ok

**Comment by kumy** [comment]
Here it is 
![screenshot from 2018-04-13 20-12-28](https://user-images.githubusercontent.com/176794/38751024-15405188-3f57-11e8-8b58-ef54507e979f.png)
