### ISSUE TITLE
"lost geokrety" page not migrated to new theme

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#402]
https://new-theme.staging.geokrety.org/lost.php

Page contains thousands of GKs, creates extra load for the server, bu I'm not sure that it's helpful in its current view at all. Probably it can be either removed or somehow reorganized (i.e. "last XX geokrety which can be lost")

**Comment by kumy** [comment]
No problem regarding server load as the page content is generated daily. As this page is not dynamically generated, the eventual pagination/filter need to be pure JS.
