### ISSUE TITLE
[New UI] Emoji support

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#403]
Although database seems to be in proper `utf8mb4`, Unicode is not supported as expected.

I tried:
- [ ] GK name
- [ ] Log comment
- [ ] GK mission

Insert some emojis (like 🙈😂😱🍰) -> all of them will be shown as question marks

**Comment by kumy** [comment]
Not really a bug, it's broken as I have synchronized database from production yesterday and not yet applied the necessary database changes

**Comment by kumy** [comment]
Link #225

**Comment by kumy** [comment]
Fix applied to `new-theme`, please check again
