### ISSUE TITLE
Update Codacy ruleset

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#405]
https://app.codacy.com/app/GeoKrety/geokrety-website/pullRequest?prid=3718167
>The "WordPress.WP.PreparedSQL" sniff has been renamed to "WordPress.DB.PreparedSQL". Please update your custom ruleset.

Probably there are some actions to be done

**Comment by kumy** [comment]
Issue is now outdated. Feel free to reopen if necessary
