### ISSUE TITLE
Some GK are not visible on geocaching.su

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#406]
From support mail by Vladimir

> Hi, we have old problem now again. Some days ago we have a problem with correct work of geokrets on site geocaching.su
> 
> Many geokrets are not visible on a page of the cache if we put them there some time ago.
> 
> As example we  put in cashe  geokrets some days ago and these geokrets  are invisible now. See Link please:
> 
> https://geokrety.org/konkret.php?id=69367#map
> 
> https://geokrety.org/konkret.php?id=61655
> 
> Thank you very much. We need your help!

**Comment by kumy** [comment]
@okainov I'm not used to use geocaching.su website, but I see our mole logo on the pages https://geocaching.su/?pn=101&cid=18165 and https://geocaching.su/?pn=101&cid=15749 does it mean GK are correctly seen? Also, I have absolutely no idea how gc.su is retrieving/synchronizing GK location. Do you know the process (may you share it with us)? May you inquiry on this problem please?

**Comment by kumy** [comment]
FTR, the problem was already encountered in december 2017, the conclusion was:

> Our programmer said the following about the problem that was:
> 
> There was a script that worked without fail on
Over a period of years and went to Geocrots
at http://geokrety.org/export_oc.php?modifiedsince= <date>.
But here in November-October mole site
was updated and, among other things, they decided, judging
around, only move to HTTPS
(earlier, as can be seen from the link, there was HTTP). And on
our ancient server does not have libraries,
working with HTTPS, so everything in one
a beautiful day stopped working.
Actually, the fix was to write
a pair of lines that our server understands,
who pull the same page from the site
moles https://geokrety.org/export_oc.php?modifiedsince= <date>
(we pay attention to the letter s in the protocol).
> 
> Now all is work correctly and we happy.

**Comment by Detroit70** [comment]
This geokrets was be add on site after 11 june and they invisible
https://geokrety.org/konkret.php?id=69367#map

https://geokrety.org/konkret.php?id=61655

All that you see on this link and visible was be added before 10 june
https://geocaching.su/?pn=101&cid=18165 
 https://geocaching.su/?pn=101&cid=15749 

Sorry english not good.

**Comment by kumy** [comment]
It seems gc.su missed some updates at some point.

Retrieving all updated GK using the `export_oc.php` endpoint I can successfully see the GK 61566 and 69367 are present. So for me problem is on gc.su side. Their database is not well synchronized.

```
$ curl "https://geokrety.org/export_oc.php?modifiedsince=201906100000" > /tmp/issue-406.xml
$ xmlstarlet sel -t -c '//geokret[@id=61655 or @id=69367]' /tmp/issue-406.xml 
<geokret id="61655">
  <name>Островский Николай</name>
  <distancetravelled>339</distancetravelled>
  <state>0</state>
  <position latitude="61.07800" longitude="36.09900"/>
  <waypoints>
   <waypoint>TR15749</waypoint>
  </waypoints>
 </geokret><geokret id="69367">
  <name>Призрак ВИЛа копия 35</name>
  <distancetravelled>0</distancetravelled>
  <state>0</state>
  <position latitude="59.69062" longitude="30.60247"/>
  <waypoints>
   <waypoint>TR18165</waypoint>
  </waypoints>
 </geokret>
```

@okainov I tend to close this issue here, as problem doesn't seems to be on our side. Also, - I can't find the issue but - I have in mind that some days ago you updated some cron on gc.su side to synchronize more frequently, could the problem be related ? I imagine some issue with timezone and some periods of time skipped.

**Comment by okainov** [comment]
> but I see our mole logo on the pages <...>does it mean GK are correctly seen?

Yes and no. If you see the logo it means that cache contains *some GK(s)*. To make sure you need to click on the logo - either one GK page will be opened (if there is only one GK in the cache) or our popup with a list of GKs will be opened)

> Also, I have absolutely no idea how gc.su is retrieving/synchronizing GK location

Still the same, `https://geokrety.org/export_oc.php?modifiedsince=%s` for incremental fetch (every 2 hours) and `'https://api.geokrety.org/basex/export/geokrety.xml` for full fetch (I scheduled in once a month I think)

In addition I rewrote a script of synchronization to Python, and actually I was noticing some time gap issues. Just to be sure now I added 1 hour overlap for `modifiedsince` query and re-run full refetch (so I can see mentioned GK now correctly). Should be good now, and let me know if anything goes wrong again.

Thanks for heads up!

**Comment by kumy** [comment]
Thanks. Let's close then.

**Comment by Detroit70** [comment]
Hi,
Sorry for delay with answer. I am in trip now/
Thanks for answer.
Best regards Vladimir

вс, 16 июн. 2019 г. в 19:51, kumy <notifications@github.com>:

**Comment by kumy** [comment]
> I have in mind that some days ago you updated some cron on gc.su side to synchronize more frequently, could the problem be related ?

Here is the conversation I was refeing: https://github.com/geokrety/geokrety-scripts/pull/8#issuecomment-500196973

**Comment by Detroit70** [comment]
Hi,
I don't know if that was the problem. I will try to know about it and send
message to you if will be news.
Now all is working.
 Best regards Vladimir

ср, 19 июн. 2019 г. в 21:50, kumy <notifications@github.com>:
