### ISSUE TITLE
disable `Deploy` stage for PR

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#407]
Looking at PR #373 in travis, we can see that `Deploy` is failing. I'm wondering if this should be disabled at all for PR or just for external contributors.

@boly38 any idea?

**Comment by boly38** [comment]
did you talk about this QA results: https://travis-ci.org/geokrety/geokrety-website/jobs/544354471 ?

**Comment by kumy** [comment]
Not qaResults but 'deploy' stage. The one wich sync translations

**Comment by kumy** [comment]
I think it's resolved on new-them, closing, reopen if needed.
