### ISSUE TITLE
`Qatests` in CI require encrypted variable to run

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#408]
Lookinat PR #373 and travis-ci work https://travis-ci.org/geokrety/geokrety-website/builds/544569554 we may see error 

```
The command "bash ./scripts/qatests_hook.sh ${TRAVIS_QA_TOKEN} ${TRAVIS_BRANCH}" exited with 1.
```

What should be done here? Disable `Qatests` completely for external contributors or try to launch the test anyway and skip the part which need authentication - I'm supposing the private variable is to authenticate test results upload.

ping @boly38

**Comment by kumy** [comment]
https://docs.travis-ci.com/user/pull-requests/
> If your build relies on encrypted variables to run, for instance to run Selenium tests with BrowserStack or Sauce Labs, your build needs to take this into account. You won’t be able to run these tests for pull requests from external contributors.
> 
> To work around this, restrict these tests only to situations where the environment variables are available, or disable them for pull requests entirely, as shown in the following example:
>
 ```
script:
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
```

**Comment by boly38** [comment]
hey good catch
we need to disable completely QA as token is used to call travis build webhook

without this token we can't start at all website-qa job.

**Comment by kumy** [comment]
There was lots of refactor in this area. It should has been fixed in the meantime.
