### ISSUE TITLE
hall of fame image broken

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#41]
https://geokrety.org/halloffame.php
bottom of this page includes broken image for tools.
![img_20180412_210109](https://user-images.githubusercontent.com/3100576/38698327-f6974984-3e94-11e8-96e7-9d61fcd9f51d.png)

---
work branch: [feature/halloffame](https://github.com/geokrety/geokrety-website/tree/feature/halloffame)

---
- [x] improve config 'icon_width'
- [x] integrate into target page ([demo](https://boly38.gk.kumy.org/halloffame.php))
- [x] move icons files to CDN and update related config url
- [x] squash, rebase, PR

**Comment by kumy** [comment]
(They are quite obsolete! It's time to review the list.) Icons have to be committed in https://github.com/geokrety/GeoKrety-Static and the cdn updated with the new commit then page updated to match new url.

@boly38 would you work on this issue? If yes, assign yourself :)

**Comment by boly38** [comment]
- [ ] add ldjson reference

**Comment by boly38** [comment]
This comment should embeed the target list of os/tools/components/frameworks to include in  `halloffame` page. 
We maybe should restrict this list to the major components (ex. we dont want to references all linux library ;) )

(@kumy feel free to complete directly this comment if needed)

For each item provide a "short name" + wanted icon url (if any).
- php
  - http://php.net/images/logos/php-power-white.gif
  - php related: [composer](https://getcomposer.org/), [smarty](https://www.smarty.net/docsv2/fr/), [phpunit](https://phpunit.de/), [FriendsOfPHP/PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer), [Torann/json-ld](https://github.com/Torann/json-ld)
- apache (+extensions) : web server application
  - ([source](https://www.apache.org/foundation/press/kit/)) https://www.apache.org/foundation/press/kit/poweredBy/Apache_PoweredBy.svg 
- docker : os virtualization
   - ([source](https://www.docker.com/legal/brand-guidelines)) todo: download media kit
- git : source code management
   - ([source](https://git-scm.com/downloads/logos)) https://git-scm.com/images/logos/2color-lightbg@2x.png
- github : online project management
  - ([source](https://github.com/logos)) todo: download brand kit
- travis : continuous integration
  - ([source](https://travis-ci.com/logo)) https://travis-ci.com/images/logos/TravisCI-Mascot-pride.png
- codacy : manage code quality
  - http://opensource.codacy.com/img/logo-codacy.png (free to use?)
- crowdin : manage translations
  - ([source](https://support.crowdin.com/using-logo/)) https://support.crowdin.com/assets/logos/crowdin-TranslationManagementService-logo.png

**Comment by kumy** [comment]
I can think of:
- adnanh/webhook: configurable incoming webhook server
  - ([source](https://github.com/adnanh/webhook/tree/master/docs/logo)) https://github.com/adnanh/webhook/blob/master/docs/logo/logo-128x128.png

- Sentry: Open-source error tracking
  - ([source](https://sentry.io/branding/)) https://sentry-brand.storage.googleapis.com/sentry-glyph-black.svg

- NASA SRTM: SRTM-30 to get the altitude
  - https://www2.jpl.nasa.gov/srtm/

- Bootstrap: popular HTML, CSS, and JS framework
  - ([source](https://v4-alpha.getbootstrap.com/about/brand/))

- flag-icon-css: http://flag-icon-css.lip.is/
- openstreetmap: https://wiki.openstreetmap.org/wiki/Logos

**Comment by boly38** [comment]
live demo :p 
https://boly38.gk.kumy.org/halloffame.php

**Comment by kumy** [comment]
So nice!!!!

> SRTM-30 to get the altitude

missing 's' - altitudes?

**Comment by kumy** [comment]
* mariadb not MySql

**Comment by boly38** [comment]
- [ ] mariadb + description
- [ ] altitude(s)
- [ ] robot framework for qa tests
