### ISSUE TITLE
Align state between export_oc and exports

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#411]
I just realized that in `export_oc` (https://geokrety.org/export_oc.php?modifiedsince=20190610005502) there is only `state` which goes to 1 if GK is not in the cache, however in `exports` (api.geokrety.org/basex/export/geokrety.xml) there are two fields: `state` and `missing` and when `missing==1` `state` could be still 0.

Could you please either align this or at least highlight it some some docs that the results are really different?

**Comment by kumy** [comment]
The page https://new-theme.staging.geokrety.org/help/api#syncmethod2 has a note about that.
![image](https://user-images.githubusercontent.com/176794/210426899-38055d4c-f9fb-4185-b31d-f84435348987.png)

With `GKv2` there should be no restriction for partners to use any of the 3 export methods. (Beside the page still saying the opposite).

I'll close this one, feel free to reopen if you believe something else should be done!
