### ISSUE TITLE
Recent logs are not recent

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#412]
It seems that recent logs are not really recent -_- 

Today is end of June:
![image](https://user-images.githubusercontent.com/918446/59795297-3703cd80-92db-11e9-8c3b-d0be099f1afe.png)

**Comment by kumy** [comment]
I already seen that, and thought that it display last posted logs whatever is the `move date`, but never really choose if it should be changed or not. Maybe we may change it for the new theme change


https://github.com/geokrety/geokrety-website/blob/5bc7b5f93dc8953d7c661524d0d889fe4d4698cc/website/index.php#L48-L50

https://github.com/geokrety/geokrety-website/blob/5bc7b5f93dc8953d7c661524d0d889fe4d4698cc/website/lib/geokrety/repository/TripRepository.class.php#L301-L309

**Comment by kumy** [comment]
Fixed in `new-theme`.
