### ISSUE TITLE
Create roadmap

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#415]
As mentioned in https://github.com/geokrety/geokrety-website/pull/381 you support idea of having some kind of roadmap :)

I think it is really useful for both developers and users (I don't know though how do you communicate with your community): for users to see that service has some meaningful direction of development and for the team to have a plan with at least something like commitments what to do :)

I see that currently you already have some stuff in mind (i.e. full redisign with Bootstrap), however probably it should be more visible. Maybe some Github features, maybe some kind of blog (inspired by one of the [projects](http://kiwitcms.org/blog/atodorov/2018/12/17/roadmap-status-report-for-2018/) we currently use)

**Comment by kumy** [comment]
As the community is quite not active in development, and our code base is quite complex, I expected to do promotion after releasing `new-theme`, as I expect it to be like an electroshock.

Yes, Roadmap is necessary as we start to be more - 3 actually - to contribute, so yes we have to know where we go. I think we may put it first in our [wiki](https://github.com/geokrety/geokrety-website/wiki/ROADMAP), then later add it as a dedicated `ROADMAP.md` file in the repo.

Regarding communication, we mostly used to post news on website, and @boly38 relay the information on social medias.

**Comment by okainov** [comment]
I think I don't have write access to wiki, neither I know details about current status, issues and plans, but I tried to make some super-high-level draft of the structure :)

# Development plans and areas for Geokrety.org


## Community

- Advertise GK more? Analyze search engines, SMM, email involvement and so on. Also IRL activities maybe?
- Improve integrations and partnership with GC services (educate people about GKs, add more integration features to less supported services?)

## UI

- New redisign for proper mobile-friendly version and fresher look

## Features

Is there any kind of voting for features from community side? It could be a good indicator if a lot of users are asking about something. Is there some kinda messages for donating, maybe paying users are asking for something?

And/or prioritized list of Github issues? However there should be still some kind of major direction...

## Development
Internal tasks which do not have direct impact on the service, however are important for ease of maintenance, support and involving new contributors.

- Tests, refactoring, bloody legacy?
- Documentation (API?)
- ~~Deploy process~~

**Comment by kumy** [comment]
@okainov I've invited you as a contributor so you'll have access to the wiki.

**Comment by kumy** [comment]
This is a first start, thanks!

**Comment by kumy** [comment]
Roadmap updated with chronological steps https://github.com/geokrety/geokrety-website/wiki/ROADMAP
