### ISSUE TITLE
Labels: ErrorException: Class name must be a valid object or a string

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#416]
Our sentry catch this error on production:

URL | http://geokrety.org/templates/labels/index.php

```
ErrorException: Class name must be a valid object or a string
 File "index.php", line 14, in handleFatalError
 $template = new $kret_szablon();
 File "/var/www/html/templates/sentry-php-master/lib/Raven/ErrorHandler.php", line 0
 Raven_ErrorHandler->handleFatalError
```

@okainov I've assigned it to you, will you be able to provide a fix? Thanks

BTW I'm wondering why the reported url is not SSL :/

**Comment by okainov** [comment]
Will take  a look when I'm back home on Sunday

**Comment by okainov** [comment]
It's somehow not expected that this page is accessed "as is", probebly I need to add post request validation and redirect back if no params are specified

Btw I wonder is it expected to have error text on prod just "as is"? I would expect that production should have display_errors=False or so

**Comment by kumy** [comment]
Sentry issue: [GEOKRETY-LEGACY-3H9](https://sentry.kumy.org/geokrety/geokrety-legacy/issues/3833/?referrer=github_plugin)

**Comment by kumy** [comment]
`GKv1` -> closing
