### ISSUE TITLE
remove Google+ fantom

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#417]
As Google+ Rest In Peace right now

we need to remove G+ references from geokrety website:
- [ ] group listed at bootom of help page (konfig-groups)
- [ ] footer

-- 
https://github.com/geokrety/geokrety-website/blob/d6e34be7a3148a3e135422e72f618e544bc58f09/website/templates/konfig-groups.php#L29-L35

**Comment by kumy** [comment]
Let's close as it's not included in new theme.
