### ISSUE TITLE
Search by cache name should be available for SU as well

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#422]
Currently search by cache name has label `Enter cache name. Works only with opencaching networks. `

However DB probably already contains names at least for SU caches, so it shouldn't be "oc-only"

**Comment by kumy** [comment]
Sure it should work, but how to formulate it so GC only cachers will understand it?

**Comment by okainov** [comment]
>Sure it should work, but how to formulate it so GC only cachers will understand it?

Maybe as is? "Does not work for gc.com caches"

**Comment by kumy** [comment]
I would prefer a simple sentence to not overwhelm users with many information on this form. Let's cahnge to "Does not work for gc.com caches" first, we'll still can change wording later.

**Comment by okainov** [comment]
@kumy  but... search still doesn't work for SU caches, does it?

- Enter "Замок" in search field
- Check dev console, API returns results ok ([link](https://new-theme.staging.geokrety.org/check_wpt_name.php?query=%D0%97%D0%B0%D0%BC%D0%BE%D0%BA))
- No caches are suggested in UI

**Comment by kumy** [comment]
Effectivelly, api returns result but UI refuse to display it. However searching by waypoint TR16017 works fine.

**Comment by kumy** [comment]
@okainov it should be better now. Thanks for finding this issue! (Just wait some minutes for the redeploy) And please close if it's working as expected.

**Comment by okainov** [comment]
Seems ok now
