### ISSUE TITLE
Fill in GK code when clicking on "log this GK"

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#426]
1. Go to "Watched GK" or any other page where there is list of GKs
2. Click on "smile" icon to log the GK
3. Make sure page with the proper ID opens (i.e. https://new-theme.staging.geokrety.org/ruchy.php?nr=1DPAZX) but number is actually empty

Please fill in numbers for the known GKs

**Comment by kumy** [comment]
Implicitly fixed.
