### ISSUE TITLE
 OCPL: Cache types and changes

### ISSUE THREAD

**Issue by andrixnet** [geokrety/geokrety-website#427]
With OCUS migrating from very old code to current OCPL code, some changes have to be implemented regarding cache_types. 

Cache type changes [here](https://github.com/opencaching/opencaching-pl/issues/2024)
New cache types [here](https://github.com/opencaching/opencaching-pl/issues/860)
Implementation progress [here](https://github.com/andrixnet/opencaching-pl/tree/cache_type)

Cache types documentation [here - wiki](https://wiki.opencaching.eu/index.php?title=Cache_types)

AFAIK GeoKrety website uses `xml/ocxml11.php` to communicate with OCPL site(s).
This is an old and [unmaintained ](https://github.com/opencaching/opencaching-pl/blob/master/xml/README.txt) code.
I've been told that this interface exposes internal ID numbers (for cache types), thus potentially affecting Geokrety data exchange.

Please take into account the upcoming changes.

**Comment by kumy** [comment]
Ok, what is the ETA of the `upcoming changes`?

**Comment by andrixnet** [comment]
Most changes have been implemented. 
I also asked for help with some details from the rest of the OCPL team. 

I estimate at least a week away.
Also notified OCPL developers of the need to coordinate with Geokrety team.
Thank you

**Comment by kumy** [comment]
I hope we'll be in time!

**Comment by kumy** [comment]
ping @boly38 @okainov :smile_cat:

**Comment by kumy** [comment]
I suspect we should now use OKAPI, but which endpoint will give us list of changed/created geocaches since last update datetime as it was with `ocxml11.php`?

**Comment by okainov** [comment]
Switch to OKAPI for synchronization form GK side - https://github.com/geokrety/geokrety-scripts/pull/11

**Comment by kumy** [comment]
Thanks to @okainov, OKAPI is now used for:
* OCPL
* OCDE
* OCUK
* OCUS
* OCNL
* OCRO
