### ISSUE TITLE
gk-waypointy table still is in unicode_polish_ci

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#430]
Probably was either missed or even completely untouched during internationalization/emoji support activities. Currently names of GC waypoints do not support emoji (especially there are some at oc.de), so it's better to switch to utf8mb4

**Comment by kumy** [comment]
Hum, #225 is not merged yet, and for me it already contains necessary conversions.

**Comment by kumy** [comment]
(Full emoji support will only be enabled after migration to new theme. It's incompatible with some current form fields cleanup in the actual legacy code.)
