### ISSUE TITLE
`gk-waypointy` many waypoints in database don't have coordinates

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#431]
In the `gk-waypointy` table, many gc.au don't have valid coordinates, country, altitude values.

Ex:
![Screenshot from 2019-07-12 22-02-13](https://user-images.githubusercontent.com/176794/61155287-d1c58580-a4f0-11e9-8f67-125092d86adc.png)

**Comment by kumy** [comment]
Same for OC.de, geocaching.gpsgames.org

![Screenshot from 2019-07-12 22-04-04](https://user-images.githubusercontent.com/176794/61155362-0a655f00-a4f1-11e9-98c1-440615e56ea0.png)

**Comment by kumy** [comment]
There is 7,196 rows in database without country, 1,980 rows were lat is `0.0000`.

A general check should be done in this area…

**Comment by okainov** [comment]
Just checked for my local dump produced from OKAPI and found just 100 entries with zero coordinates. Most of them seem to be garbage/archived caches (i.e. http://www.opencaching.us/viewcache.php?wp=OU01B8)

Don't really see a big problem here.

**Comment by kumy** [comment]
BTW: Archived caches should have `status` equal to `3`.

**Comment by kumy** [comment]
Database seems cleaned in `GKv2` -> closing
