### ISSUE TITLE
Block access to some subdirectories

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#432]
We should block access to some directories like:
* /website/vendor
* /website/help
* /website/lib
* /website/mapki
* /website/rest
* /website/robots-files
* /website/templates

At the webserver level. Those files are not to be accessed directly.

**Comment by okainov** [comment]
Why do you ever have `vendor` inside wwwroot? The rest is ok, I can understand, but composer stuff usually you put on top level

Can be done in nginx quite easily, like `location ~ ^/(help|lib|mapki) { return 403;}` or so

**Comment by kumy** [comment]
> Why do you ever have vendor inside wwwroot?

@okainov Do you have some examples for installing composer packages away from `wwwroot`?

How do you consider interoperability with other platforms (Linux, mac, Win) if we choose to install them in `/usr/local/share/php/geokrety`? What about non privileged users cloning the repo and launching `composer install`? In my opinion, installing to a sub-directory only solves all those problems at once.
