### ISSUE TITLE
ErrorException: file_get_contents(https://www.opencaching.nl/okapi/services/replicate/changelog?consumer_key=...

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#447]
https://sentry.kumy.org/geokrety/geokrety-legacy/issues/4744/?referrer=github_plugin

```
ErrorException: file_get_contents(https://www.opencaching.nl/okapi/services/replicate/changelog?consumer_key=...&since=121033): failed to open stream: HTTP request failed! 
  File "xml2sql.php", line 398, in handleError
    $raw = file_get_contents($downloadUrl);
  File "/var/www/html/templates/sentry-php-master/lib/Raven/ErrorHandler.php", line 0, in file_get_contents
    Raven_ErrorHandler->handleError
  File "xml2sql.php", line 398
    $raw = file_get_contents($downloadUrl);
```

**Comment by okainov** [comment]
At least at the moment this link works returning `{"changelog":[],"revision":121033,"more":false}`. Maybe some random issue? Should we introduce try-retry with some timeout?

I sometimes was getting issues when `since` was too old, but if it's run regularly then shouldn't be an issue.

**Comment by kumy** [comment]
We should just handle correctly when remote server has down times

**Comment by kumy** [comment]
Closing as I didn't saw much issue on GKv2 yet...
