### ISSUE TITLE
add new log (ruchy) now is considered as in the future 

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#448]
I just create a new GeoKrety, and I add a new log (visit my home cache): ruchy form told me that I'm trying to set a date in the future:
![image](https://user-images.githubusercontent.com/3100576/61964989-7b1b7980-afcf-11e9-9816-4abe02df08b7.png)

I had to remove 2 hours to success in form submission: so I suspect TimeZone issue while comparing current date and server date

**Comment by kumy** [comment]
Argh. Db was moved to utc, but it wasn t failing as such in tests. Are you able to circumvent it by code fix. I m not available

**Comment by kumy** [comment]
Btw all datetime shoulf be given as utc, as we don t yet support tz correctly. I m wondering what the behaviour in other apps, cgeo, oc sites...

**Comment by kumy** [comment]
It s also broken in cgeo.

Notify @Lineflyer

**Comment by Lineflyer** [comment]
Thanks @kumy for notifying. From what I read I guess this is just for information for c:geo but nothing we can do on our side to work around it?!

**Comment by kumy** [comment]
@Lineflyer, no, nothing on your side.

On July 26, 2019 7:27:12 PM GMT+02:00, Lars <notifications@github.com> wrote:
>Thanks @kumy for notifying. From what I read I guess this is just for
>information for c:geo but nothing we can do on our side to work around
>it?!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/geokrety/geokrety-website/issues/448#issuecomment-515535597

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment]
Dirty workaround will be auto-deployed in a few minutes

**Comment by boly38** [comment]
where unable to reproduce just [now](https://geokrety.org/konkret.php?id=74791#map), so it's ok from website point of view

**Comment by kumy** [comment]
Restore default timezone in ansible config. Workaround commit reverted.
