### ISSUE TITLE
Daily mail doesn't display well in some mail clients

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#451]
Reported by @Lineflyer, our daily mails are badly displayed.

In his case, he post GeoKrety logs automatically along with his GC.com logs using c:geo. As GC.com support only Markdown for formatting logs, he use this language as default, and have in his signature a link formatted in valid markdown: `[c:geo - Android](https://www.cgeo.org)`. Our legacy code try to be zealous and try to find any url strings in comment text and make it an html link. This give some weird and broken links such as `[c:geo - Android]([<a
href='https://www.cgeo.org)' rel=nofollow>Link</a>]`. Displaying it in our website doesn't seems to breaks the html rendered, but it causes troubles in daily mails.

In thunderbird, rendering seems correct, but he founds that on default "samsung's mail client on tablet" it render broken. The signature at the end of message seem to be placed at the beginning.

** samsung mail client **
![Screenshot from 2019-08-04 11-32-54](https://user-images.githubusercontent.com/176794/62422007-a37c3580-b6ab-11e9-8250-13e327adc82d.png)

** thunderbird **
![Screenshot from 2019-08-04 11-33-33](https://user-images.githubusercontent.com/176794/62422012-c1e23100-b6ab-11e9-934e-0b49250c97bc.png)

I see some possible enhancements:
1. stop being zealous, and don't try to format links. (Easy and fast, but incomplete solution)
1. hack/fix our mail routines to properly encode such case
1. Backport to legacy from the `new-theme` branch some code that make this field supporting Markdown input, but also the code that render it on pages. This will greatly help on migration to `new-theme`. We should also take case to properly update all the historical logs. ie convert them to markdown (remove `<br />` tags, convert links to markdown links, remove all spaces after `#` to not have them rendered as `heading`. The daily mails should also render markdown as html. 

@Lineflyer, do you think c:geo has to be updated to render GK comments written in markdown? or it has already the necessary code in place as I suspect it already render GC comments as markdown correctly.

link to #370.

**Comment by Lineflyer** [comment]
cgeo does not support markdown AFAIK.
It shows gc.com logs, which have orginally composed in markdown but downloaded to c:geo in HTML due to the nature of our access to the website.

**Comment by Lineflyer** [comment]
Regarding the view on my mobile device which @kumy cited above:
I think it is a client issue. I only have this on one device. On normal mail client it displays normal.

**Comment by kumy** [comment]
`new-theme` branch use a framework to build mail, those should disappear with the site rewrite. Let's keep it open until we test this part with your mail client when ready on our side.
