### ISSUE TITLE
Some of our daily mails are rejected by distant servers

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#457]
That's the 3rd case in 2 days, our daily mails are rejected. That concerns different receiving domains:
* gmail.com
* yahoo.fr
* sfr.fr

The `learn more` link is https://support.google.com/mail/answer/69585
Nothing changed on our side since some time, quite strange. Does those users manually placed our mails in some spam folder on their side?
I know personally one of them, I'll ask him.

![2019-08-25_16-05](https://user-images.githubusercontent.com/176794/63651144-2d229e80-c752-11e9-8423-3467d367db28.png)
![2019-08-25_16-04_1](https://user-images.githubusercontent.com/176794/63651145-2dbb3500-c752-11e9-8c66-7e4e25e0697b.png)
![2019-08-25_16-04](https://user-images.githubusercontent.com/176794/63651146-2dbb3500-c752-11e9-8a79-079c877625db.png)

**Comment by kumy** [comment]
Private mail sent to user `gueta`.

**Comment by kumy** [comment]
My friend told me that 3 of our mails where in the spam folder. He moved them out of this directory... Let's wait until tomorrow.

**Comment by kumy** [comment]
New occurence for `@gmail`

**Comment by boly38** [comment]
>He moved them out of this directory... 
How ?

for related gmail users, they needs to go into "spam" folder" to retrieve last daily mail, and on that mail, there is a "non-spam" button + "this is not a spam" banner with a link. I think they must told to gmail that this is not a spam to unlock related mails.


Did your action fix the issue for gueta for example?
(I don't know how to fix for yahoo or sfr, BTW I think it's on user side..

**Comment by kumy** [comment]
We still receive errors for user gueta, and another one using gmail. Yes I think error was originally on user side, but now they don't receive our mails anymore so no chance for them to learn their antispam. Maybe adding our from email in their address book may help.

We have the option to mark their account as `problem with mail`, they'll have an alert saying their address has problem (and we don;t try to send them new daily mails), but generally we flag account as such when the user mailbox is not active/available/existent.

I hope that with the new mail templates coming with `new-theme` their antispam will be fooled and they will receive notifications again.

**Comment by kumy** [comment]
One new occurence, eith a password recovery email for a gmail.com user.

We may start thinking of changing our smtp relay + mail address :/

**Comment by kumy** [comment]
We take some time with user livedraz, trying to instruct gmail to not place our mail as spam, but even with all our efforts, mails are discarded by the incoming server :( It really smell bad! 💩

**Comment by boly38** [comment]
did you try postmaster tool to go ahead ?
https://support.google.com/mail/answer/6227174
(I've no experience with this tool)

**Comment by kumy** [comment]
if the errors stay low for _administrative mails_, then I can manage them manually. In the meantime, I hope we can better follow the nice recommendations from the link above in the `new-theme` branch.

**Comment by Lineflyer** [comment]
@mucek4 Could this be related to the bounces we used to have to due running our own unknown mail server (some time ago) or is this completely different?

**Comment by kumy** [comment]
Note: our current smtp server is gmail.com :/ so really strange. Too much people should have moved our mail to the spam folder instead of un-subscribe :(

Not sure it is related to c:geo problem… :)

**Comment by kumy** [comment]
Seems quite stable now.
