### ISSUE TITLE
Add a new geokrety type : car

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#465]
some geocachers like to put a tb code on their cars, vehicles..
why don't let them create a geokrety code for a car.
they already have the way to create a'traditional' one but would be great to have dedicated type.

need to analyse the impact:
- icon to add ?
- procedure to re-test with this new type
- database script/comment?

**Comment by kumy** [comment]
Also, a car should not be "grabb-able". I also thought adding a "pets" type, with same constraints.

👍

**Comment by kumy** [comment]
And BTW, the parked feature would be nice to have too https://github.com/geokrety/geokrety-api/wiki/%22Parked%22-feature

**Comment by Lineflyer** [comment]
> And BTW, the parked feature would be nice to have too https://github.com/geokrety/geokrety-api/wiki/%22Parked%22-feature

Wasn't that the similar feature as the "collection" on GC we discussed some year ago?

**Comment by kumy** [comment]
@Lineflyer exactly that! We've redacted this wiki page together long time ago ;)

**Comment by GGGuerin** [comment]
Already seen at an event : tb code on a shirt ....
Why not the same for GK ?
