### ISSUE TITLE
Test note on production site?

### ISSUE THREAD

**Issue by Lineflyer** [geokrety/geokrety-website#467]
When opening https://www.geokrety.org I do see this note on the page:

Dies ist nicht die Produktwebseite. Falls du kein Tester bist, möchtest du wahrscheinlich auf unsere Produktwebseite.

When opening https://geokrety.org the note is *NOT* shown.

I think this might be unintentional?!

**Comment by kumy** [comment]
Thanks, we already have #378 for it ;) I think we'll follow what's done for cgeo, and redirect to www.geokrety.org, this will prevent cookies spreading in all subdomains. Closing here
