### ISSUE TITLE
Improve QA step for new-theme

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#473]
As geokrety-website contributor, a **new-theme** branch is still in progress, and I need a green QA step for this branch too.

Informations:
- migration details into wiki: [New-theme-migration](https://github.com/geokrety/geokrety-website/wiki/New-theme-migration)
- new-theme [GK_CDN_SERVER_URL](https://new-theme.cdn.geokrety.org) - [staging](https://new-theme.staging.geokrety.org/fr)

Todo:
- [x] **new-theme** branch working locally
- [x] add a stage that wait target environment git hash: cf #531
- [x] adapt qa scenario : cf. geokrety/geokrety-website-qa#52 (& geokrety/geokrety-website-qa#53 browserstack)

**Comment by boly38** [comment]
poke @kumy  : do you have new-theme dedicated GK_CDN_SERVER_URL ?

**Comment by boly38** [comment]
- WIP local new-theme branch :

- [ ] footer.tpl seems broken as I dont have the rest / navbar...
- [ ] find again how to clean smarty cache (no more under templates/cache ?)

**Comment by kumy** [comment]
There is a cdn for new theme, check the staging website.

We have a cli endpoint to purge cache, see the dockerfile command.

If no navbar, then there must have a php error, check generated page source

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by boly38** [comment]
following #536 merge, a build with deploy and wait has been executed: [jobs/597592039](https://travis-ci.org/geokrety/geokrety-website/jobs/597592039)

But we have got a little **1 car** issue with `git describe` result :
```
 * now waiting for 'v2.4.4-5-g7b9ff3a' from https://new-theme.staging.geokrety.org/en/app-version
2019-10-14 11:59:51 current version is: '{"version":"v2.4.4-5-g7b9ff3a6"}'
2019-10-14 11:59:52
```

**Comment by boly38** [comment]
I think we're done in a way we have a complete mechanism to improve qa step for new-theme version ; even with experimental browserstack stage which allow us to see some behavior on tablet / smartphone :D
