### ISSUE TITLE
Un-translate "Tracking Code" word

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#475]
in French the word "Tracking Code" has been translated to "Code de Suivi", as this is - in my opinion - the most right translation, we should not translate it at all. Mostly all labels in the wild use the "Tracking Code" word.

Doing so will help users to find which information to put in form field.

**Comment by claire-lovisa** [comment]
Hi! Can I take this issue ? :)

**Comment by kumy** [comment]
Sure! :)

**Comment by kumy** [comment]
Pay attention that it's related to branch 'feature/new-theme' only

**Comment by kumy** [comment]
Thanks a lot.
