### ISSUE TITLE
new-theme template must be resilient when no data

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#485]
when there is no data on some widget, smarty template should be resilient

while working on #473 on local instance of new-theme:

- `footer.tpl` seems broken as I dont have the rest / navbar...

````
Argument 1 passed to smarty_modifier_print_date() must be an instance of DateTime, null given, called in /tmp/smarty/compile/b7266d1fbbc231892001e0fe1584d1188e463762_2.file.news.tpl.php on line 64 [/var/www/html/app-templates/smarty/plugins/modifier.print_date.php:14]
````
l64 is
````
<?php echo smarty_modifier_print_date($_smarty_tpl->tpl_vars['news']->value->created_on_datetime);?>
````
smarty_modifier_print_date seems not accepting null as Date :)

update modifiers to be more resilient with no data

**Comment by kumy** [comment]
Hehe, never used website without data yet, would you make necessary PR please ?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment]
@boly38 could this be closed?

**Comment by boly38** [comment]
yep 👍
