### ISSUE TITLE
Improve DEV windows install guide

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#496]
As geokrety contributor, I would like a simple doc on how to install geokrety locally.

Goals are the following
- [x] improve `Makefile` to support [DockerForWindows ](https://docs.docker.com/docker-for-windows/) case
- [x] fix `Makefile`   `composer` target (we've got a single  file right now) 
  - [x] copy `vendor/` files onto website container
- [x] improve `Makefile` to support `phpcs`
- [x] improve `Makefile` to support `test` (phpunit)
- [x] improve Makefile to support `seed` feature (cf. #516 @kumy post)
- [x] check if `Makefile` could support travis checks: crlf,trailing-spaces, utf, phplint
- [x] make `winpty`prefix dynamic depending host OS
- [x] **remove** `gkShell/` ( [DockerToolbox](https://docs.docker.com/toolbox/toolbox_install_windows/) ) : no more supported
- [x] update INSTALL doc

branch: **feature/dockerForWindows**

**Comment by boly38** [comment]
@kumy while adding seed target, I got following feedback (I dont have time to go deeper right now)
![image](https://user-images.githubusercontent.com/3100576/66042853-edec2800-e51d-11e9-9737-0d4707d3a287.png)

**Comment by kumy** [comment]
@boly38 you need to be in `website` folder and use `../vendor/bin/phinx`

**Comment by boly38** [comment]
ok ... ;)

**Comment by boly38** [comment]
it's merged :)
