### ISSUE TITLE
Revert hiding `news` menu in navbar

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#497]
I did not thought about that before, but in this context, `$news` only exists in some pages (`home` at least). We should revert this, and add proper message in `news_list.tpl` for the case where there is no news to list.

_Originally posted by @kumy in https://github.com/geokrety/geokrety-website/pull/486/review_comment/create_

**Comment by boly38** [comment]
kumy told: _(I've already prepared a fix for it)_

**Comment by boly38** [comment]
already done by @kumy  in #498
