### ISSUE TITLE
Allow some code/markup in geokret description content

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#50]
As end-user I would like to improve GeoKret description field (ex image, colors, link+label...: simplified html)  like the geocaching cache description.

Not sure about:
* postpone to future GK portal ?
* is this improvement really needed ? (to give your opinion about this improvement add +1/-1 icon to this text)

**Comment by kumy** [comment]
Nice idea, @boly38 may you want to do it?

But be careful, it's will be an open door to many security issues.
* https://stackoverflow.com/questions/12406590/show-html-user-input-security-issue
* https://security.stackexchange.com/questions/61123/allowing-users-to-input-a-safe-subset-of-html

The less we can do is use http://htmlpurifier.org/, it seem already implemented https://github.com/geokrety/geokrety-website/blob/0d67a127a1a8706c262ac49e3dcbdd5c4cf19578/smarty_start.php#L11-L16 We should think about updating it to the current version, I'm pretty sure it is very outdated.

Things should happens here:
https://github.com/geokrety/geokrety-website/blob/0d67a127a1a8706c262ac49e3dcbdd5c4cf19578/edit.php#L574-L584
and
https://github.com/geokrety/geokrety-website/blob/0d67a127a1a8706c262ac49e3dcbdd5c4cf19578/czysc.php#L39-L54

Good luck!

**Comment by boly38** [comment]
Ok thanks for infos
As you already know I've little time window in my week to contribute to gk. so I would like first finish already assigned issue.  That's why I wont assigned more now. I'm not attached to this issue or another. What I like is to learn gk backend and append my contribution 🤣.

**Comment by kumy** [comment]
We should close this issue, and mark it somewhere in the features list for GKv2.

**Comment by kumy** [comment]
Hum, back on the subject. It seems we only purify the GET values and never the POST! Too bad :(

https://github.com/geokrety/geokrety-website/blob/0d67a127a1a8706c262ac49e3dcbdd5c4cf19578/smarty_start.php#L11-L16

**Comment by boly38** [comment]
Ok for me. do you plan a dedicated label or put this issue in another tracker? I let you mange and close. thanks

**Comment by kumy** [comment]
A wiki page here https://github.com/geokrety/geokrety-api/wiki should do the trick right now.

**Comment by kumy** [comment]
Referenced on the [wiki](https://github.com/geokrety/geokrety-api/wiki/Features). Closing here.
