### ISSUE TITLE
Add `powered by F3` logo

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#502]
Add the credit to F3 as our underlying framework. (on `halloffame` page and in README too)

Their logo are accessible there: https://github.com/bcosca/fatfree/raw/archive/f3-logos.zip

-- https://fatfreeframework.com/3.6/development#SomemoreGoodies

**Comment by Ananthavijay** [comment]
I will take up this issue

**Comment by error401de** [comment]
I'll take this

**Comment by kumy** [comment]
Thanks @error401de
