### ISSUE TITLE
hallOfFame > smarty  > undefined index kumy

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#516]
while rendering [hall_of_fame.tpl.php:70] I ve got this issue

Undefined index: kumy

**Comment by boly38** [comment]
Seems loaded from db by HallOfFame controller

**Comment by kumy** [comment]
@boly38 this commit may help you https://github.com/geokrety/geokrety-website/commit/e39331d48d64bb9b63bae78549debb59d4d07fbe

use `cd website; ../vendor/bin/phinx seed:run`

**Comment by boly38** [comment]
I like the seed feature :) on another task, I will add Makefile target
BTW I think userlink call should be fixed to avoid !isset exception. I've a fix for that point.
