### ISSUE TITLE
Add a stage that wait target environment git hash

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#531]
Subtask of #473 : we need aditionnal travis stage that wait auto deploy result in order to start qa tests bependend build if and only if target environment is up and running 

Task to do:
- add a way to retriave current application version : new endpoint `/app-version`
- add a sample stage that wait for a given version on a given target environement

toBeDiscuss: somewhere: a version prefix is added to git commit hash, this must be managed too.

**Comment by kumy** [comment]
> add a way to retriave current application version : new endpoint `/app-version`

This should be fairly easy, it is stored in constant `GK_APP_VERSION`. `/app-version` is good idea, it should return values in a machine readable format ; json is perfect!

**Comment by boly38** [comment]
> it should return values in a machine readable format ; json is perfect!
I need to do that ; and so using `jq` on client side to parse result

**Comment by boly38** [comment]
following #536 merge, a build with deploy and wait has been executed: [jobs/597592039](https://travis-ci.org/geokrety/geokrety-website/jobs/597592039)

But we have got a little **1 car** issue with `git describe` result :
```
 * now waiting for 'v2.4.4-5-g7b9ff3a' from https://new-theme.staging.geokrety.org/en/app-version
2019-10-14 11:59:51 current version is: '{"version":"v2.4.4-5-g7b9ff3a6"}'
2019-10-14 11:59:52
```

**Comment by boly38** [comment]
With this fix, we expected a green build right [here](https://travis-ci.org/geokrety/geokrety-website/builds/598096244?utm_source=github_status&utm_medium=notification)

**Comment by boly38** [comment]
failed, we've  9 chars hash on the endpoint side, 
wherease travis script expected value is 8 chars hash

**Comment by boly38** [comment]
right [now](https://travis-ci.org/geokrety/geokrety-website/builds/598101806?utm_source=github_status&utm_medium=notification)
