### ISSUE TITLE
GK not shown on some gc.su  pages

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#551]
From support mail:

---

Good day!
I noticed that geokrets are not marked on this page in this cache on our site. On other pages in our site of hiding places everything was worked correctly.
Screenshot is attached
Links is
Work is correct
https://geocaching.su/?pn=101&cid=1746
Work is not correct
https://geocaching.su/?pn=101&cid=5491
[…]
 Best regards V

![Bag without geokret](https://user-images.githubusercontent.com/176794/69573136-d5e8d000-0fc5-11ea-8c6e-989ff8381d0f.png)
![Normal](https://user-images.githubusercontent.com/176794/69573137-d5e8d000-0fc5-11ea-9df2-7e1bfc1ccc7f.png)

**Comment by kumy** [comment]
I have absolutely no idea how gc.su is synchronizing GK database to display them on their website. @okainov any clue?

**Comment by okainov** [comment]
Yeah, I think there was some issues on our side, now it should be better. We use `https://geokrety.org/export_oc.php?modifiedsince=%s`  for incremental updates (~every 4 hours) and `https://api.geokrety.org/basex/export/geokrety.xml` for full updates (~weekly)

**Comment by kumy** [comment]
Let's close then
