### ISSUE TITLE
new-theme - my profile - geokrety near home map

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#552]
- I'm logged, 
- I clic on `My profile` page,
![image](https://user-images.githubusercontent.com/3100576/69828802-9fa58d80-121d-11ea-8bd9-43ca7f5f74e8.png)

- then I got a map view at bottom right called `GeoKrety near home`.
![image](https://user-images.githubusercontent.com/3100576/69828794-974d5280-121d-11ea-88d2-c7f074f74f95.png)

I see map Point of interest(PoI) icon, I can zoom in, and zoom out.

But when I clic on a PoI there is no effect: I can't see the name of the geokrety or a link to that geokrety.

I think this view is not major feature, and maybe we could hide this widget until it's fully implemented. 
Another simple intermediate solution could be to add a link to the `/map` view at home coordinate.

**Comment by kumy** [comment]
Latest minimap looks like this.
![Screenshot from 2020-11-14 14-11-34](https://user-images.githubusercontent.com/176794/99147871-8b53de00-2684-11eb-8511-c31b8d7baa54.png)![Screenshot from 2020-11-14 14-19-17](https://user-images.githubusercontent.com/176794/99147870-8abb4780-2684-11eb-8fd8-954d66d55e47.png)

Popup template is located at `website/app-templates/smarty/js/users/geokrety_near_home_map.tpl.js` if you wish to enhance it :smile:
