### ISSUE TITLE
new-theme - not english 'move' page - "tracking code" reference

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#553]
Following #475 I think keeping `Tracking code` is an excellent point.

This avoid user confusion about which "code" to input: we should refer at a same label everywhere : website, and geokrety label (and maybe mobile app..)

To fix this issue, 
- for other than english langage, add `Tracking code` label in `move` page first widget.

english example
![image](https://user-images.githubusercontent.com/3100576/69829361-f1e7ae00-121f-11ea-9ea9-df7fd8dc99d2.png)

french example
![image](https://user-images.githubusercontent.com/3100576/69829375-00ce6080-1220-11ea-8739-d9b86df1c88e.png)

**Comment by kumy** [comment]
Done on crowdin
