### ISSUE TITLE
Norwegian missing from languages list?

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#559]
User Trond recently translated most of the strings in Norwegian, I don't find this language in our language selector. Are we missing something?

**Comment by kumy** [comment]
I have a problem here, what is the correct locale we should apply here? The crowdin system is activated for `Norwegian` and export files for this language in subdirectory `no`, which seems not be recognized by `gettext`.

Locale helper https://lh.2xlibre.net/locale/se_NO/ indicate `se_NO` as the valid locale, with name `Northern Sami`.
I can see in crowdin this language, I'm afraid that we made a misconfiguration there the first time.
![Screenshot from 2020-02-12 22-38-33](https://user-images.githubusercontent.com/176794/74380049-2283c080-4de9-11ea-9fd9-a716707cce23.png)

I'll enable `Northern Sami` on crowdin and I expect it to copy all the translated strings there!

It' would be nice if someone could validate my findings.

**Comment by kumy** [comment]
Ok, `Northern Sami` created on crowdin, and strings copied from `Norwegian`. I hope that's ok. I'll wait a bit for a confirmation, before proceed further.

**Comment by jcmypal** [comment]
What do i need to do? Northern Sami is an own language, that used by Norwegian/swedish/Finnish natives. They use this language, and its a language that is different from Norwegian. The sami natives talk sami over borders, but i Norway we all (also norwegian sami´s) understand norwegian.
Norwegian is also in 2 types, but we don't use this on geokrety i think, because the common norwegian "bokmal" is the most used, and the common in Norway.

Trond

**Comment by kumy** [comment]
Here is what enabled now, @jcmypal is it what you expected?
![Screenshot from 2020-11-14 16-30-26](https://user-images.githubusercontent.com/176794/99150728-e5f63580-2696-11eb-930e-b5b43d3ad93c.png)

**Comment by jcmypal** [comment]
Hmmm, maybe i have contacted wrong place, i have byen involved i translating opencaching. Im very sorry that the mail was direkte to the wrong place. And also thank you, for messeng me, i shall make a New post, to the responsible for opencaching.I see that you have the translation.ReparasjonJcmypalSendt fra min Galaxy
-------- Opprinnelig melding --------Fra: kumy <notifications@github.com> Dato: 14.11.2020  16:33  (GMT+01:00) Til: geokrety/geokrety-website <geokrety-website@noreply.github.com> Ko: jcmypal <trond.bygderadio@gmail.com>, Mention <mention@noreply.github.com> Emne: Re: [geokrety/geokrety-website] Norwegian missing from languages list? (#559) 
Here is what enabled now, @jcmypal is it what you expected?

**Comment by kumy** [comment]
Hi @jcmypal, if you also would like to contribute to GeoKrety translation, you are more than welcome here :+1: 
If you wanna check how it looks like, please check our staging environment https://new-theme.staging.geokrety.org/en
Bests
