### ISSUE TITLE
Announcing changes to Google Maps JavaScript API v2

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#565]
From support mail:

![Screenshot from 2020-06-05 10-00-44](https://user-images.githubusercontent.com/176794/83852016-722d2580-a713-11ea-9be4-6fbbb4329a5a.png)

**Comment by andrixnet** [comment]
Perhaps migrate to smth like Leaf, etc? 

there is also the problem with the MAP API and data access for which Google require payment (beyond a certain free usage) ... 

At OC we changed the API entirely and map sources.

**Comment by kumy** [comment]
On `new-theme` branch we already migrated to leaflet and OSM layers :)
