### ISSUE TITLE
Add possibility to preselect log type on ruchy page

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#567]
Somehow similar to #566

It would be great to be able to preselect logtype i.e. https://geokrety.org/ruchy.php?waypoint=TR25&logtype=1 

Reasoning - we'd like to add a button to the cache page at geocaching.su like "log a geokret in this cache" and it would be useful to be able to pre-select waypoint and type of the log (which is typically "drop")

**Comment by kumy** [comment]
This is now implemented on branch `new_theme`, sorry I will not implement it for master branch.

It will be (when code deployed to this staging environment):
https://new-theme.staging.geokrety.org/en/moves?tracking_code=8S8WUG&waypoint=GC5BRQK&move_type=0&coordinates=44.31207%204.7067
