### ISSUE TITLE
Cannot delete Geokret image

### ISSUE THREAD

**Issue by Lineflyer** [geokrety/geokrety-website#574]
- Open an owned GeoKret (in my case GKFC75)
- Select the red x for one of the attached pictures
- Confirm the following dialog with OK
- An empty page is shown for https://geokrety.org/edit.php?delete_obrazek=51608&confirmed=1
- Return to the GeoKret page

Result:
- Picture still shown

Expected:
- Result screen should show the result
- Picture removed

**Comment by kumy** [comment]
According to the current implementation, this is "normal". This GeoKret (and the others from the series - c:geo contribution award), have only one picture (same file) attached to multiple GK and to prevent deletion of "all" images, the delete is blocked. I agree that a message would have been displayed explaining the case :/

As I don't plan to update the legacy website version anymore, @Lineflyer I propose to manually update the database from this case, is it ok for you?

TODO: check how will the new website handle this, so I'll let the issue open.

**Comment by Lineflyer** [comment]
That was a fast reaction :)

Indeed for this special case it would be nice if you could just replace the old logo with the new logo for the whole set of award coins (although the coin itself is the old logo).

Optional:
If you could imagine, that such feature for a set of TBs might be used for other people in future as well, you might think about introducing an appropriate error message.

**Comment by kumy** [comment]
> Indeed for this special case it would be nice if you could just replace the old logo with the new logo for the whole set of award coins (although the coin itself is the old logo).

I'll do.

> If you could imagine, that such feature for a set of TBs might be used for other people in future as well, you might think about introducing an appropriate error message.

Honestly, internals in legacy is really messy, no unit test, I'm really afraid of breaking something. But for sure, I'll do something better for branch `new-theme`.

**Comment by kumy** [comment]
I've checked the new-theme branch: not edit/delete button is available for such pictures. I don't really like that, and will work on that later.

**Comment by kumy** [comment]
Done, all pictures updated.
