### ISSUE TITLE
Cannot edit existing GeoKret image

### ISSUE THREAD

**Issue by Lineflyer** [geokrety/geokrety-website#575]
- Open one of my owned GeoKret (in my case GKFC75)
- Select the pencil icon next to an existing image

Result:
Does only happen for one (older) image, but not for another (newer) image:
A page with exclamation mark sign and text "Error #12012110" is shown

**Comment by kumy** [comment]
Same problem as #574.

**Comment by kumy** [comment]
TODO: check on branch new-theme
