### ISSUE TITLE
Print multiple labels per page

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#581]
Follows #356.
The actual code permit on `new-theme` has the necessary bit of code to permit generating pdf pages containing multiple labels.

But it's still need a way to let users select which GK to place on pages.

**Comment by GGGuerin** [comment]
quite useful

**Comment by kumy** [comment]
Yes, that will be a nice feature, but it'll come come later. I have to be features equal (which takes a lot of time) then I'll add new features. So sorry don;t expect it "soon"

**Comment by kumy** [comment]
![image](https://user-images.githubusercontent.com/176794/162575523-ede3005a-d819-41f8-8484-9930bd6f1196.png)
![image](https://user-images.githubusercontent.com/176794/162576126-375b4746-2093-43f2-88db-dbd7a73b563e.png)

(In a later time, it will be nice to have metadata on label templates, so we can rearrange the label disposition to better use the page)
