### ISSUE TITLE
Add map "where are my GKs?"

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#589]
Just saw somewhere there was a service providing map with current location of all one's owned GKs. Feels like relatively simple but useful feature (especially for ones who have a lot of GKs) and worth implementing it in the GK website itself

**Comment by kumy** [comment]
You were probably thinking about https://geokretymap.org (a service I've developed before my geokrety.org take over)?

The current website ha**d** such map but it's currently broken. https://geokrety.org/mapka_kretow.php?userid=26422

The GK-NG has this feature already implemented https://new-theme.staging.geokrety.org/fr/users/26422/owned-geokrety/map

I'll tend to close this issue…

**Comment by okainov** [comment]
Okay, if it's already implemented, then it's cool, we can close indeed :)

But one note - link from profile popup goes to *all* GK map, not to my GK map :)

![image](https://user-images.githubusercontent.com/918446/101802641-ba912a00-3b20-11eb-8d62-105bb5683513.png)

**Comment by kumy** [comment]
Good catch, I'll fix the link.
