### ISSUE TITLE
Gc.su sync issues?

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#592]
Seems like there is some synchronization issue with gc.su :( GK reports TR25212 as "invalid", but it's for sure valid...
https://geocaching.su/?pn=101&cid=25212

Was it missed somehow during sync? Isn't there full database resync from time to time,

**Comment by kumy** [comment]
Automatic full re-sync, is not implemented (yet). I've launched the full re-import manually. This waypoint is now in database.
