### ISSUE TITLE
No flag

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#594]
![Issue 2 GGG](https://user-images.githubusercontent.com/77342426/104443279-88973b80-5596-11eb-958d-06ca5eccb8aa.jpg)
No flag country affected. It should be the french one.

**Comment by kumy** [comment]
Link to #593

**Comment by kumy** [comment]
Flag appeared, I remember to have seen a "missing country garbage collector" in cron scripts.
https://github.com/geokrety/geokrety-scripts/blob/master/geokrety-crontab#L38

It's executed every 10 minutes, don't know why it stayed "unknown" more than that. I'll close this issue, feel free to reopen later if it appear again…

![Screenshot from 2021-03-16 19-42-36](https://user-images.githubusercontent.com/176794/111363012-cb0cef80-868f-11eb-9d14-73c9bc77e97e.png)
