### ISSUE TITLE
Statistics display

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#595]
![GGG 3 error](https://user-images.githubusercontent.com/77342426/104916919-ff677680-5992-11eb-8a78-4324d4e4a592.jpg)
Troubleshooting in the display of statistics

**Comment by kumy** [comment]
Thanks for your report. The problem doesn't seems to affect all GeoKrety, for example this one is working https://geokrety.org/stat_timeline.php?gk=63781 Seems to be some specific logic issue related to the movements sequence?? in the code https://github.com/geokrety/geokrety-website/blob/master/website/stat_timeline.php

On another hand, the statistics were not yet ported to the new website, I think I'll go deeper in this while working on this part later

**Comment by kumy** [comment]
Link to #354

**Comment by kumy** [comment]
I was lucky on my first tries, as I found the two that were working :laughing:  But I agree there are many broken stats :disappointed:
