### ISSUE TITLE
Map for lost geokrets

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#598]
![GGG 5 issue](https://user-images.githubusercontent.com/77342426/105746289-89897f00-5f3f-11eb-8ce0-1d6742cbb2d5.jpg)
Not possible to display the map for lost geokrets
Remark : strange to find this feature in the statistics tab ....it could be maybe better to put this feature in side products

**Comment by kumy** [comment]
CSP issue should be fixed (when properly deployed on prod), but it will fail soon as google will disable this api soon. We could/should migrate to `leaflet` and OSM background, but I don't think it will be implemented on the old website.

**Comment by kumy** [comment]
Half working, but this one will be closed like this. Sorry.
![Screenshot from 2021-01-25 19-33-48](https://user-images.githubusercontent.com/176794/105749857-4382ea00-5f44-11eb-95cb-3274fc05d7ab.png)
