### ISSUE TITLE
GK visiting a cache

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#599]
![GGG 6 issue](https://user-images.githubusercontent.com/77342426/105747249-d588f380-5f40-11eb-9e6a-edb069fee9f2.jpg)
There is a GK in this cache .... but it is not displayed ....

**Comment by kumy** [comment]
@GGGuerin Could you please tell me which GK you expect to be present? Thanks

**Comment by GGGuerin** [comment]
GK13E4B

**Comment by kumy** [comment]
You have spaces pasted in the search box (I see that in the URL the `+ +`)

This works fine https://geokrety.org/szukaj.php?wpt=GC8AH2N

We may trim spaces from the field - easy to implement and not too risky ;)

**Comment by kumy** [comment]
Let's test on staging first https://staging.geokrety.org/, then I'll deploy to prod

**Comment by GGGuerin** [comment]
Apologize for this false issue ....

**Comment by kumy** [comment]
> Apologize for this false issue ....

Not really ;) Thnigs can always get better. Here it's should be a really simple - non intrusive - fix, so I'll try to fix it, as said many time, I generally prefer to not touch the legacy code to not break it.

**Comment by kumy** [comment]
Tested on staging -> ok. It's currently being deployed to prod.
