### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#601]
It seems that there is no new badge since 2019

**Comment by kumy** [comment]
That's (unfortunately) still a tedious task.
I've started the badge distribution for the last two years :smile: 

@GGuerin you're ranked `#52` in 2019 and `#27` in 2020 :wink:

**Comment by kumy** [comment]
I would like -some day- to change the rules, or create new badge attributions. As of today, it count dips/drops. I would like to add a notion of drops-only and/or `someone else` only moved GK. But it's not for 2020, I hope 2021 if my time and motivation permits ;)

**Comment by GGGuerin** [comment]
I thought that it could be funny to get badges for countries visited by GKs...
Why not for counties (departments or regions in France for example ....)

**Comment by kumy** [comment]
Yes, that could be nice ideas, we have to think "world wide" so I have doubts for regions in France ;)

**Comment by kumy** [comment]
Yes, I like those ideas, but as I say every time, my first goal is to finish 1 to 1 features on the new website version (aka [`new-theme`](https://new-theme.staging.geokrety.org/))

I've started a wiki page about [new badges ideas](https://github.com/geokrety/geokrety-website/wiki/Badges-ideas), @GGGuerin are you able to edit the page to add all your great ideas?

**Comment by kumy** [comment]
TODO:

- [ ]  Add news on website

**Comment by kumy** [comment]
I have an `Edit` button that you probably don't see :/

![2021-03-09_18-16](https://user-images.githubusercontent.com/176794/110510597-a77ffd00-8103-11eb-86ca-8f836262a22b.png)

**Comment by GGGuerin** [comment]
> 
> 
> I have an `Edit` button that you probably don't see :/
> 
> ![2021-03-09_18-16](https://user-images.githubusercontent.com/176794/110510597-a77ffd00-8103-11eb-86ca-8f836262a22b.png)

Actually i do not have neither Edit nor New Page

**Comment by kumy** [comment]
I have created a new group, and assigned it `triage` rights, I hope it's sufficient to edit wiki other than managing issues ;)

**Comment by GGGuerin** [comment]
> 
> 
> I have created a new group, and assigned it `triage` rights, I hope it's sufficient to edit wiki other than managing issues ;)
> @GGGuerin you should have received an invite

Not yet .... :-(

**Comment by kumy** [comment]
My fault, I missed a `G` in your username :).

BTW, news has been posted, let's close.
