### ISSUE TITLE
Mismatch between maps

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#603]
If one looks a the same place with GK map at https://new-theme.staging.geokrety.org/fr/geokrety/map or https://geokretymap.org/geokrety-world-map/#10/43.12/6.096/0/1/0/0/45/   , there is almost no match between the two maps ....
![image](https://user-images.githubusercontent.com/77342426/111295765-0980bb00-864c-11eb-8725-fa51c7d799b5.png)
![image](https://user-images.githubusercontent.com/77342426/111295794-13a2b980-864c-11eb-805e-5afe28fb08a3.png)

**Comment by kumy** [comment]
interesting… :thinking:

**Comment by kumy** [comment]
Ok, that was the `materialized view` which was not refreshed after bulk daily imports. I have manually triggered it, and It should also be fine for tomorrow import at ~12h.

Comparison between two maps is not really easy as both shows GK based on different last move time.

**GKM**
- show by default GK moved in the last 45 days, to 90days, after 90days there is no granularity. (see the option panel on the right of the map)

**GKv2** (`new-theme`)
- show GK moved in the last 730days, but if the coverage area (user zoom out) is > 150000 km2 then time frame is reduced to 365days.
