### ISSUE TITLE
Favorite GK

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#604]
In the new theme, i do not find the good GKs for my favorite ones.
![image](https://user-images.githubusercontent.com/77342426/111296933-5add7a00-864d-11eb-9441-4a3052633038.png)
![image](https://user-images.githubusercontent.com/77342426/111296977-64ff7880-864d-11eb-8446-61dc12ab4603.png)

**Comment by kumy** [comment]
That's clearly an import bug! Nice find!!

**Comment by kumy** [comment]
manually launched the update. Should also be fixed in tomorrow import. Please check again ~12h CET

**Comment by kumy** [comment]
Just checked, today's import is fine

**Comment by GGGuerin** [comment]
Just checked today .... and import is not good ....
![image](https://user-images.githubusercontent.com/77342426/111598467-8be5b800-87cf-11eb-85d8-32a9811714ea.png)

**Comment by kumy** [comment]
Please check at 12h and report again.. Database is not coherent *during* import.

**Comment by GGGuerin** [comment]
> 
> Please check at 12h and report again.. Database is not coherent *during* import.

It seems to be good right now ....
