### ISSUE TITLE
Users GK lists cannot be ordered

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#605]
It is not possible to display in determined order such as increasing distance, number of moves .... I do not see what is the order used to sort the GKs ...
![image](https://user-images.githubusercontent.com/77342426/111326673-0a761480-866d-11eb-97d6-164007cddb4d.png)

**Comment by GGGuerin** [comment]
For example, it is not possible to display in function of indreasing GK ids.

**Comment by kumy** [comment]
Ok, understood.

**Comment by kumy** [comment]
Should be fixed in tomorrow import. Please check again ~12h CET

**Comment by kumy** [comment]
That's also the case with other pages:
- inventory
- owned
- watched
- recent moves
- etc…

**Comment by kumy** [comment]
BTW, the default sorting method is 'last GK update'.

Nothing has been implemented yet to allow different sorting.
