### ISSUE TITLE
Kumy's signature expired

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#606]
Probably you want to update your GPG key  @kumy  :)

![image](https://user-images.githubusercontent.com/918446/111369039-dd3e5c00-8696-11eb-82c7-8d3f8f59c406.png)

**Comment by kumy** [comment]
I have edited my key many month ago and pushed it to [keyserver](https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0xc06ee20f74df3848).  I thought that was enough :), I didn't even notice that info on github…

I searched a bit how to force github to refresh my key, and found a [documentation](https://docs.github.com/en/enterprise-server@2.22/github/authenticating-to-github/updating-an-expired-gpg-key) about it (but for github enterprise - I hope it work the same on github oss).

So I just deleted and re-uploaded my key to github, but problem remains.

![2021-03-16_21-51](https://user-images.githubusercontent.com/176794/111378264-e254d880-86a1-11eb-98fc-9c0d432657a8.png)

@okainov any idea?

**Comment by kumy** [comment]
The same [doc](https://docs.github.com/en/github/authenticating-to-github/updating-an-expired-gpg-key) for normal github. So procedure should be fine. Let's wait a bit, there may be some cache running on their side.

**Comment by okainov** [comment]
I'm not a big expert in these signing things :( For myself I think I have non-expiring key and never really saw anything like that....

**Comment by okainov** [comment]
BTW now the message has changed!

![image](https://user-images.githubusercontent.com/918446/111432981-fd553600-86fd-11eb-8cc4-ad9c65c7d7f7.png)

**Comment by kumy** [comment]
Can't remember why my key didn't had the right email in it, maybe the restored file after a reinstall was not up to date??

However, edited my key to add my github mail address, and installed it again in github. Message changed instantaneously.

@okainov thanks for notifying me about this :)
