### ISSUE TITLE
GK details miss `Country Track`

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#608]
In the new theme, there is no more country track as in the current one

**Comment by kumy** [comment]
![image](https://user-images.githubusercontent.com/176794/196029271-4986ecd5-7be2-4bbd-80b3-9267a2385c63.png)
(second french flag is for "réunion", so not a bug)

![image](https://user-images.githubusercontent.com/176794/196029281-91e3c65c-5a82-4515-8fb3-4c3a82b370f1.png)
