### ISSUE TITLE
Archive icon

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#609]
![image](https://user-images.githubusercontent.com/77342426/111461682-cc84f900-871d-11eb-9524-4719787a7c6e.png)

In the new theme, there is no difference between archived and in motion GKs in terms of icon

**Comment by kumy** [comment]
Issue should be in this smarty custom plugin: https://github.com/geokrety/geokrety-website/blob/feature/new-theme/website/app-templates/smarty/plugins/modifier.posicon.php

**Comment by kumy** [comment]
1 line fix, 15 lines of unit tests :laughing: …unit testing joys :wink:
