### ISSUE TITLE
Migrate waypoints imports to new-theme

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#615]
The automated process to synchronize waypoints from external websites has to be ported to `new-theme`

legacy scripts : https://github.com/geokrety/geokrety-scripts/tree/master/waypointy

- [x] gc.su (`VT*`, `EV*`, `MV*`, `LV*`, `CT*`, `TR*`, `MS*`, `LT*`, `VI*`)
- [x] oc.pl
- [x] oc.de
- [x] oc.uk
- [x] oc.us
- [x] oc.nl
- [x] oc.ro
- [x] gc.hu (`GC*`)
- [ ] geotrekking.plus.ro (`GR*`) - Export API broken, mail sent to owner
- [ ] http://www.rejtekhely.ro (`RH*`) - Export API broken, mail sent to owner
- [ ] ~geocahing.com~ (Not allowed to sync)
- [x] geodashing (`GDFI-*`)
- [x] gpsgames (`GE*`) - Can only access the last 200 caches :( - mail to owner sent
- [ ] ~opencaching.com~ - Site is down
- [ ] ~oc.cz~ - Old xmlapi - not working
- [x] wpg (`WPG*`)

**Comment by okainov** [comment]
I can take at least `gc.su` part, probably just need some template how do you see it in `new-theme`. Also we're flexible to change our endpoint if needed (e.g. return JSON instead of XML)

**Comment by kumy** [comment]
Nothing has been started yet, I'll try to initiate something soon about this.

**Comment by kumy** [comment]
@okainov Are there any "cache type" on gc.su caches?

The export page actually return data as:
https://geocaching.su/rss/geokrety/api.php?interval=3h&changed=1
```xml
<?php xml version="1.0" encoding="utf-8"?>
<data>
  <cache id="16831">
  <code>TR16831</code>
  <autor>Кочевники</autor>
  <name>79 дней</name>
  <position lat="54.5038333" lon="36.2258667"/>
  <cdate>2015-02-01 00:00:00</cdate>
</cache>
[…]
```

If there is one, could you add it to your exports please?

Also, is it possible add the cache status? On OKAPI we check for statuses:
- `Available` (`1`)
- `Temporarily unavailable` (`2`)
- `Archived` (`3`)
- All other types are considered as `0` (unknown?)

Thanks

BTW: There seems to be a typo on element `autor`, shouldn't it be `author`?

**Comment by okainov** [comment]
>Are there any "cache type" on gc.su caches?

Yep. Traditional, Multi, Virtual, Multi-Virtual, Mystery, Virtual Mystery and events and contests. It's implicitly encoded in geocode, as such:
- TR == Traditional
- MS - Multi
- VI - Virtual
- MV - Multi-Victual
- LT - Mystery ("logical")
- LV - Virtual Mystery

How do you want to get it, any preferences? I can send two-letter abbreviation, or our internal id (some integer from 1 to 10), or something else if you need. Or you can just parse it on your side.

>Also, is it possible add the cache status? On OKAPI we check for statuses:

We have more complex system, so currently this endpoint returns only "active" caches (not archived), but there is "subtype" which is "1" = Available, "2" - "presumably unavailable", "3" - "unavailable".
And "unavailable" is not "archived", it's like... hmmm... when people can still see the cache on the map, but it needs restoration. If noone saves the cache in some months/years, then it will go to archive.

I've added subtype to endpoint, let me know if you need also archived caches... Is it for marking GKs as missing if they're in archived caches?

>BTW: There seems to be a typo on element autor, shouldn't it be author?

Backward compatibility :D I've added proper field, let me know when update is completed so I can remove the one with typo.

**Comment by kumy** [comment]
@okainov 

> there is "subtype" which is "1" = Available, "2" - "presumably unavailable", "3" - "unavailable".

The idea behind is to display a warning if some user try to log in those cache see #438. 
I've mapped as :
* 1 -> 2
* 2 -> 2
* 3 -> 6

> let me know if you need also archived caches...

Regarding archived caches, yes that would be fine, so we can prevent logging there, and compute lost GKs

**Comment by kumy** [comment]
> > BTW: There seems to be a typo on element autor, shouldn't it be author?

> Backward compatibility :D I've added proper field, let me know when update is completed so I can remove the one with typo.

That should be ok on legacy scripts and GKv2 one. @okainov you can clear the old field if no one else use it :) :+1:

**Comment by okainov** [comment]
>1 -> 2
2 -> 2

Shouldn't it be 1 then?  From #438 I see that "1" is "Active". At least our subtype=1 is for sure "1" as "Active".

>Regarding archived caches, yes that would be fine, so we can prevent logging there, and compute lost GKs

Okay, I've added `status` as well, be aware that it can have some "soft deleted" caches. Basically in gc.su we treat `status==1` as "good, in game" and any other status is some random state of "archive" of different kinds (such as "drafts", "pre-moderation", "removed", "archived" and so on, around 7 different statuses in total).

>That should be ok on legacy scripts and GKv2 one. @okainov you can clear the old field if no one else use it :) 👍

Done, removed. Deploying now, should land in ~10 min.

**Comment by kumy** [comment]
So gc.su status `"2" - "presumably unavailable"` should be mapped to OC status `2 -> temporarily disabled`?

I'll check the new `status` field. Thanks

**Comment by kumy** [comment]
@okainov Do you agree with such function?

```php

    /**
     * Convert gc.su statuses to oc statuses
     *
     * @param string $status gc.su cache status
     * @param string $subtype gc.su cache subtype
     * @return int|null The cache status
     */
    private function status_to_id(string $status, string $subtype): ?int {
        if ($status !== '1') {
            // Cache is not in `good status`
            return 3; // archived
        }
        switch ($subtype) {
            case '1': // Available
            case '2': // presumably unavailable
                return 1; // active
            case '3': // unavailable
                return 3; // archived
            default:
                return null;
        }
    }
```

**Comment by okainov** [comment]
>        switch ($subtype) {
            case '1': // Available
            case '2': // presumably unavailable
                return 1; // active
            case '3': // unavailable
                return 3; // archived
            default:
                return null;
        }

I'd probably suggest something like
```
        switch ($subtype) {
            case '1': // Available
                return 1; // active
            case '2': // presumably unavailable
                return 2; //  temporarily disabled // Here I don't know. It can be either 1 or 2, probably depends how strict you want to restrict users there. If it will just print warning like "It seems this cache might be missing, are you sure?", but still allow to proceed - 2 is good enough. But if you really restrict putting GK in such caches, then it's better to put 1 instead, because "presumably unavailable" MAY be apparently available.
            case '3': // unavailable
                return 2; // Temporary disabled   <--- Here
            default:
                return null;
        }
```

**Comment by kumy** [comment]
OK, thanks. Let's start with
```php
        switch ($subtype) {
            case '1': // Available
                return 1; // active
            case '2': // presumably unavailable
            case '3': // unavailable
                return 2; // temporarily disabled
            default:
                return null;
        }
```

**Comment by kumy** [comment]
So I think we're good :

- [ ] Synchronize "still working websites" (ex: oc.com is now down)
- [ ] Launched via cron
- [ ] Locking system while updating - no cron overlap
- [ ] Public statistic page
- [ ] Admin mail alert on locked script since too long time
- [ ] Admin alert on synchronization error
- [ ] Error counting on stat page
- [ ] Last  error text on stat page - hiding secret keys

![Screenshot from 2021-03-30 21-35-21](https://user-images.githubusercontent.com/176794/113046386-4dbda080-91a0-11eb-9095-6b215cdae8ce.png)

![Screenshot from 2021-03-30 21-43-08](https://user-images.githubusercontent.com/176794/113046923-f1a74c00-91a0-11eb-8446-0cac561ae7ed.png)

(OC_DE is missing, full export return error `"No fulldump found. Try again later. If this doesn't help contact site administrator and/or OKAPI developers."`, I don't know if it's a problem with my key (request limit) or some thing else. It's failing since at least 2 days - so maybe a problem on their side…)
![Screenshot from 2021-03-30 21-44-38](https://user-images.githubusercontent.com/176794/113047099-2915f880-91a1-11eb-8f92-36a01cb0a725.png)
