### ISSUE TITLE
Allow users to change their username

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#617]
We often receive requests to change usernames. On GKv1 it was an admin feature. We should allow users to be autonomous on that point.

- [x] The new username must not be used (either in actual users tables or pending one)
- [x] Account has to be in `valid` state
- [x] ~~A confirmation email should be sent with a validation link~~
- [x] Once changed, a final confirmation mail should be sent
- [ ] ~~Requesting a new username while a first request has not been validated yet will cancel the first one automatically~~
- [x] Once validated, the old username become automatically available
- [ ] ~~Pending username will be automatically cancelled (how long 15min? 1h? 1d?) - should we send cancel informational mail~~
- [x] Process must have proper `qa-tests`
- [x] Store username history somewhere - we could display it later on the website

Note: This may require a database schema change to store pending usernames

**Comment by okainov** [comment]
> A confirmation email should be sent with a validation link

Sounds like too much, don't you think so? The website should allow login by email and just changing login shouldn't really affect anything...

> Once validated, the old username become automatically available
It would be nice feature to keep the history, like on user page maybe show "Previously known as `old-nickname`". It should not prevent others to take old nickname though, here I agree.

Also I'm not sure whether you thought of having feature like "@mention", if yes, those also have to be updated.

**Comment by kumy** [comment]
> The website should allow login by email 

That feature has already added to GKv2 (it didn't existed in GKv1)


> > A confirmation email should be sent with a validation link
> Sounds like too much, don't you think so?

That's not "easy" to implement, but I think it's important in security terms… That's my opinion :)

> It would be nice feature to keep the history

Yeah, why not, didn't thought it was useful… Not sure everyone want such "history". As an example, I had many time support mail because some users used their email address as nickname, and this info is public. If we choose to do that, then users should be able to drop single entries.

> Also I'm not sure whether you thought of having feature like "@mention", if yes, those also have to be updated.

Hum never thought about this, please open a dedicated issue for that so we'll not forget the idea.

**Comment by kumy** [comment]
I've added the "keep username history" to the do at the top of this issue.

**Comment by kumy** [comment]
> > A confirmation email should be sent with a validation link
> > Sounds like too much, don't you think so?
> That's not "easy" to implement, but I think it's important in security terms… That's my opinion :)

Reconsidering this, let's ignore that at the moment…
