### ISSUE TITLE
User avatar is not good in new-theme

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#619]
![Avatar](https://user-images.githubusercontent.com/77342426/111763633-aa68b380-88a2-11eb-8432-a42511f58a87.jpg)
In place of the avatar, there is a kind of star or snow flake ....

**Comment by kumy** [comment]
That's an import problem, I will check what's wrong there…

**Comment by kumy** [comment]
Fixed. To be checked again after tomorrow import at ~12h CET

**Comment by GGGuerin** [comment]
it seems OK for me !
