### ISSUE TITLE
Wrong GK in Last move tab

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#620]
![image](https://user-images.githubusercontent.com/77342426/111765436-9faf1e00-88a4-11eb-8ff1-c239d670d0b6.png)
it is not one of my Gks nor one that I have in my inventory.

**Comment by GGGuerin** [comment]
![image](https://user-images.githubusercontent.com/77342426/111771859-772b2200-88ac-11eb-8702-a739bea2abc7.png)
OK right now ???

**Comment by kumy** [comment]
That the inconsistent database state between 10h10 CET - 12h00 CET. Please do not check such database concistency during that period of time.
