### ISSUE TITLE
No watched GK in new theme

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#621]
![image](https://user-images.githubusercontent.com/77342426/111765868-2a901880-88a5-11eb-8144-8c8a8144b697.png)

![image](https://user-images.githubusercontent.com/77342426/111766078-64611f00-88a5-11eb-8ece-d5fdf42d17dd.png)

**Comment by GGGuerin** [comment]
![image](https://user-images.githubusercontent.com/77342426/111772017-ab064780-88ac-11eb-9409-81a6ebcfc7bf.png)
OK right now ....

**Comment by kumy** [comment]
Same as #619 

> That the inconsistent database state between 10h10 CET - 12h00 CET. Please do not check such database concistency during that period of time.
