### ISSUE TITLE
Altitude picture in GK detail in new-theme

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#623]
![image](https://user-images.githubusercontent.com/77342426/111772443-25cf6280-88ad-11eb-8cf0-3cb103951263.png)
This GK has only 3 moves .... so the atitude display is not good
![image](https://user-images.githubusercontent.com/77342426/111772560-4a2b3f00-88ad-11eb-99c6-12316c507e5d.png)
And it remains very tiny when I click on it

**Comment by kumy** [comment]
This feature has not yet been ported to new theme, the picture you see is just a placeholder while designing the website.

Tracked in #624
