### ISSUE TITLE
No caption in GK map (new theme)

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#626]
There are some points with various colors. What is the meaning of the colour ?

**Comment by kumy** [comment]
The colors represent the age of the last move.

Green moved very recently, red moved long time ago.

I'll add the caption. Good catch :)

**Comment by kumy** [comment]
Caption added and the accordion allow to display GK based on predefined filters.

![Screenshot from 2021-05-02 17-19-46](https://user-images.githubusercontent.com/176794/116818241-a9e25e80-ab6a-11eb-9de0-d1ee17190c3b.png)

![Screenshot from 2021-05-02 17-19-54](https://user-images.githubusercontent.com/176794/116818245-acdd4f00-ab6a-11eb-969e-e60d78fde344.png)

![Screenshot from 2021-05-02 17-20-01](https://user-images.githubusercontent.com/176794/116818247-aea71280-ab6a-11eb-88b2-f9dbe96a3aaf.png)

**Comment by GGGuerin** [comment]
No icon in the caption
![image](https://user-images.githubusercontent.com/77342426/116971581-1324b780-acba-11eb-9716-26af73202d1e.png)

**Comment by kumy** [comment]
Good catch, fixed - the css were not regenerated properly from scss ;)

**Comment by GGGuerin** [comment]
Yes fixed !

**Comment by kumy** [comment]
Fun, I'm "looking" to the same "region" :D:D near Pierrelatte

![Screenshot from 2021-05-04 09-44-48](https://user-images.githubusercontent.com/176794/116973859-7401bf00-acbd-11eb-82c0-9b496c0f4390.png)
