### ISSUE TITLE
GK missing in a cache

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#627]
I found one cache this week-end where i should find one GK. But there was no GK.
How can i report that the GK is missing ? I just could write a comment that GK is missing ....

**Comment by okainov** [comment]
There is (at least in current production) button "report as missing". So just click it.

**Comment by GGGuerin** [comment]
> 
> 
> There is (at least in current production) button "report as missing". So just click it.

Can you show me where please ?
![image](https://user-images.githubusercontent.com/77342426/111971123-51945780-8afc-11eb-9f37-c90df8bb4b0a.png)
Nothing to report missing here ...

**Comment by kumy** [comment]
@GGGuerin you were quite close :)

![2021-03-22_10-54](https://user-images.githubusercontent.com/176794/111971842-16465880-8afd-11eb-8fd0-316e40e6de87.png)

**Comment by GGGuerin** [comment]
Thank you !

**Comment by kumy** [comment]
In new theme it has been moved there:
![2021-03-22_10-56](https://user-images.githubusercontent.com/176794/111972054-4857ba80-8afd-11eb-8791-f8468f80eb16.png)
