### ISSUE TITLE
Display avatar picture in floating popup on "has avatar" icon

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#629]
![image](https://user-images.githubusercontent.com/77342426/112448540-c9f45600-8d52-11eb-9a9f-185e33a573ae.png)
If my mouse goes on the GK avatar, it does not display it as in the previous theme

**Comment by kumy** [comment]
Popup has been implemented. Code is currently deploying on https://new-theme.staging.geokrety.org/

![2021-05-01_12-19](https://user-images.githubusercontent.com/176794/116782282-9dc9a480-aa77-11eb-9903-c12d6f835433.png)
