### ISSUE TITLE
Wrong graphics on german help page

### ISSUE THREAD

**Issue by Lineflyer** [geokrety/geokrety-website#63]
When accessing https://www.geokrety.org/help_generate.php?help=de#Chooselogtype (in german) the log type icons are incorrect. When using the page in english, everything seems OK.
No idea whether this is a bug in the page code or in hyperlinks coming in from translations.

In fact it is a repitition of the geokrety type icons (see above):
![2018-04-16 11_26_43-geokrety_ hilfe](https://user-images.githubusercontent.com/949669/38802634-3edf6d7c-416d-11e8-88fb-dfa0776091fb.jpg)

**Comment by kumy** [comment]
Good catch, we'll rework the help files to crowdin as a translate support. Let's keep it open to not forget.

**Comment by kumy** [comment]
@Lineflyer help page is now available to translate on crowdin.

**Comment by Lineflyer** [comment]
@kumy Will take a look!

**Comment by kumy** [comment]
@Lineflyer just a friendly reminder :)

**Comment by kumy** [comment]
We're fine. Thanks!
