### ISSUE TITLE
How to adopt a GK ?

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#631]
I do not know what is the owner code ...
![image](https://user-images.githubusercontent.com/77342426/113421023-a5d7eb00-93ca-11eb-8700-5afbbfcb264a.png)

**Comment by kumy** [comment]
In GKv1 we have a specialized admin page, which permit admin to generate GK batch. From time to time, we generate batch for users organizing events and wishing to offer participants a nice reward. ;) We also used it to batch generate the c:geo limited contributors coins codes. - This special admin page would need to be ported to GKv2. Unfortunately, "normal" users don't have the ability to generate adoption code by themself. Admin have to manually update the database.

--- 

GKv2 allow users to propose their GK for adoption, link is on each **owned** GK page.
![2021-04-02_18-50](https://user-images.githubusercontent.com/176794/113436144-77ffa000-93e4-11eb-88ad-3cff217e9e2e.png)
![Screenshot from 2021-04-02 18-51-58](https://user-images.githubusercontent.com/176794/113436250-ada48900-93e4-11eb-9303-9257a2a110f1.png)


![2021-04-02_18-52](https://user-images.githubusercontent.com/176794/113436239-a9786b80-93e4-11eb-9efc-4925dae8b15d.png)

**Comment by GGGuerin** [comment]
@kumy : thank you for the explanation ! 
I used it this feature this morning on GKv2. In the present state, can I see adoption, that I id in GKv2, in GKv1 ?

**Comment by kumy** [comment]
> can I see adoption, that I id in GKv2, in GKv1 ?

No, GKv2 is only on staging state, it's database is completely overwritten every morning (it's currently broken since 2 days). This is instance is only meant to test GKv2 with real data. There is (will not be) way push modification back to GKv1 - databases are completely different schema and I don't want to waste my time doing a two way synchronization. sorry :)

**Comment by GGGuerin** [comment]
> 
> 
> > can I see adoption, that I id in GKv2, in GKv1 ?
> 
> No, GKv2 is only on staging state, it's database is completely overwritten every morning (it's currently broken since 2 days). This is instance is only meant to test GKv2 with real data. There is (will not be) way push modification back to GKv1 - databases are completely different schema and I don't want to waste my time doing a two way synchronization. sorry :)

It is what i feared :-) 
OK not necessary to work on that topic ;-)
