### ISSUE TITLE
EV (meeting-caches in gc.su) are not available

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#639]
Seems like for some reason EV* cache types from gc.su are not present in geokrety.. Example of the recent one - https://geocaching.su/?pn=101&cid=26340

Is is something we miss in our endpoint or on GK parsing side?

**Comment by kumy** [comment]
I'm sorry, i don't see the problem :/

![Screenshot from 2021-04-18 11-14-49](https://user-images.githubusercontent.com/176794/115140406-6f8ba400-a037-11eb-8aa1-c10986e3340c.png)
![Screenshot from 2021-04-18 11-15-02](https://user-images.githubusercontent.com/176794/115140408-71edfe00-a037-11eb-8c6e-46dc2fc79179.png)

**Comment by okainov** [comment]
Hmm... Maybe it's some c:geo issue then? I was dipping and dropping my GKs in this event, but in logs it looks like `ru 44.07707/40.16118` and not cache name.

See for example here https://geokrety.org/konkret.php?id=82402 log after " VI12533 Одинокий Турист ()" and before "TR26372 Памятник 3-й роте 379-го полка 20-й дивизии ()"

**Comment by kumy** [comment]
I can reproduce with https://geokrety.org/konkret.php?id=46684

Odd, editing the log show the correct waypoint, but it s not display in the GK details page. I ll check the database later.

**Comment by kumy** [comment]
Doesn t seems related to cgeo, as a direct log with the same parameters show the same issue.

**Comment by kumy** [comment]
Everything is fine in database, probably a weird case in the legacy code. GKv2 is fine with your log https://new-theme.staging.geokrety.org/en/geokrety/GK141E2#log2462218

I'll not go deeper in old code, and close this as is, sorry.

![Screenshot from 2021-04-19 09-13-10](https://user-images.githubusercontent.com/176794/115195807-7e359200-a0ef-11eb-83e0-ff2d89ad744b.png)

If someone want to track this issue, a good starting point are files `konkret.php` and `konkret-tabelka.php`
