### ISSUE TITLE
Geokrety map 

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#658]
For a few days, there is no more display of GK map at the original GK site.
![image](https://user-images.githubusercontent.com/77342426/124570128-e1a9a300-de46-11eb-81c6-de3308d7206e.png)

**Comment by kumy** [comment]
Yeah, I know :disappointed: that's because Google stopped their Map v2 API. We should have migrated to API v3 but I don't want to mess the actual GKv1 by doing code updates (except security issues).

BTW Such map is implemented and working on GKv2. :wink:

**Comment by kumy** [comment]
Closing as implemented in GKv2
