### ISSUE TITLE
MS* waypoints missing for gu.su

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#665]
Someone reported that `MS/26225` is not in our database, while investigating, I've found that we don't have any `MS*` waypoints at all. @okainov is there any good reason for not synchronizing such wpt?

I don't see any filtering in https://github.com/geokrety/geokrety-scripts/blob/master/waypointy/ru/gpx2sql.php, I'm wondering if it's gc.su api that is not giving us those wpt? (https://geocaching.su/rss/geokrety/api.php)

**Comment by okainov** [comment]
That's very odd, MS is the regular type of the cache (multi)

What might have happened is type update. For gc.su geocode is not constant, only the numeric ID is constant but the geocode might change.

However if you don't see them at all, it's completely mystery, shouldn't happen...

**Comment by okainov** [comment]
But I do see them?
I.e. for myself https://geokrety.org/konkret.php?id=82402, check 4th cache:

> MS3364 Монастырь Св. Николая в Крехове

**Comment by kumy** [comment]
:astonished: you're right, I wonder which sql query I've launched before opening this issue as I see them right now.

I've launched a complete reimport of gc.su waypoints, let's see if `MS/26225` will appear…

**Comment by kumy** [comment]
Ok, problem fixed, sorry for the noise.
![Screenshot from 2021-08-29 19-29-20](https://user-images.githubusercontent.com/176794/131259656-2eb4fb55-b1ea-4d0d-afce-1901545ad270.png)
