### ISSUE TITLE
Disabled OC cache not providing coordinates

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#666]
From support mail:

Normaly when You provide the OC-code,
then GK finds the name and the coordinates.
But this mechanism fails when the OC-code
points to a deactivated listing.

**Comment by kumy** [comment]
Mic@ may you provide an OC cache having the mentioned issue? Would be nice to also have screenshots demonstrating the problem. :)

**Comment by oconly** [comment]
OK, here the above issue with more details.
First I have this GeoKret...
https://geokrety.org/ruchy.php?nr=XYA273

...which I like to drop to this (disabled) Cache:
https://opencaching.de/OC16E0E

While typing "OC16E0E" in the field for the waypoint,
the website responds --> Fehlende oder ungültige Koordinaten 
(translation: missing or non valud coordinates)
![_screen](https://user-images.githubusercontent.com/10009402/131991317-d7c60587-a405-4e12-a92f-251601941f85.JPG)

**Comment by kumy** [comment]
hum interesting, [we follow OKAPI incremental updates](https://github.com/geokrety/geokrety-scripts/blob/master/waypointy/oc/xml2sql.php) and this waypoint is not in our database, I may try a full oc.de waypoint reimport, but it will take time…

**Comment by oconly** [comment]
This listing was only for a very short time online (active) and deactivated again by the owner.
The purpose was that we can make a beta test von this listing.
Also the coordinates are fake (north switched tosouth). Maybe it´s too far away for GK :-)

**Comment by kumy** [comment]
As said, we synchronize our local database with waypoints from oc* using OC OKAPI protocol, so if it is in there then we should have it in our database. On another hand "if" disabling a cache in OC is repercuted in OKAPI as "delete" then it is removed from our database too. Not sure the "issue" is on our side. Do you know other caches which were up for some time then disabled? So we check how they appear on our side.

**Comment by oconly** [comment]
I will check with developers if this is a problem by OKAPI.
THX for the analysis! Greetings from Berlin, Mic@

**Comment by kumy** [comment]
@oconly any news about this?

**Comment by oconly** [comment]
Good morning, I think You can close this old topic.
I checked above failure (see my screenshot on Sep 3, 2021) and the OC cache was correctly identified.
But meanwhile this cache OC16E0E is not disabled anymore, so I tried the same with another cache (OC15AF),
and here the cache was correctly identified again.
So everything is fine from our side... maybe the waypoint database got synchronized meanwhile :-)
Greetings, Mic@
