### ISSUE TITLE
Image size restrictions

### ISSUE THREAD

**Issue by andrixnet** [geokrety/geokrety-website#667]
Image size restrictions specify width=800 height=700. 
Why not 800x800 or 700x700? 
This restriction prefers landscape images and lowers comparative size&quality of the image is portrait. 
IMO it is unfair. 

Please improve this criteria. Thank you.

**Comment by kumy** [comment]
I know the actual file upload implementation is quite oldish and not optimal. This has completely been reworked on next website version, you can test it at https://new-theme.staging.geokrety.org.

I do not plan to work on legacy website version so I'll close this issue. Sorry.
