### ISSUE TITLE
Missing new gc.su caches?

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#670]
I got a complain from our users that seems like new SU caches are not on GK website... Just checked myself - I cannot see for example `TR27355` (https://geocaching.su/?pn=101&cid=27355) which was published on 10th of October (4 days ago).

Is some sync broken again? :(

**Comment by kumy** [comment]
Hum, the website itself need `php 5.6`, but the `cron` image probably could be upgraded, unfortunately I have no time at the moment for such changes :( there are many repo involved, and the `ansible` toolchain has to be  updated too

**Comment by kumy** [comment]
Manually fixed the problem and data synchronized, mentionned waypoint is now in database

![2021-10-14_22-44](https://user-images.githubusercontent.com/176794/137392647-63525daf-ff53-4088-a05d-c725440e694d.png)

**Comment by okainov** [comment]
>@okainov How did you solved that on gc.su? Did you rebuild php youself and published a docker image? From what I remember, upgrading php version on GKv1 is not an option 😢

I just disabled the verification =( Ugly but the error was only in one place, so was good enough...

>ok, a simple method is to explicitly disable the Expired certificate. In a debian based image

Good to know, thanks :)

And thanks!

**Comment by kumy** [comment]
> I just disabled the verification =( Ugly but the error was only in one place, so was good enough...

OMG :scream:
