### ISSUE TITLE
OC.pl waypoint synchronization is failing

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#675]
Our synchronization cron is currently failing with error:

```
 * processing OC_PL
 *        url:https://opencaching.pl/okapi/services/replicate/changelog?consumer_key=xxx&since=8491012

Warning: file_get_contents(https://opencaching.pl/okapi/services/replicate/changelog?consumer_key=xxx&since=8491012): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
 in /opt/geokrety/waypointy/oc/xml2sql.php on line 398
Cannot get incremental dump for OC_PL
Maybe `since` is too old, check full resync or try again
```

I've tried a fully resynchronization lsat week, and trying again now. Problem seems to be on OC.pl side which does not provide complete "full export"?

**Comment by kumy** [comment]
Another error while extracting the received `tar.bz`, which does only happen inside the `cron` container but not on the host

```
# tar -C oc_dump_extracted/ -xf tempfile.tar.bz2

bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

```

**Comment by kumy** [comment]
Response:
```
Hi Kumy, 

It seems we had again some issue with dump generation in OKAPI. I remember we had something like that before. Let me review it in next days.

kojoty
```

**Comment by kojoty** [comment]
@kumy please let me know if currently served dump is working for you

**Comment by kumy** [comment]
@kojoty I don't have the original error anymore. But there are now 2 things weird.

1. One warning, not sure if it's related to you or not
2. Some `json` files (there are many) are missing from the archive

```
bzip2: (stdin): trailing garbage after EOF ignored
```

```
# examples:
Warning: file_get_contents(oc_dump_extracted/part00003.json): failed to open stream: No such file or directory in /opt/geokrety/waypointy/oc/xml2sql.php on line 238

Warning: file_get_contents(oc_dump_extracted/part00108.json): failed to open stream: No such file or directory in /opt/geokrety/waypointy/oc/xml2sql.php on line 238

Warning: file_get_contents(oc_dump_extracted/part01537.json): failed to open stream: No such file or directory in /opt/geokrety/waypointy/oc/xml2sql.php on line 238

```

**Comment by kojoty** [comment]
HI, I think this is because last dump was broken - I tried to force generation and in result of my mistake it was generated twice - I think this is because of the overalp in generation.

Anyway I next generation is scheduled on 
cron-5       okapi\core\CronJob\FulldumpGeneratorJob   scheduled to run in 133963 seconds **(02:05:00, 2021-11-05)**

so if this is not a problem for you let's wait two days for the next dump - I assume it will be OK.

**Comment by kojoty** [comment]
New dump is ready. Please try if everything is ok now.

**Comment by kumy** [comment]
It's ongoing…

**Comment by kumy** [comment]
It's fine, we're now on `8860070`.
Thanks @kojoty
