### ISSUE TITLE
Improve search engines indexation

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#7]
Improve Geokrety search engine optimization.

Following actions could be done:
- "enhance pages semantic", 
- check current robots.txt https://github.com/geokrety/geokrety-website/blob/master/robots.txt 
   probably responsible for the non indexation of geokrety. 
- enhanced sitemap.

Most important content:
- Geokret details : https://github.com/geokrety/geokrety-website/blob/master/konkret.php
- Help pages

**Comment by kumy** [comment]
Found that, I don't know if it is relevant for this issue https://github.com/geokrety/geokrety-website/blob/f246feb47fdd9a203a1264cea1075423f7f24b2e/konkret.php#L248
