### ISSUE TITLE
Add a new geokrety type: playing card

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#705]
Like other ideas such as [cars](https://github.com/geokrety/geokrety-website/issues/465), [pets](https://github.com/geokrety/geokrety-website/issues/465#issuecomment-526944311), [pebbles](https://github.com/geokrety/geokrety-website/issues/613), add a new type : `Playing card`

![cards_PNG8471](https://user-images.githubusercontent.com/176794/148690230-24318f7c-1e75-48bb-86f0-fbb84c89c415.png)

**Comment by GGGuerin** [comment]
and jigsaw puzzle parts ... it is quite popular in GKs
