### ISSUE TITLE
GK move comment - image limits

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#735]
- Screen : https://new-theme.staging.geokrety.org/en/moves
- seen in [review](https://github.com/geokrety/geokrety-website/wiki/new-theme---2022-06---Boly38-review---temp-page---wip)

comment image - big image limit?

Does exist a way to set a image width ?

should the editor set a default width by default ?

I just paste an image url in my move form (/ comment / add image) 
And this produce the image with real size by default (I know that it is not necessarily easy to find a solution to this problem.)

![image](https://user-images.githubusercontent.com/3100576/175019412-10e124e8-5292-4860-b3e7-2e1c437cdf3e.png)

HowTo:
- search  an image url on Internet (having big width)
- add a geokrety comment - add image url - submit

**Comment by kumy** [comment]
It also happen in news comments and GeoKrety mission

**Comment by boly38** [comment]
- now limited to max width 100% : ✅ 
- no feature to set width
- thansk Kumy 👍
