### ISSUE TITLE
log a geokret (move) - form - invalid captcha

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#736]
(this issue may be maybe fixed with #731) 

- Screen: https://new-theme.staging.geokrety.org/en/moves
- seen in [new-theme review](https://github.com/geokrety/geokrety-website/wiki/new-theme---2022-06---Boly38-review---temp-page---wip)

Donnees supplementaire - captcha not checked
After all green input, I just missed to check "I'm not a robot" and this is what I get as result:
![image](https://user-images.githubusercontent.com/3100576/175018891-047ee3b9-f1ac-484e-b90a-a79a88365e8b.png)

I expect to have last step opened (not first one)

**Comment by kumy** [comment]
Now that the captcha button is moved out of last step, I think we can close this one.

**Comment by boly38** [comment]
captcha always at bottom ✅ - thanks Kumy 👍
