### ISSUE TITLE
[staging] post login - confirmation link message not translated

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#739]
- Screen: https://new-theme.staging.geokrety.org/fr/terms-of-use
- seen in [new-theme review](https://github.com/geokrety/geokrety-website/wiki/new-theme---2022-06---Boly38-review---temp-page---wip)

---
HowTo:
- login using existing account
- (24/06/2022 ~13h30 FR TIME) a message indicates that I must click on received email, but I never received it

![image](https://user-images.githubusercontent.com/3100576/175024820-2a104213-4e7f-4bf4-98ec-e83c32f206d7.png)

expected: a full french message (may be a crowdin issue, else wrong message id ??)

on crowdin, I'm unable to say where the issue is ? message seems here :/ 
![image](https://user-images.githubusercontent.com/3100576/175526840-b562ee35-67e3-4b13-9ffe-3bfb6bbfe364.png)

**Comment by kumy** [comment]
@boly38 could you please test again?

**Comment by boly38** [comment]
new test ok ✅ - thanks Kumy 👍
