### ISSUE TITLE
question (minor) adduser.php / mcrypt_encrypt warning on success

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#74]
Hi
While trying on local instance, I got this warning on register:
![image](https://user-images.githubusercontent.com/3100576/39058105-366f3db0-44bb-11e8-81d5-8c3b1a3c3024.png)

Unable to reproduce on rec.geokrety.org

Seems not linked to konfig-xxx

do you confirm: it's only when userid is very small ??

**Comment by kumy** [comment]
IMHO, it related to those config entries: https://github.com/geokrety/geokrety-website/blob/e929cc069b9a1026f4b0996d8cee56d35f348160/configs/konfig-local.tmpl.php#L16-L17

On prod config L16 is 16 chars long :)

**Comment by boly38** [comment]
will review that my side
was just question so I close issue
thx @kumu
