### ISSUE TITLE
Migration to GeoKrety.org v2 - Partners testing

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#754]
Hi,

I'm pleased to announce that GKv2 (GeoKrety.org rewritten from scratch) has now reached enough maturity in it's core public features to declare it as ready to be deployed. GKv2 work has been started some years ago, it's a complete rewrite, but the UI should look familiar. Sure there will be missing features but I think it's really usable.

The public staging instance is hosted at https://new-theme.staging.geokrety.org/. Database is synchronized from production every days at 2am UTC. So there will be no problem if tests are made there, just remind that everything there is volatile.

- Bugs should be reported on [GitHub](https://github.com/geokrety/geokrety-website/issues).
- Translations are hosted on [crowdin](https://crowdin.geokrety.org/).

Regarding the API and legacy URLs, I did my best to **keep same API endpoints or add redirections** so the migration should be transparent.

---

**Partners are however requested to _test their product on their staging/development environments against GKv2_ using the url above ^^** before we proceed with the migration.

---

The migration date will be set depending of the quantity, severity and time need to fix the new found bugs. :) Due to database and schema changes, the GKv1 to GKv2 migration will be one way forward. The expected downtime should be around 6h. To give everyone enough time let's plan that for February/March 2023...

# Known changes
## Rate limit system

API endpoint now have 2 types of rates limits:

- Use nginx rate-limiting and limit the number of request per second per group of endpoints
- Authenticated endpoints have requests limits calls per days.

Both of them should be quite high. Let me know if some needs tuning. For the 2nd point, for each request you'll find in the headers the current consumption, limit and count period.

## Timezone support

Historically all date times were processed as if they were UTC. Now timezone should be handled properly. On legacy API endpoints, there is now a new timezone parameter (default to UTC)

## GKM/GK fusion

On migration, the api.geokretymap.org will point to api.geokrety.org

## Pictures

- Upload is now possible via drag&drop
- Automatic image scaling
- User can have multiple avatars

## Comments

- Unicode support in titles and message body 🎉

## Missing features

- Rate Geokrety
- Races
- Users statistics
- GeoKrety statistics
- No GeoKrety altitude profile

Bests
Kumy - GK Team - France

---

# Notifications:

- c:geo: https://cgeo.org
  - [x] Mail
  - [ ] Issue tracker: https://github.com/cgeo/cgeo/issues/13542
  - [x] Mentions
    - @Lineflyer 

- oc.nl: https://www.opencaching.nl
  - [x] Mail
  - [ ] Issue tracker:
  - [x] Mentions
    - @harrieklomp

- oc.pl: https://github.com/opencaching/opencaching-pl
  - [x] Mail
  - [ ] Issue tracker:
  - [x] ~Mentions~
    - Unknown

- oc.de: https://www.opencaching.de
  - [ ] Issue tracker:
  - [x] Mentions
    - @teiling88

- oc.uk: https://opencache.uk
  - [x] Mail
  - [ ] Issue tracker:
  - [x] ~Mentions~
    - Unknown

- oc.us: https://www.opencaching.us/
  - [x] Mail: Gmail is not able to send them emails: `TLS Negotiation failed`
  - [ ] Issue tracker:
  - [x] ~Mentions~
    - Unknown

- oc.ro: https://www.opencaching.ro
  - [x] Mail
  - [ ] Issue tracker:
  - [x] Mentions
    - @andrixnet

- oc.cz: https://opencaching.cz
  - [x] Mail
  - [ ] Issue tracker:
  - [x] ~Mentions~
    - Unknown

- gc.su: https://geocaching.su/
  - [x] Mail
  - [ ] Issue tracker:
  - [x] Mentions
    - @okainov

- coord.eu: https://coord.eu/
  - [x] Mail
  - [ ] Issue tracker:
  - [x] Mentions
    - @andrixnet

- redan.art.pl
  - [x] Mail
  - [ ] Issue tracker:
  - [x] ~Mentions~
    - Unknown

- GeoKrety Toolbox
  - Firefox: https://raw.githubusercontent.com/geokrety/GeoKrety-Toolbox/master/GeoKrety.Toolbox.user.js
    - [ ] Issue tracker:
    - [x] Mentions
      - @kumy
  - Chrome: https://chrome.google.com/webstore/detail/geokrety-toolbox/ldbheajkebdflbjdckojokbfdndkahnl?hl=en-US
    - [x] Mail
    - [ ] Issue tracker:
    - [x] Mentions
      - @simor

- GeoKrety Logger: https://sourceforge.net/p/geokretylog/code/HEAD/tree/
  - [ ] Issue tracker:
  - [x] ~Mentions~
    - Unknown

- Opencaching QuickFind: https://play.google.com/store/apps/details?id=net.rygielski.roadrunner
  - [x] Mail
  - [ ] Issue tracker:
  - [x] ~Mentions~
    - Unknown

**Comment by okainov** [comment]
As usual we're very last minute :)

So after migration it looks like we have some issues with the full sync with geocaching.su against GK database. Incremental sync works fine via `https://geokrety.org/export_oc.php?modifiedsince=%s` endpoint, but we also do full refresh once in a while via `https://api.geokrety.org/basex/export/geokrety.xml`. And the latter gives 404 now.

Any suggestions for alternative endpoint returning full database dump?

**Comment by kumy** [comment]
GKv2 deployed, closing
