### ISSUE TITLE
waypoints are not working

### ISSUE THREAD

**Issue by brasiaPL** [geokrety/geokrety-website#79]
some of the waypoints are not working, e.g.
OP8RRA, OP8R8Q, OP8RRE, OP8R8S, OP8R8R, OP8R8N, OP8R8M
... e.g. OP8S4F, OP8S4G, OP8S4H etc...
:(

**Comment by brasiaPL** [comment]
... e.g.  OP8S4F, OP8S4G, OP8S4H etc... 
:(

**Comment by boly38** [comment]
I've no hand on REC/PROD but locally I tried the related waypoints 

I got the first list, but not the second one (my side OP8S4F, OP8S4G, OP8S4H are missing too)

I provide here a snapshoot, maybe timestamp `2018-05-02 12:25:xx` could help @kumy  to re-import the related timewindow

BTW I could provide related SQL if needed
![image](https://user-images.githubusercontent.com/3100576/40053156-8464b778-5840-11e8-8441-be1577af5538.png)

**Comment by kumy** [comment]
@brasiaPL @boly38 I'm sorry, I'm quite busy at the moment. I'll check what's wrong ASAP.

**Comment by kumy** [comment]
May be related to #90. Path were not fixed in cron container since we changed our main repository layout. Many waypoints are currently importing. Let's check in a moment..

**Comment by kumy** [comment]
@brasiaPL thanks for the report. And sorry for the long delay. It should now be fixed, feel free to reopen if problem occurs again.

**Comment by brasiaPL** [comment]
Thanks. Working!!!
