### ISSUE TITLE
race.php: cant join race

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#80]
I would like to join a race I just created (?raceid=13).
- txt length is limited to 6 chars, but now GK ref number is 7 length
- if I enforce 7 chars (by using developpers tools), then backend (race_add) refuse my code GK10936 "Ce n'est pas votre GeoKret"

**Comment by boly38** [comment]
See https://github.com/geokrety/geokrety-website/blob/master/website/race_join.php#L90

**Comment by boly38** [comment]
I've not installed php_cs at home, will see that later.. 
BTW need to build clean class to handle race; add check to avoid adding a GK twice to same race.

**Comment by boly38** [comment]
@kumy when did you plan next MTP ? because current version (5a69eeb) doesn't allow me to add my recent geokret to NewZeland destination..

**Comment by kumy** [comment]
What do you mean by `next MTP`? Update production to current master? If yes, do you validate what's actually on rec (f3737fa)?

**Comment by boly38** [comment]
oops yep U right, I've pending check on #81 
will create new PR for that.
