### ISSUE TITLE
Migration to GeoKrety.org v2 - Switch to branch `main` (aka `new-theme`/ `GKv2`)

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#807]
# Change plan to migrate to `GKv2`: Planned for September 14, 2023

| Title                        | Comment                                                                                    |
|------------------------------|--------------------------------------------------------------------------------------------|
| Start                        | ~February 24 2023, at 20pm UTC~ September 14, 2023 6 pm UTC                                                            |
| Planned public interruption  | 2h                                                                                         |
| Release risk                 | MAJOR                                                                                      |
| Planned operation            | Migrate to GKv2 which include a migration to postgres + full new db schema + full new code |
| Rollback plan during release | Roll the procedure in revert order                                                         |
| Rollback plan after release  | This is a one way forward major release                                                    |

Notes:
- The `api.geokrety.org` (read-only api) will stay up during the migration (`c:geo` users should be able to see caches inventory during the migration).
- The `cdn.geokrety.org` will stay up, it will serve the pictures until they are fully imported in a final step.
- [`https://prod.geokrety.org/en`](https://prod.geokrety.org/en) is the "ready to go" prod instance. Database will be synchronized every nights until migration.

### Public communication

- [x] Define the date (Maybe on **January 3, 2023**)
- [x] Write a news for the website
- [x] Request for translate on crowdin
- [x] Publish news on the website
- [x] Take hand on Twitter account (I need @boly38 help & phone number ;) )

### Ansible

- [x] prepare new ansible configs
- [x] ensure new instance deploys properly
- [x] disable automatic nightly imports from `legacy-prod`
- [ ] generate all users statpic on `staging`: `docker exec -i geokrety-new-theme_website.1.xxxxxxx make users-banner-regenerate-all`

### GitHub

- [x] create the new branches
- [x] review pipelines

### DNS

- [x] create new dns entries

### TLS certificates

- [x] Configure new certificates

### BaseX

The day before:

- [ ] Ensure we have the staging with recent prod data
- [ ] Ensure Basex exports are present for later step: `docker exec -i geokrety-new-theme_website.1.xxxxxxx make basex-import-all`

### Partners

- [x] Notify partners about upcoming changes and ask for testing (#754)

### BaseX

Note: this step can be done while the database is importing

- [x] Connect on `BaseX` and import known data:

```
$ basexclient
open geokrety
put / https://cdn.new-theme.staging.geokrety.org/exports/geokrety.xml
open geokrety-details
put / https://cdn.new-theme.staging.geokrety.org/exports/geokrety-details.xml
```

- [x] Check number of entries

```xpath

xquery count(doc('geokrety')//geokrety)  (: Should be 1 :)
xquery count(doc('geokrety')//geokret)  (: Should be ~94000 :)
```

### Import prebuilt statpic

- [x] Synchronize already built statpics from staging

```shell
$ rclone sync --progress gkstaging:statpic gkprod:statpic
```

### Suspend GeoKretyMap updates

- [x] Remove the `cron` container

```shell
$ docker service rm gkm_cron
```

### Suspend the website

- [x] Edit `haproxy` config and enable the pending config:

```shell
$ vi /etc/haproxy/haproxy.conf
$ # Enable the landing page ; see commented config
$ systemctl reload haproxy
```

- [x] Check if the service is suspended: https://geokrety.org
- [x] Take a last backup (db + files)
- [x] Tag the latest backup: `restic tag --add latest-legacy-prod xxxxxxx`
- [x] Remove the legacy-prod website container

```shell
$ docker service rm geokrety-legacy-prod_website
```

### Deploy new code

- [x] Edit the `main` Ansible config
  - `environment`
  - `sentry.env`
  - `website.uri` **(Don't enable the `api.geokrety.org` and **all** `geokretymap.org` yet !!!)**

- [x] Deploy the new code using ansible:

```shell
$ make akula_geokrety_ansible
$ make akula_geokrety_prod
```

- [x] Check new website version is up on the right domain using internal connection

```shell
$ curl -H "Host: geokrety.org" https://[2001:470:1f13:504::b0]/ -v -k
```

### Import the database

- [x] Launch script in a `screen` session **(it takes ~100 minutes)**

```shell
$ byobu
$ gk_copy-database_legacy-prod-to-prod.sh
```

### Clean the environment

- [x] Edit the "new" `prod` Ansible config
  - `website.uri` (Enable the remaining entries now)
  - `db.importer` (Remove the line)

- [x] Deploy the new code using ansible:

```shell
$ #### WAIT FOR THE DATABASE IMPORT BEFORE GOING FURTHER
$ #### ELSE THE IMPORT WILL BE INTERRUPTED
$ make akula_geokrety_ansible
$ make akula_geokrety_prod
```

### Make the new site accessible

- [x] Edit `haproxy` config and disable the temporary config:

```shell
$ vi /etc/haproxy/haproxy.conf
$ # disable the landing page
$ systemctl reload haproxy
```

- [ ] Check if the service is fine: https://geokrety.org

🎉🎉🎉

### Drop `GeoKretyMap.org`

- [x] Remove the whole `docker stack`

```shell
$ docker stack rm gkm
```

### Change OAuth app endpoint

- [x] On [geokrety github profile](https://github.com/organizations/geokrety/settings/applications), change the app urls

### Regenerate all users statpic

The time it takes don't matter, we imported old version in the past.

- [x] Launch the script in a `screen` session (it takes ~8 minutes)

```shell
$ docker exec -i geokrety-main_website.1.xxxxxxx make users-banner-regenerate-all
```

### Import the pictures

The time it takes don't matter, the old cdn will serve the files in the meantime.

- [x] Launch the script in a `screen` session (it takes ~? hours)

```shell
$ docker exec -i geokrety-main_website.1.xxxxxxx make pictures-import-legacy-to-s3
```

### Refresh the BaseX data

The time it takes don't matter, we have already imported quite fresh data at the beginning.

- [x] Launch script in a `screen` session (it takes ~6 hours)

```shell
$ byobu
$ docker exec -i geokrety-main_website.1.xxxxxxx make basex-import-all
```

**Comment by kumy** [comment]
Due to health issues, I have to postpone the migration. No new date at this time.

**Comment by GGGuerin** [comment]
Good recovery to you !

**Comment by okainov** [comment]
Get well soon and thanks for preparing, great work!

**Comment by kumy** [comment]
After 7 months I finally start to feel better :partying_face: I think I will do the migration mid-september :tada:

**Comment by okainov** [comment]
Yay, looking forward to it!

**Comment by kumy** [comment]
Changing the date to Sept 14

**Comment by kumy** [comment]
Migration done.

pictures and basex is synchronizing in the background

I'll keep it under watching a bit, during the next days
