### ISSUE TITLE
Map markers don't apply the color mentioned in legend

### ISSUE THREAD

**Issue by Lineflyer** [geokrety/geokrety-website#808]
GKv2 testing:
When looking at the GK in my inventory, the legend shows different colors for start, interim station and last seen.
The markers on the map however are all blue:

![image](https://user-images.githubusercontent.com/949669/210133994-4fdd2e17-2e04-45c4-86ed-4222357e193d.png)

Edit:
Example here: 
[GKFC75](https://new-theme.staging.geokrety.org/en/geokrety/GKFC75/page/1#moves)

**Comment by kumy** [comment]
[Fixed](https://new-theme.staging.geokrety.org/en/geokrety/GKFC75/page/1#moves), and also finally set the line as gradient… The gradient is based on the moves log step number. It could be enhanced in the future to represent altitude or whatever :shrug: 
![image](https://user-images.githubusercontent.com/176794/210249083-044bd965-4ee0-4065-8fc6-3c8fb68febd6.png)
