### ISSUE TITLE
Menu for own and other users functions look to similat

### ISSUE THREAD

**Issue by Lineflyer** [geokrety/geokrety-website#809]
GKv2 testing:
This is rather an improvement proposal than a bug.

If I pull up my own profile I do see the following with the different functions on the right hand side (red box):
![image](https://user-images.githubusercontent.com/949669/210134161-b4055b19-5465-407b-b418-4d4ddd28599b.png)

While browsing the website I ended up in looking at some other users profile and was a bit confused that the very same function list does now trigger the same functions for that user but not for my profile:

![image](https://user-images.githubusercontent.com/949669/210134226-5dd09433-10a8-4b96-82dc-cc0f76b52f57.png)

The functionality and the logic behind is OK, but it can be quite irritating, that it is just the 100% identical menu (but e.g. "Own geokrety" are not my own geokrety but the other users own geokrety).

A possible solution could be to make the strings adaptive, to have something like "Own geokrety" on my profile, but "Geokrety owned by $user" on other users profile.

**Comment by kumy** [comment]
Done, don't hesitate to suggest other wording if you feel it's necessary ;)
