### ISSUE TITLE
Use new c:geo logo in geokrety logbook for logs from c:geo

### ISSUE THREAD

**Issue by Lineflyer** [geokrety/geokrety-website#810]
GKV2 testing:
The icon used is still the outdated c:geo logo (the current one can be found in the c:geo repo)

![image](https://user-images.githubusercontent.com/949669/210134410-fabd326a-0b9f-4b29-b12a-c13f576a7fa8.png)

**Comment by kumy** [comment]
@Lineflyer I didn't found the logo itself as svg, so I took https://github.com/cgeo/cgeo/blob/master/main/project/rawimages/ic_launcher_send2cgeo.svg and removed the `send2` sub-icon myself.
I created https://github.com/cgeo/cgeo/issues/13808 + the PR https://github.com/cgeo/cgeo/pull/13809

**Comment by kumy** [comment]
![image](https://user-images.githubusercontent.com/176794/210214638-c08043fe-2c35-4632-a22f-f3e16ca8a133.png)
