### ISSUE TITLE
Amount of visited sites does not increase

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#820]
![Capture d’écran 2023-04-15 à 19 15 09](https://user-images.githubusercontent.com/77342426/232242163-32cc6053-55a2-47ba-96bc-d38e2d8f6d14.png)
![Capture d’écran 2023-04-15 à 19 18 56](https://user-images.githubusercontent.com/77342426/232242250-58a1c545-0a6b-4054-960d-e929886a016a.png)
I just created a new move in the Atlantic Ocean but the amount of visited places does not change .... It remains 639....

**Comment by kumy** [comment]
FTR: The mysql error is
![image](https://user-images.githubusercontent.com/176794/232243733-326eb9be-c93c-4397-920c-f7842c9e79fb.png)

:eyes:

**Comment by kumy** [comment]
Fixed in v1.11.5
