### ISSUE TITLE
Unable to visit a cache

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#822]
![Capture d’écran 2023-04-18 à 20 12 24](https://user-images.githubusercontent.com/77342426/232866868-ac9af151-9519-4ad1-a919-f33f3dd5e392.png)

**Comment by kumy** [comment]
I'm sorry I don't find that error in the error table. I wasn't able to reproduce as oer my last tests on https://geokrety.org/konkret.php?id=46684

Are you still able to reproduce? Could you show me the form content before submitting it :pray:

**Comment by GGGuerin** [comment]
👻 This emoticon was in the comments. If I delete it, I can so submit my log. 
This post can be closed. Thank you kumy

**Comment by kumy** [comment]
Ok I see. Emoji will be supported in GKv2. Anyway, thanks for reporting
