### ISSUE TITLE
Invalid places count and distance

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#845]
![bec7e491-bd3c-4591-a01b-93a43c78d79a](https://github.com/geokrety/geokrety-website/assets/77342426/ff6f7821-92b8-4620-8f8c-b70efa316d3f)
Mismatch between visited places and country track

**Comment by GGGuerin** [comment]
If a movement is recorded with GKv2, visited places fit then with country track !

**Comment by kumy** [comment]
> I'll add a step during the import to force recomputing the counters.

Done. Should be ok for next nightly import
