### ISSUE TITLE
C:geo

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#850]
I can no more log Geokrets with c:geo.

**Comment by kumy** [comment]
I tested this morning and it was working for me. Which c:geo version are you using? Is there a specific error message?

**Comment by kumy** [comment]
Ok, when logging a cache from c:geo, the user GK inventory is empty.
I was able to reproduce. looking into it.

**Comment by kumy** [comment]
Error found in Sentry
```
ErrorException

Deprecated: ctype_digit(): Argument of type int will be interpreted as string in the future
```

Arf, i should not have upgraded the whole stack to php 8 a few weeks before the release :cry:

**Comment by kumy** [comment]
Will be deployed in a moment

**Comment by kumy** [comment]
@GGGuerin I works for me now, could you please confirm
