### ISSUE TITLE
Amount of displayed GKs

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#853]
It is not possible to display more than 100 Gks. It was possible in the previous version.

**Comment by kumy** [comment]
Where please?

**Comment by GGGuerin** [comment]
![image](https://github.com/geokrety/geokrety-website/assets/77342426/5463ca7a-76eb-4d6d-b81f-36b055f02e15)

**Comment by kumy** [comment]
Hum, as far as I remember, there was memory exhaustion if there was not limit... Will look at it later.

**Comment by kumy** [comment]
yeah, just tested with a max on 10000 and I get memory error
![image](https://github.com/geokrety/geokrety-website/assets/176794/8baa44e0-d30e-476d-b5e7-ce4c06d78069)

**Comment by kumy** [comment]
I will set a limit of 1000, it seems to work on my local dev environment

**Comment by GGGuerin** [comment]
It works well for me !
