### ISSUE TITLE
Sort Geokrety lists by last update is inacurate

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#854]
![image](https://github.com/geokrety/geokrety-website/assets/77342426/872d8add-ed9a-41eb-8ad8-fb2ba5fdc562)
When one wants to order GKs in functions of the last mofdifcation dates, ranking is not perfect.

**Comment by kumy** [comment]
Code is deployed, it should be better now!

**Comment by GGGuerin** [comment]
It works well now.
