### ISSUE TITLE
GK banner links changed, "legacy bridge" needed

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#859]
I can no more display GK banner on my GC profile 
![image](https://github.com/geokrety/geokrety-website/assets/77342426/811885be-1bdd-48cb-9a6a-dd5bb1ea96bc)

**Comment by kumy** [comment]
The url has changed to access them. I will need to add a "legacy bridge" for them.

**Comment by devmuhib009** [comment]
I want to solve this issue as this is marked as ''good first issue", I am new at opensource contribution. Can someone guide me here?

**Comment by kumy** [comment]
Hi thanks for your proposition. First you'll probably need to run the code locally. We use `docker` to start all the dev instance. You'll find a sample `docker-compose.yml` file at the repository root.

**Comment by kumy** [comment]
https://cdn.geokrety.org/images/statpics/26422.png now redirects to https://cdn.geokrety.org/images/statpics/26422.png
