### ISSUE TITLE
There is no transition from the geokrety page when you click to the su cache page.

### ISSUE THREAD

**Issue by Detroit70** [geokrety/geokrety-website#860]
There is no transition to the su website
Example
  https://geokrety.org/ru/geokrety/61778
If you click on MS13817
![not go to site su](https://github.com/geokrety/geokrety-website/assets/51854774/c9884533-a0bf-46bd-a99b-abbfe23758ba)

Then you get a transition and an inscription that the cache does not exist
The link should lead to the next page following the link.
https://geocaching.su/?pn=101&cid=13817
![not found when click](https://github.com/geokrety/geokrety-website/assets/51854774/09b0bcbe-0c9b-4587-bfef-5b4f5057b6a9)

this is the correct link
https://geokrety.org/go2geo/?wpt=MS13817
and this link is registered now and it leads to the page of which I am attaching a screenshot

And this is the situation with any transition to the su cache

**Comment by kumy** [comment]
Should be fixed in v2.38.4
