### ISSUE TITLE
Problem with links to opencaching.pl

### ISSUE THREAD

**Issue by paraleline** [geokrety/geokrety-website#864]
Hi
I have a problem with links to opencaching.pl
Could you see the description in attachment?
![problem 1](https://github.com/geokrety/geokrety-website/assets/146210799/f5dcc2cd-4a4d-44cd-af94-cd16c4da535e)

**Comment by kumy** [comment]
I will have a look. Do you have an example of "correct" link?

**Comment by kumy** [comment]
I looked quickly to the opencaching code for this search page: https://github.com/opencaching/opencaching-pl/blob/master/searchplugin.php

The page is requiring a `sourceid`...

**Comment by paraleline** [comment]
Look, please at the attachment
![explanation 1](https://github.com/geokrety/geokrety-website/assets/146210799/41c24d07-a3d1-4d3a-9d13-aec38fe0b63a)
