### ISSUE TITLE
Posting Geokrety (by c:geo)

### ISSUE THREAD

**Issue by paraleline** [geokrety/geokrety-website#866]
Hi

I can only log in all my geokrety for the first few geocaches per day. Then c:geo logs geokrety supposedly, but in fact there are no logs on the geokrety.org website. The next day the situation repeats itself.
Few more details in my attachment.

![problem 3](https://github.com/geokrety/geokrety-website/assets/146210799/d71a0134-5ef7-473b-bcd3-27a376aae98a)

**Comment by kumy** [comment]
This should be related to the new rate limiting system. How many log do you do per day ???? I see 8/263 (🫣), I think the rate limit is 1500 logs per day (I thought is was a reasonable number). So after your 5th cache you should have problems...
Another thing for the "next day", the counters is a fifo, so first logs should not count anymore after the delay.

Regarding c:geo, maybe it doesn't handle the proper http error code for a "too many request" http 429. Also, the current user rate limit is available in the response header from the server. /cc @Lineflyer

**Comment by kumy** [comment]
I did some checks, and effectively you are hitting the rate-limit
![image](https://github.com/geokrety/geokrety-website/assets/176794/29278713-8bab-46fb-bf3f-bf33bafc3160)

**Comment by paraleline** [comment]
263 geokrets x approximately 30 caches a day (or more ;) - almost 8.000 logs a day...

**Comment by kumy** [comment]
@paraleline I manually reset your rate limit usage  for this API endpoint. could you test if you can post logs (in the current limit of course...)

**Comment by paraleline** [comment]
It seems I can. I've tried just now for a one geocache and few geokrets and there were no problems (a few hours ago it wasn't possible after the today's limit was used). Do I still have a limit of 1,500 or will it be increased?

**Comment by kumy** [comment]
cool, at least your main issue cause is identified...

> Do I still have a limit of 1,500 or will it be increased?

I will raise it a bit so you can play, but I also need to check if the "purge" is really done in the background...

**Comment by paraleline** [comment]
@kumy 
ok - thanks a lot!

**Comment by kumy** [comment]
Raised temporarily the limit to 10000/day.

I still need to check if the "purge" is really done in the background... But I'll do that this weekend

**Comment by paraleline** [comment]
Unfortunately: after logging only a few geocaches today (and thus about 1000 geokrety), further logging of geokrety using c:geo has become impossible again :(

**Comment by kumy** [comment]
@paraleline I just checked, your actual quota usage count is 11/10000
The error I see in the logs is `Something already exists at the same datetime "Moved_on_datetime"`

![image](https://github.com/geokrety/geokrety-website/assets/176794/0b64a03e-be72-4316-b316-c4769348edad)

**Comment by paraleline** [comment]
ok - I know what the problem is: my mistake.
Today I logged 19 geocaches (therefore about 5000 geokrets) and everything worked perfectly :)
Thank you very much for your quick and effective help!

**Comment by kumy** [comment]
Good to know. 👍

I looked at the rate-limit reset code, and it need to be reworked. I will do that during the weekend...

**Comment by kumy** [comment]
I've reworked the rate-limiter. Let me know how it goes.

You can get your current rate limit using this address:
`https://geokrety.org/api/v1/rate-limit/usage?secid=<secid_here>`

It's using `Token Bucket Algorithm`, and should quota should properly refill regularly...
