### ISSUE TITLE
All (Many) GeoKrety appear in only one cache

### ISSUE THREAD

**Issue by paraleline** [geokrety/geokrety-website#867]
I found over 200 geokrety in one cache :) I think it's no possible...
https://opencaching.pl/viewcache.php?cacheid=90925
Including mine, while I'm sure it's travelling.
A few days ago, most of my geokrets  were logged in one cache as dropped, while of course I had them with me.
![problem 4](https://github.com/geokrety/geokrety-website/assets/146210799/a7732959-7b5e-4a4f-aa49-a4a7d1ad7afd)
![problem 4a](https://github.com/geokrety/geokrety-website/assets/146210799/01dc90e8-1651-4493-97ac-b46ebed0cc7c)

**Comment by kumy** [comment]
mail sent to `rt at opencaching.pl` (https://opencaching.pl/News.RawNews/show/280)

---

> Hi,
> 
> Someone reported this issue https://github.com/geokrety/geokrety-website/issues/867
> 
> I suspect it has something to do with your regular imports from our export files. It should also be related to our new website version. But I have no idea what is going bad. Could you check on your side if you understand how this is possible?
> 
> Bests
> Kumy

**Comment by kumy** [comment]
@harrieklomp @teiling88 @andrixnet Did you see something similar on your oc.nl/de/ro ?

**Comment by kumy** [comment]
I hope root cause was the same as https://github.com/cgeo/cgeo/issues/15263#issuecomment-1951216075

@paraleline may you please check if it has fixed it :pray: 

BTW I never get an answer to the mail sent in https://github.com/geokrety/geokrety-website/issues/867#issuecomment-1751305387
> mail sent to rt at opencaching.pl
