### ISSUE TITLE
logs deleting

### ISSUE THREAD

**Issue by paraleline** [geokrety/geokrety-website#869]
Is it possible to restore the possibility of deleting the logs of my own geokrety in a situation, when my geokret is right now in other hands (look at the situation presented on the screenshot)
![2023-09-30 (1)](https://github.com/geokrety/geokrety-website/assets/146210799/ce0532e8-4a46-4139-9d27-738a762066fe)

**Comment by kumy** [comment]
I didn't knew it was possible in GKv1 😥

**Comment by paraleline** [comment]
Yes, surely it was. I did it myself, for example, when someone logged my geokrety with a date when it was not yet in his/her hands.
I would also like to delete logs shown above on the screenshot ;)
