### ISSUE TITLE
Google Maps will not be free anymore

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#87]
it seems that google map api services will not be free anymore starting June 11, 2018.

https://cloud.google.com/maps-platform/pricing/
http://www.frandroid.com/android/developpement/502962_incomprehension-chez-les-developpeurs-google-maps-sera-exclusivement-payant-des-le-mois-de-juin

We have to switch to another provider soon.

I have started using leafletJS some time ago, it can handle multiple providers. I think it may be used in some part of the actual website.

* konkret.php
* mapka_kretow.php

We have to find a new way to generate static map https://rec.geokrety.org/mapki/google_static_logs.png

**Comment by boly38** [comment]
- Following #254 #268 : `konkret.php` uses now leafletjs

stay todo (to migrate):
- `mapka_kretow.php?userid=xxxx`
- `user_stat.php?userid=xxxx`
- `/mapki/google_static_logs.png`
- `race.php`

**Comment by kumy** [comment]
Fixed in `new-theme`.
