### ISSUE TITLE
Error HTTP 404 in statistics for previous years

### ISSUE THREAD

**Issue by SDymon** [geokrety/geokrety-website#887]
![Ошибка_при_открытии_статистики_за _предыд_годы](https://github.com/geokrety/geokrety-website/assets/150231059/24317c7c-0f17-41cf-a366-d7eeaae2cf46)

**Comment by okainov** [comment]
@SDymon  probably wrong screenshot, could you please check and maybe put the link as well?

**Comment by SDymon** [comment]
Great! Thanks!
But...
Here's another language pack problem! I'm attaching the screenshot.
![Скрин](https://github.com/geokrety/geokrety-website/assets/150231059/a73f3f72-4da2-4461-895c-9003a3c278a7)

**Comment by kumy** [comment]
Translation should be missing on crowdin. Feel free to contribute there https://geokrety.crowdin.com/
