### ISSUE TITLE
After moving to a new site, it is impossible to mark a geokret from an application "c:geo" with an empty comment.

### ISSUE THREAD

**Issue by SDymon** [geokrety/geokrety-website#889]
After moving to a new site, it is impossible to mark a geokret from an application "c:geo" with an empty comment.

**Comment by kumy** [comment]
I don't see any limitation in the current code.
I was able to post that move https://geokrety.org/en/geokrety/GKB65C#log4881900

/cc @Lineflyer WDYT?

**Comment by Lineflyer** [comment]
@SDymon 
What do you mean by "mark a geokret"?
Can you describe the steps in c:geo you take. 
What error message is returned by c:geo?

**Comment by SDymon** [comment]
> I don't see any limitation in the current code. I was able to post that move https://geokrety.org/en/geokrety/GKB65C#log4881900
> 
> /cc @Lineflyer WDYT?

I’m not talking about a geokrot named "c;geo". I mean a smartphone application "c;geo".

**Comment by SDymon** [comment]
> @SDymon What do you mean by "mark a geokret"? Can you describe the steps in c:geo you take. What error message is returned by c:geo?

I'll let you know later today.

**Comment by kumy** [comment]
(The GeoKret called "c:geo" is just my GK test item. I used it to post a log using c:geo app)

**Comment by SDymon** [comment]
![IMG_5343](https://github.com/geokrety/geokrety-website/assets/150231059/08ef708d-2862-4b22-aea2-93c34fef6aae)

**Comment by SDymon** [comment]
c:geo не удалось отправить вашу запись, потому что она пуста.
translation into English:
Your entry could not be sent because it is empty.

**Comment by okainov** [comment]
@SDymon yes, because you cannot have empty logs on geocaching.su

**Comment by SDymon** [comment]
Since when did this happen? Before geokrety.org update this was possible.

**Comment by okainov** [comment]
@SDymon more than a few years ago for sure, maybe there was some bug in cgeo which got fixed somehow, but anyway, no empty logs for .su caches is expected.

**Comment by Lineflyer** [comment]
IMHO it is wise to forbid empty logs in general.

**Comment by kumy** [comment]
Thanks all. I'll close the issue.

**Comment by SDymon** [comment]
> @SDymon more than a few years ago for sure, maybe there was some bug in cgeo which got fixed somehow, but anyway, no empty logs for .su caches is expected.

Empty logs were available this year. So there have been changes to the .su?
