### ISSUE TITLE
When marking a geokret, each section must be expanded. Previously, it was enough to scroll the page.

### ISSUE THREAD

**Issue by SDymon** [geokrety/geokrety-website#891]
![Снимок](https://github.com/geokrety/geokrety-website/assets/150231059/4d949a7e-dfc4-46f7-99d5-54fab291291c)

**Comment by okainov** [comment]
Actually I have the same thing, while it might be useful for new users/guests to have wizard-like kind of process, for advanced users it just forces to do way more clicks, quite inconvenient...

**Comment by kumy** [comment]
Duplicate of #722.
Closing here

**Comment by SDymon** [comment]
Disappointed in the impossibility of solving this problem!

**Comment by kumy** [comment]
I can understand your frustration. But this form is quite complex, and require lot of care and unit testing to be robust. Thus a lot of time (and motivation) from my side, which I don't have at the moment. Sorry.

**Comment by SDymon** [comment]
it's a pity.
