### ISSUE TITLE
Incorrect use of a language pack in identical tools.

### ISSUE THREAD

**Issue by SDymon** [geokrety/geokrety-website#892]
![Русификация](https://github.com/geokrety/geokrety-website/assets/150231059/7d592e60-0b4e-430d-9cc6-56bc2ff05db1)

**Comment by okainov** [comment]
Just fixed bunch of Russian translations on Crowdin, should be better now

**Comment by kumy** [comment]
There is an already existing issue to provide a form for advanced users. Never had time to work on it sorry

**Comment by SDymon** [comment]
Great! Thanks!
