### ISSUE TITLE
It is impossible to enter the date and time using the numeric keypad, as in the previous version of the site.

### ISSUE THREAD

**Issue by SDymon** [geokrety/geokrety-website#894]
It is impossible to enter the date and time using the numeric keypad, as in the previous version of the site. It is inconvenient to select and scroll through dialog elements.
![Скрин](https://github.com/geokrety/geokrety-website/assets/150231059/8e3433c9-fe54-4629-9b96-997a0ebb7b1e)

**Comment by kumy** [comment]
Duplicate of https://github.com/geokrety/geokrety-website/issues/722.
Closing here
