### ISSUE TITLE
Non-compact list of geokret movement history.

### ISSUE THREAD

**Issue by SDymon** [geokrety/geokrety-website#896]
![Снимок_marked](https://github.com/geokrety/geokrety-website/assets/150231059/e4e8b187-aa27-437d-81d8-bbf42d85129c)

In the old version of the site, more marks were placed on the page.

**Comment by kumy** [comment]
Caused by #897.
There seems to be a glitch with the Dropzone css...
Closing here

**Comment by SDymon** [comment]
Fine! But I think that for an even more compact appearance, it is advisable to place a number of buttons (edit, delete, add photo, add comment) on the same line with the comment text.
