### ISSUE TITLE
Incomprehensible button in each geokrot mark.

### ISSUE THREAD

**Issue by SDymon** [geokrety/geokrety-website#897]
![Непонятная кнопка в каждой отметке крота_marked](https://github.com/geokrety/geokrety-website/assets/150231059/ae3f70fc-64f5-4d91-b0fc-a4d0171f99be)

When you press it, nothing happens.

**Comment by kumy** [comment]
There seems to be a glitch with the Dropzone css...

**Comment by SDymon** [comment]
Great! Thanks!
