### ISSUE TITLE
There is no separating space between username and title "My posted pictures".

### ISSUE THREAD

**Issue by SDymon** [geokrety/geokrety-website#898]
![Скрин_marked](https://github.com/geokrety/geokrety-website/assets/150231059/bb5a3521-b07a-4741-8f10-ce48501719d2)

**Comment by okainov** [comment]
Just updated the translation string, should be better with the next locales update (@kumy how often does it happen, daily?)

**Comment by kumy** [comment]
Thanks. If the crowdin integration is not broken again, then we should receive a new PR soon after the strings are updated on crowdin

**Comment by kumy** [comment]
Crowdin don't create the new commits on the translation branch thus not creating a PR... This is not the first time this integration is broken, it start to really bother me :exploding_head:

**Comment by kumy** [comment]
Fixed in v2.40.2
![image](https://github.com/geokrety/geokrety-website/assets/176794/e6acc37f-5200-496b-9924-873f12105af3)

**Comment by SDymon** [comment]
Great! Thanks!
