### ISSUE TITLE
No email notifications

### ISSUE THREAD

**Issue by filipsPL** [geokrety/geokrety-website#90]
For some time (one user mention 3 months) there are no email notification about geokrety moves.

**Comment by kumy** [comment]
Oh :( I'll check. One container may have died >:(

It may also be the problem for the other issue where waypoints are not available in our database.

On June 5, 2018 11:00:40 PM GMT+02:00, filips <notifications@github.com> wrote:
>For some time (one user mention 3 months) there are no email
>notification about geokrety moves.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/geokrety/geokrety-website/issues/90

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment]
Path in `konfig-tools.php/sh` was not changed accordigly to the new main repo layout, my bad :(

**Comment by kumy** [comment]
It started on `Thu Apr 19 17:29:01 UTC 2018`

**Comment by kumy** [comment]
Ok, mail are now sent again.
