### ISSUE TITLE
Wrong location

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#902]
For example, choose one GK of the ones most famous owner : Burned (GKF769) owned by.... kumy !
The last location provided by GK site is in Serbia.
![GK 1](https://github.com/geokrety/geokrety-website/assets/77342426/de78d38a-1838-4d6c-9863-7d47cde7e3cf)

If one looks at the cache site, it is in Portugal ....

![GK2](https://github.com/geokrety/geokrety-website/assets/77342426/8fd7b11a-5370-4ad6-a0de-a25ee2a1d3bc)

**Comment by kumy** [comment]
I manually fixed that waypoint.
It remind me https://github.com/geokrety/geokrety-website/issues/186#issuecomment-526861995
