### ISSUE TITLE
to log a GK at a date older than the creation one

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#903]
It is no more possible to log a GK at an older date that the creation date of the GK.

**Comment by kumy** [comment]
Why would someone do that?

**Comment by kumy** [comment]
Ok make sense. Beside the code change, the integration tests should also be changed...

**Comment by kumy** [comment]
What should be done:
- This [test](https://github.com/geokrety/geokrety-website/blob/main/website/db/tests/test-30-moves-moved-on-datetime.sql#L17-L19) should be changed to it's opposite
- A [new migration](https://github.com/geokrety/geokrety-website/blob/main/website/db/tests/test-30-moves-moved-on-datetime.sql#L17-L19) has to be created to change the database behavior (in function `moves_moved_on_datetime_checker()`)
![image](https://github.com/geokrety/geokrety-website/assets/176794/5a7dbac4-4f96-4c18-8f69-85af7ede64f2)
- [Integration tests](https://github.com/geokrety/geokrety-website/blob/main/tests-qa/acceptance/210_LegacyBridges/210_ruchy.robot#L65) must be adjusted

Anyone willing to contribute?

**Comment by kumy** [comment]
I was really annoyed by the concept of "moving before GK birth", and finally went to the conclusion that GK Bird date should be editable :)

Ongoing work in PR https://github.com/geokrety/geokrety-website/pull/1012
The GK birthdate will be editable from the GK edit form
![image](https://github.com/geokrety/geokrety-website/assets/176794/afe90d7d-edfd-436e-827b-f2d04569edf8)

**Comment by kumy** [comment]
It could be tested on staging https://staging.geokrety.org
