### ISSUE TITLE
Unclickable links on the new site

### ISSUE THREAD

**Issue by Detroit70** [geokrety/geokrety-website#904]
All links that were clickable on the old version are no longer clickable on the new one
![old link](https://github.com/geokrety/geokrety-website/assets/51854774/60fe3309-8425-4b3c-bff0-020ecd8bb1b0)
![new link](https://github.com/geokrety/geokrety-website/assets/51854774/9a0cc79a-079f-47fb-9aca-880d7ed41e8e)
Another  examples 
https://geokrety.org/ru/geokrety/GK15C5D
https://geokrety.org/ru/geokrety/GK104FC
AlsoI know many other examples

**Comment by kumy** [comment]
I'm really sorry for that. Some data seems to have been lost during the transition GK description  transition to markdown 😵

**Comment by kumy** [comment]
What could be done:
- create a new db migration to create a new column in the GK table
- import raw description from last GKv1 backup (Only me can do this step)
- implement a button to "revert to GKv1 raw content"
- Let user fix the formatting

Contributions are welcome!

**Comment by Detroit70** [comment]
From what you suggested, I would like to ask you to implement the following function on the new site, so that anyone can make edits on the new version in independent mode, transferring links from the old version, that is
implement a button to "revert to GKv1 raw content"

How can this be done and can we be helpful in carrying out this task?

**Comment by kumy** [comment]
So, I pushed 2 commits f6872f3d2b53ca33dcb2353f3f50db0632ef8b40 dc4407e287a0dbd908f47530845cd7139bb7ad41

That will add a new button in from tof the "Mission" label
![image](https://github.com/geokrety/geokrety-website/assets/176794/1766beb8-fa3f-41dd-82b7-4efaac9a388c)

On click it open a modal with the raw old content
![image](https://github.com/geokrety/geokrety-website/assets/176794/316d7258-af37-475f-9dbc-2665a8f18aed)

It is testable on https://new-theme.staging.geokrety.org

I will push to prod once the workflow finish

**Comment by kumy** [comment]
Done on prod.

> How can this be done and can we be helpful in carrying out this task?

There are new strings to translate on crowdin, you may help here https://crowdin.geokrety.org/ :shrug:

**Comment by kumy** [comment]
> How can this be done and can we be helpful in carrying out this task?

Create a wiki page explaining how to accomplish "this" based on the commits linked in this issue
- f6872f3d2b53ca33dcb2353f3f50db0632ef8b40
- dc4407e287a0dbd908f47530845cd7139bb7ad41
- 0987673ed57771301adad9e68674998000eb4933
- https://github.com/geokrety/geokrety-ansible/pull/100
- https://github.com/geokrety/geokrety-ansible/pull/101

**Comment by kumy** [comment]
I forget to create the related Integration tests

**Comment by kumy** [comment]
tests added in ab3c0fa
