### ISSUE TITLE
Difference between "missing" and "archived"?

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#906]
Just went thru my poor GKs today just to figure out a lot of them have actually gone missing with no logs for a long time. The ones which have been marked as "In the cache" are somehow easy - there is a small red button "probably missing" which adds red comment and then highlights the whole GK with red in the list of owned GKs. So far so good and easy.

However for the GKs which are marked as "in the hands of.." there is no way I can declare them as missing, there is just no such button next to the logs. So, _Q1: why? Can we have button "probably missing" even for "grabbed it" logs?_

So I did archive them clicking "archive". However now in the list they're not higlighted with red:
![image](https://github.com/geokrety/geokrety-website/assets/918446/3187cbdd-651d-4281-9872-7e13a2b410d6)

Q2: what am I doing wrong? I want to have a similar state for my GKs which are lost/missing, regardless of whether they got missing from the hands of someone or from the cache. How should I mark them?

**Comment by kumy** [comment]
> Difference between "missing" and "archived"?

- GK marked as missing, should still appear in cache inventory. In GKT or `exports.xml`
- GK marked as archived, should not be present in cache inventory.

> Q1: why? Can we have button "probably missing" even for "grabbed it" logs?

It was like that in the old version too. But yeah I agree, that should be unlocked

> Q2: what am I doing wrong? I want to have a similar state for my GKs which are lost/missing, regardless of whether they got missing from the hands of someone or from the cache. How should I mark them?

Could you define what is "similar state for my GKs which are lost/missing" for you?

Maybe we should define the background colors for each state?

**Comment by kumy** [comment]
I believe that this commit will do it https://github.com/geokrety/geokrety-website/commit/3e42aba23ad21fa28b5bfa1781870cc1efe8efb6

**Comment by okainov** [comment]
>Could you define what is "similar state for my GKs which are lost/missing" for you?

@kumy I mean like on the screenshot - I expect all "missing" GKs should have red background. Saw the change, thanks!


>GK marked as missing, should still appear in cache inventory. In GKT or exports.xml
But it still would have "missing=1" property, at least in gc.su we filter by it and treat those like "not in the cache any more" :) So at least for gc.su it doesn't matter really.
