### ISSUE TITLE
Posting Geokrety by c:geo

### ISSUE THREAD

**Issue by paraleline** [geokrety/geokrety-website#908]
Unfortunately, again I cannot log in more than 1500 geokrety per day by c:geo. You once increased this limit for me (Issue #866), but today the situation repeats itself: 1,500 logs and that's it.  :(
Probably in September you raised the limit temporarily .
Could you increase it again?
leszek.

**Comment by kumy** [comment]
As said in https://github.com/geokrety/geokrety-website/issues/866#issuecomment-1741832853, the algorithm has been effectively changed end of September.

> I've reworked the rate-limiter. Let me know how it goes.
> 
> You can get your current rate limit using this address:
> https://geokrety.org/api/v1/rate-limit/usage?secid=<secid_here>
> 
> It's using Token Bucket Algorithm, and should quota should properly refill regularly...

Here are some rate-limits graph history. Even if there are some peaks, the limits should be fair on most user cases. So I don't think the limits are unfair. Maybe it's your usage that is crazy :robot:? Also from the graph we can see that the refill is quite quick and in less than 1h you should get fully refilled.

Limits are here to try prevent service usage abuse, spam or :shrug: . There is actually no way to raise the limits per user sorry.

### Last 15 days
![image](https://github.com/geokrety/geokrety-website/assets/176794/33d66bec-0a54-44b5-ad11-7e1e3ef314a9)


### peak 1
![image](https://github.com/geokrety/geokrety-website/assets/176794/f72cead5-2bc4-446e-bf38-a616705eb2e3)
![image](https://github.com/geokrety/geokrety-website/assets/176794/d5f6c218-ecc5-4a07-8764-74b131807433)

### peak 2
![image](https://github.com/geokrety/geokrety-website/assets/176794/39182664-d96a-494f-b88f-0c49e0932ae1)
![image](https://github.com/geokrety/geokrety-website/assets/176794/732dcdf8-bae3-431e-889b-ad1fd11bc87e)

### peak 3
![image](https://github.com/geokrety/geokrety-website/assets/176794/f93e4e3c-4495-4884-98cb-71ac0d58d6d1)
![image](https://github.com/geokrety/geokrety-website/assets/176794/f0b038f4-7cb2-49c4-986e-2c066714628d)
