### ISSUE TITLE
Dutch translations not updated on site

### ISSUE THREAD

**Issue by harrieklomp** [geokrety/geokrety-website#91]
There are some translations to Dutch that are not visible on main site. When select online translation function it is translated like it should.
![selectie_182](https://user-images.githubusercontent.com/1060518/41037691-4e8ace2a-6994-11e8-869c-04243fba8de8.png)   ![selectie_183](https://user-images.githubusercontent.com/1060518/41037706-57dcca28-6994-11e8-8cda-334ca56a67cc.png)

**Comment by kumy** [comment]
Thanks. PR#83 is pending. @boly38 do you agree to merge #83?

**Comment by boly38** [comment]
out of my minor review/question,
no problem for me, agree to merge

**Comment by kumy** [comment]
New translations are now merged.
