### ISSUE TITLE
Random omissions when marking geokrets in c:geo

### ISSUE THREAD

**Issue by SDymon** [geokrety/geokrety-website#941]
In the c:geo application, when group marking all available geokrets in the cache, not all geokrets are marked on geokrety.org. What is this connected with?
This was last seen yesterday 02/25/2024.

**Comment by kumy** [comment]
Hi @SDymon, may you please provide more information:

What is your GK username?
Any shorter time window than 24h (which timezone?)
List of concerned GeoKrety?
How many posts in how much time?
Any error message on c:geo

(If you have privacy concerns, you can send that to support@geokrety.org)

/cc @Lineflyer

**Comment by SDymon** [comment]
My account: Dymon
Logs were made between 20:25 and 21:15 Moscow time (GMT +3) 02/25/2024
22 posts
c:geo did not display error messages

List of geokrets to mark:

1,35 zł - Польский злотый
GK15D4A

200 FCFA - Центральноафриканский франк КФА
GK15D51

2½ c - Южноафриканский цент
GK12EC7

2,50 ₽ - Российских рублей
GK165FB

2500л. достижения Бхагваном Махавирой нирваны
GK168AA

2 эскудо Мозамбикской компании
GK14ED2

300 Немецих рейхсмарок
GK11D78

30 Pf. - Восточно Германский пфенинг
GK14D97

35 копеек
GK12F68

3-й Всемирный табачный конгресс
GK15FFB

3 нидерландских цента
GK11DFE

400 Немецких рейхсмарок
GK16A95

4 станция Ходогайя , Утагава Хиросигэ
GK12CC2

50 Итальянских чентезимо
GK12ECA

61 межпарламентская конференция
GK1675A

6 Мальтийских центов
GK15B25

Moscow
GK1195F

XIV Центральноамер-кие и Карибские игры -бокс
GK15FF0

Адам Альбрехта Дюрера
GK15F37

Американский индеец стреляющий по рыбе
GK15B01

Антитело к COVID-19 №17
GK1479C

Атомиум
GK152DD

Афанасий Никитин
GK1467C

Басенджи
GK1580E

Белолобый гусь
GK1346E

Белохвостый райский зимородок
GK16A5A

Бобслеисты с ОИ 1956 года
GK1581A

Большой теннис
GK15BFA

Будильник
GK12719

"Будь готов!" - "Всегда готов!"
GK16526

Бухой Авокадик
GK170B6

Верблюд
GK133C8

Виды Джерси - Белкроут Бэй
GK12EA6

Вилочный погрузчик на аэродроме
GK15BF8

Водолей (японская версия)
GK15800

Воздушный
GK11C3D

Высадка норвежцев в Исландии
GK157FB

Газовый двигатель
GK154A7

Генерал Франко
GK10D01

Гидроэлектростанция Шеннона
GK1228E

Глиняная собака, Садовара
GK156C9

Год Крысы
GK1402C

Годовщина полёта Восток-2
GK1515C

Голубятня
GK14421

Государственный кредитный билет одинъ рубль
GK1690D

Движение юных пионеров
GK114F7

Дендробиум госпожи Сандер
GK163D0

День космонавтитки 1975
GK1299B

Джон Молсон
GK16755

Дискотечный
GK13503

Длиннолистный сахарный кустарник
GK13778

Добыча угля, Нигерия
GK10C14

Друг Наф - Нафа
GK125AF

Дуглас C-47 над кораблём
GK16A61

Ёжик Ёжиков имеет значок аватара
GK13E45

Женщина в движении
GK15F3A

Залив Агана
GK138EE

Замок Корнет
GK16007

Зволенский замок
GK14E81

Зубастик
GK12AA2

Императрица Мария Фёдоровна
GK167DF

Испано Сюиза Булонь
GK12892

Йеменский лев
GK16A55

Кактус Дима
GK167C5

Капская олуша
GK135DC

Карзубый
GK12D04

Карта Самоа
GK15D3B

Кете Штробель
GK146E6

Клиантус пунцовый
GK16005

Коридор против Новой Зеландии
GK154A3

Королева Рокс
GK14317

Королевское шествие
GK156DB

Король и королева -китайские шахматные фигуры
GK15BD3

Кочари понтийский танец
GK12C43

Красное Облако
GK12CCC

Красный мальчик
GK12593

Лара Крофт
GK168DF

Ледниковый Желудь
GK1555C

Лошадиная антилопа
GK10B3D

Мавзолей Пейлин Мукден
GK16961

Масленница в России
GK130BA

Михаил Васильевич Фрунзе
GK13E83

Могилевская ратуша. XVII-XX вв.
GK14709

Мужской портрет
GK168A1

Мухаммад Али Джинна
GK12F57

На севере диком
GK15C0E

Национальный день в Сингапуре (1966 г.)
GK16A7A

Обработка земли
GK149E4

Обучение рабочих
GK141D0

Орден Трудового Красного Знамени
GK121BE

Пейзаж с облаками
GK14262

Первая моторная пожарная машина, 1904 г.
GK113F0

Печать на кувшине
GK15FED

Пихта белая европейская
GK13A3C

Позитивный Арбуз имеет значок аватара
GK12745

Польское дитя
GK15BDC

Портрет П.А. Булахова
GK16A4F

Почтовая карета
GK168A0

Призрак ВИЛа копия 45
GK14536

Приманка
GK118FA

Пролетарии всех стран, соединяйтесь!
GK16A1A

Пуп Земли
GK14D43

Ребёнок на пешеходном переходе
GK151A4

Река Аясэ и Канегафучи
GK15F2A

Руки загребущие. ОР
GK108B4

Синий жук / Blue bug имеет значок аватара
GKB2DC

Скипетр,сельское хозяйство и пром-сть Цейлона
GK13700

Снегирь и снеговик с подарками у ёлки
GK16A52

Советы туристу. 2 Долгая стоянка
GK14C66

Советы туристу. 31 Солнечный удар
GK14C8E

Сокол
GK13050

Соне из Крыма
GK11D5E

СССР - Индия
GK10D5B

Стапелия Леендертц
GK13A51

Стоячий почтовый ящик
GK15AF3

Сумчатый волк
GK14D88

Сцена восстания 1907 года
GK15F4E

Транспортировка резервуара для хранения нефти
GK155FE

Трилон и Перисфера
GK151AA

Укрощение строптивой
GK12E92

Умберту Кастелу Бранку
GK168AE

Учебный корабль Америго Веспуччи
GK1143E

Хит сезона
GK15920

Центральноафриканский гологлазый турако
GK12BA7

Циферблат астрономических часов
GK15BCF

Чатта
GK158A7

Шведская промышленность
GK14F6A

Шри-ланкийское птичье крыло
GK13070

Щукин Борис
GKEC08

Японские марки
GK11407

Японский жук-носорог
GK14247

**Comment by kumy** [comment]
Please see https://geokrety.org/help/api#apiratelimit

**Comment by okainov** [comment]
@kumy would you consider increasing the limit e.g. back to 10k? We have at least 5 users I believe, who are incredibly active GK users and visit a lot of caches with all the Gk... You should be able to check the metrics, how often are clients getting this limit reached? 

Does it really cause too much of an issue if folks add their longs in such huge batches?

**Comment by kumy** [comment]
I checked the logs and honestly I'm not seeing much api over limit. May you privately share their userid so I can double check
I however discovered a bug introduced 2 days ago which affect c:geo `2024.07.07` and `2024.08.09-RC`, see #1051 

--- 
![image](https://github.com/user-attachments/assets/d0e9910f-f1af-4a30-a7cd-88f1b9fc9dda)

![image](https://github.com/user-attachments/assets/d9aff754-5294-4314-9297-87766bbc4ca8)

**Comment by okainov** [comment]
Maybe indeed the root cause of the complaints was what you mentioned #1051 .

However as with API limit, even on the screenshot I see at least 5 spikes over the last 10 days and probably those are coming from known active 2-5 users :) 

In other words, if you don't want to increase general limit for everyone, maybe add some "tiers", so users who are active/old/have some GK in inventory get bigger API limit? While anonymous or newbies get default one (which can be even less than 1500). I would imagine that if the limit is bigger than, let's say `50*(amount of GKs in inventory)`, it should be quite fine even with most active folks (I think if you check profiles of the users already posted here, you'll see that they have hundreds of GKs in their hands if not thousand)

**Comment by kumy** [comment]
This is a nice idea. Would you please track it in a dedicated issue. Thanks

**Comment by SDymon** [comment]
I can't imagine how this can be implemented and how the number of GK in the inventory will be automatically tracked. But for active users with more than a hundred GK in the inventory, this will make it easier to mark GK on the site.
