### ISSUE TITLE
Status - Forbidden, Code - 403

### ISSUE THREAD

**Issue by SDymon** [geokrety/geokrety-website#970]
Hi! For the second day in a row, when opening the geokret page in a new tab, an error appears (on the screen) and then re-authorization is required. What's happening?
![Скрин_бага](https://github.com/geokrety/geokrety-website/assets/150231059/428182e1-0d55-4985-9a83-cf3056324fd2)

**Comment by kumy** [comment]
Only thing that come to my mind may be dynamic IP renewal
