### ISSUE TITLE
Website giving 404 error

### ISSUE THREAD

**Issue by Milfus** [geokrety/geokrety-website#990]
When accessing the website https://geokrety.org I am presented with a "404 page not found error". 
Accessing http://www.geokretymap.org/en also gives me a 404 error but other pages on that website work.

**Comment by kumy** [comment]
I'm sorry for that. We have a problem with the database server which freeze randomly.

**Comment by kumy** [comment]
I'm moving all the databases to a temporary server, that will give us time to diagnose the hardware
